// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shoppb/area.proto

package shoppb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//省
type Prov struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label"`
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value"`
	Children             []*City  `protobuf:"bytes,3,rep,name=children,proto3" json:"children"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prov) Reset()         { *m = Prov{} }
func (m *Prov) String() string { return proto.CompactTextString(m) }
func (*Prov) ProtoMessage()    {}
func (*Prov) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57779f76da783a4, []int{0}
}

func (m *Prov) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prov.Unmarshal(m, b)
}
func (m *Prov) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prov.Marshal(b, m, deterministic)
}
func (m *Prov) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prov.Merge(m, src)
}
func (m *Prov) XXX_Size() int {
	return xxx_messageInfo_Prov.Size(m)
}
func (m *Prov) XXX_DiscardUnknown() {
	xxx_messageInfo_Prov.DiscardUnknown(m)
}

var xxx_messageInfo_Prov proto.InternalMessageInfo

func (m *Prov) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Prov) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Prov) GetChildren() []*City {
	if m != nil {
		return m.Children
	}
	return nil
}

//市
type City struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label"`
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value"`
	Children             []*Coun  `protobuf:"bytes,3,rep,name=children,proto3" json:"children"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57779f76da783a4, []int{1}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *City) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *City) GetChildren() []*Coun {
	if m != nil {
		return m.Children
	}
	return nil
}

// 区
type Coun struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label"`
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coun) Reset()         { *m = Coun{} }
func (m *Coun) String() string { return proto.CompactTextString(m) }
func (*Coun) ProtoMessage()    {}
func (*Coun) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57779f76da783a4, []int{2}
}

func (m *Coun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coun.Unmarshal(m, b)
}
func (m *Coun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coun.Marshal(b, m, deterministic)
}
func (m *Coun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coun.Merge(m, src)
}
func (m *Coun) XXX_Size() int {
	return xxx_messageInfo_Coun.Size(m)
}
func (m *Coun) XXX_DiscardUnknown() {
	xxx_messageInfo_Coun.DiscardUnknown(m)
}

var xxx_messageInfo_Coun proto.InternalMessageInfo

func (m *Coun) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Coun) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ListAreaReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAreaReq) Reset()         { *m = ListAreaReq{} }
func (m *ListAreaReq) String() string { return proto.CompactTextString(m) }
func (*ListAreaReq) ProtoMessage()    {}
func (*ListAreaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57779f76da783a4, []int{3}
}

func (m *ListAreaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAreaReq.Unmarshal(m, b)
}
func (m *ListAreaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAreaReq.Marshal(b, m, deterministic)
}
func (m *ListAreaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAreaReq.Merge(m, src)
}
func (m *ListAreaReq) XXX_Size() int {
	return xxx_messageInfo_ListAreaReq.Size(m)
}
func (m *ListAreaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAreaReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListAreaReq proto.InternalMessageInfo

type ListAreaRes struct {
	Areas                []*Prov  `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAreaRes) Reset()         { *m = ListAreaRes{} }
func (m *ListAreaRes) String() string { return proto.CompactTextString(m) }
func (*ListAreaRes) ProtoMessage()    {}
func (*ListAreaRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57779f76da783a4, []int{4}
}

func (m *ListAreaRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAreaRes.Unmarshal(m, b)
}
func (m *ListAreaRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAreaRes.Marshal(b, m, deterministic)
}
func (m *ListAreaRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAreaRes.Merge(m, src)
}
func (m *ListAreaRes) XXX_Size() int {
	return xxx_messageInfo_ListAreaRes.Size(m)
}
func (m *ListAreaRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAreaRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListAreaRes proto.InternalMessageInfo

func (m *ListAreaRes) GetAreas() []*Prov {
	if m != nil {
		return m.Areas
	}
	return nil
}

func init() {
	proto.RegisterType((*Prov)(nil), "shoppb.Prov")
	proto.RegisterType((*City)(nil), "shoppb.City")
	proto.RegisterType((*Coun)(nil), "shoppb.Coun")
	proto.RegisterType((*ListAreaReq)(nil), "shoppb.ListAreaReq")
	proto.RegisterType((*ListAreaRes)(nil), "shoppb.ListAreaRes")
}

func init() { proto.RegisterFile("shoppb/area.proto", fileDescriptor_a57779f76da783a4) }

var fileDescriptor_a57779f76da783a4 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xb1, 0x4b, 0xc5, 0x30,
	0x10, 0xc6, 0xa9, 0xaf, 0xef, 0xa1, 0x57, 0x1d, 0x8c, 0x0e, 0x45, 0x10, 0x4b, 0xa7, 0x4e, 0x2d,
	0xd6, 0xc1, 0x59, 0x05, 0x5d, 0x1c, 0x24, 0x6e, 0xe2, 0x92, 0xd4, 0xe3, 0x35, 0x90, 0xd7, 0xc4,
	0x24, 0x2d, 0xf8, 0xdf, 0xcb, 0x35, 0x28, 0x15, 0x5c, 0x04, 0xc7, 0xef, 0x77, 0x97, 0xdf, 0xc1,
	0x17, 0x38, 0xf6, 0xbd, 0xb1, 0x56, 0x36, 0xc2, 0xa1, 0xa8, 0xad, 0x33, 0xc1, 0xb0, 0x4d, 0x44,
	0xe5, 0x2b, 0xa4, 0x4f, 0xce, 0x4c, 0xec, 0x14, 0xd6, 0x5a, 0x48, 0xd4, 0x79, 0x52, 0x24, 0xd5,
	0x01, 0x8f, 0x81, 0xe8, 0x24, 0xf4, 0x88, 0xf9, 0x5e, 0x91, 0x54, 0x29, 0x8f, 0x81, 0x55, 0xb0,
	0xdf, 0xf5, 0x4a, 0xbf, 0x39, 0x1c, 0xf2, 0x55, 0xb1, 0xaa, 0xb2, 0xf6, 0xb0, 0x8e, 0xba, 0xfa,
	0x4e, 0x85, 0x0f, 0xfe, 0x3d, 0x25, 0x3b, 0x91, 0x7f, 0xb3, 0x9b, 0x71, 0x58, 0xd8, 0x5b, 0x48,
	0x89, 0xfc, 0xc5, 0x5e, 0x1e, 0x41, 0xf6, 0xa8, 0x7c, 0xb8, 0x71, 0x28, 0x38, 0xbe, 0x97, 0x97,
	0xcb, 0xe8, 0x59, 0x09, 0x6b, 0xea, 0xc8, 0xe7, 0xc9, 0xcf, 0xc3, 0x54, 0x11, 0x8f, 0xa3, 0xf6,
	0x1e, 0x32, 0x5a, 0x7f, 0x46, 0x37, 0xa9, 0x0e, 0xd9, 0x35, 0x64, 0x0f, 0x38, 0x0b, 0x48, 0xc4,
	0x4e, 0xbe, 0x9e, 0x2c, 0xae, 0x9c, 0xfd, 0x02, 0xfd, 0xed, 0xc5, 0xcb, 0xf9, 0x56, 0x85, 0x7e,
	0x94, 0x75, 0x67, 0x76, 0x8d, 0xef, 0xd5, 0xb0, 0x53, 0x5b, 0xd3, 0x58, 0xd9, 0xc4, 0x65, 0xb9,
	0x99, 0x7f, 0xea, 0xea, 0x33, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xf0, 0xe5, 0x16, 0xbe, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AreaServiceClient is the client API for AreaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AreaServiceClient interface {
	GetAreaList(ctx context.Context, in *ListAreaReq, opts ...grpc.CallOption) (*ListAreaRes, error)
}

type areaServiceClient struct {
	cc *grpc.ClientConn
}

func NewAreaServiceClient(cc *grpc.ClientConn) AreaServiceClient {
	return &areaServiceClient{cc}
}

func (c *areaServiceClient) GetAreaList(ctx context.Context, in *ListAreaReq, opts ...grpc.CallOption) (*ListAreaRes, error) {
	out := new(ListAreaRes)
	err := c.cc.Invoke(ctx, "/shoppb.AreaService/GetAreaList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AreaServiceServer is the server API for AreaService service.
type AreaServiceServer interface {
	GetAreaList(context.Context, *ListAreaReq) (*ListAreaRes, error)
}

func RegisterAreaServiceServer(s *grpc.Server, srv AreaServiceServer) {
	s.RegisterService(&_AreaService_serviceDesc, srv)
}

func _AreaService_GetAreaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AreaServiceServer).GetAreaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppb.AreaService/GetAreaList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AreaServiceServer).GetAreaList(ctx, req.(*ListAreaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AreaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shoppb.AreaService",
	HandlerType: (*AreaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAreaList",
			Handler:    _AreaService_GetAreaList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shoppb/area.proto",
}
