// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shoppb/carrier.proto

package shoppb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basepb "github.com/shinmigo/pb/basepb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CarrierStatus int32

const (
	CarrierStatus_CarrierStatusPlaceholder CarrierStatus = 0
	CarrierStatus_Enabled                  CarrierStatus = 1
	CarrierStatus_Disabled                 CarrierStatus = 2
)

var CarrierStatus_name = map[int32]string{
	0: "CarrierStatusPlaceholder",
	1: "Enabled",
	2: "Disabled",
}

var CarrierStatus_value = map[string]int32{
	"CarrierStatusPlaceholder": 0,
	"Enabled":                  1,
	"Disabled":                 2,
}

func (x CarrierStatus) String() string {
	return proto.EnumName(CarrierStatus_name, int32(x))
}

func (CarrierStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d24829979d9c7c59, []int{0}
}

type Carrier struct {
	CarrierId            uint64        `protobuf:"varint,1,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string        `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Sort                 uint32        `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Status               CarrierStatus `protobuf:"varint,5,opt,name=status,proto3,enum=shoppb.CarrierStatus" json:"status,omitempty"`
	AdminId              uint64        `protobuf:"varint,6,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Carrier) Reset()         { *m = Carrier{} }
func (m *Carrier) String() string { return proto.CompactTextString(m) }
func (*Carrier) ProtoMessage()    {}
func (*Carrier) Descriptor() ([]byte, []int) {
	return fileDescriptor_d24829979d9c7c59, []int{0}
}

func (m *Carrier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carrier.Unmarshal(m, b)
}
func (m *Carrier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carrier.Marshal(b, m, deterministic)
}
func (m *Carrier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carrier.Merge(m, src)
}
func (m *Carrier) XXX_Size() int {
	return xxx_messageInfo_Carrier.Size(m)
}
func (m *Carrier) XXX_DiscardUnknown() {
	xxx_messageInfo_Carrier.DiscardUnknown(m)
}

var xxx_messageInfo_Carrier proto.InternalMessageInfo

func (m *Carrier) GetCarrierId() uint64 {
	if m != nil {
		return m.CarrierId
	}
	return 0
}

func (m *Carrier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Carrier) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Carrier) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *Carrier) GetStatus() CarrierStatus {
	if m != nil {
		return m.Status
	}
	return CarrierStatus_CarrierStatusPlaceholder
}

func (m *Carrier) GetAdminId() uint64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

type DelCarrierReq struct {
	CarrierId            uint64   `protobuf:"varint,1,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCarrierReq) Reset()         { *m = DelCarrierReq{} }
func (m *DelCarrierReq) String() string { return proto.CompactTextString(m) }
func (*DelCarrierReq) ProtoMessage()    {}
func (*DelCarrierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d24829979d9c7c59, []int{1}
}

func (m *DelCarrierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCarrierReq.Unmarshal(m, b)
}
func (m *DelCarrierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCarrierReq.Marshal(b, m, deterministic)
}
func (m *DelCarrierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCarrierReq.Merge(m, src)
}
func (m *DelCarrierReq) XXX_Size() int {
	return xxx_messageInfo_DelCarrierReq.Size(m)
}
func (m *DelCarrierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCarrierReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelCarrierReq proto.InternalMessageInfo

func (m *DelCarrierReq) GetCarrierId() uint64 {
	if m != nil {
		return m.CarrierId
	}
	return 0
}

type ListCarrierReq struct {
	Page                 uint64        `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint64        `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Id                   uint64        `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status               CarrierStatus `protobuf:"varint,5,opt,name=status,proto3,enum=shoppb.CarrierStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListCarrierReq) Reset()         { *m = ListCarrierReq{} }
func (m *ListCarrierReq) String() string { return proto.CompactTextString(m) }
func (*ListCarrierReq) ProtoMessage()    {}
func (*ListCarrierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d24829979d9c7c59, []int{2}
}

func (m *ListCarrierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCarrierReq.Unmarshal(m, b)
}
func (m *ListCarrierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCarrierReq.Marshal(b, m, deterministic)
}
func (m *ListCarrierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCarrierReq.Merge(m, src)
}
func (m *ListCarrierReq) XXX_Size() int {
	return xxx_messageInfo_ListCarrierReq.Size(m)
}
func (m *ListCarrierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCarrierReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListCarrierReq proto.InternalMessageInfo

func (m *ListCarrierReq) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListCarrierReq) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCarrierReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListCarrierReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListCarrierReq) GetStatus() CarrierStatus {
	if m != nil {
		return m.Status
	}
	return CarrierStatus_CarrierStatusPlaceholder
}

type CarrierDetail struct {
	CarrierId            uint64        `protobuf:"varint,1,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string        `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Sort                 uint32        `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Status               CarrierStatus `protobuf:"varint,5,opt,name=status,proto3,enum=shoppb.CarrierStatus" json:"status,omitempty"`
	CreatedBy            uint64        `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            uint64        `protobuf:"varint,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt            string        `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string        `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CarrierDetail) Reset()         { *m = CarrierDetail{} }
func (m *CarrierDetail) String() string { return proto.CompactTextString(m) }
func (*CarrierDetail) ProtoMessage()    {}
func (*CarrierDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_d24829979d9c7c59, []int{3}
}

func (m *CarrierDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarrierDetail.Unmarshal(m, b)
}
func (m *CarrierDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarrierDetail.Marshal(b, m, deterministic)
}
func (m *CarrierDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarrierDetail.Merge(m, src)
}
func (m *CarrierDetail) XXX_Size() int {
	return xxx_messageInfo_CarrierDetail.Size(m)
}
func (m *CarrierDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CarrierDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CarrierDetail proto.InternalMessageInfo

func (m *CarrierDetail) GetCarrierId() uint64 {
	if m != nil {
		return m.CarrierId
	}
	return 0
}

func (m *CarrierDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CarrierDetail) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CarrierDetail) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *CarrierDetail) GetStatus() CarrierStatus {
	if m != nil {
		return m.Status
	}
	return CarrierStatus_CarrierStatusPlaceholder
}

func (m *CarrierDetail) GetCreatedBy() uint64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *CarrierDetail) GetUpdatedBy() uint64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *CarrierDetail) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *CarrierDetail) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListCarrierRes struct {
	Total                uint64           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Carriers             []*CarrierDetail `protobuf:"bytes,2,rep,name=carriers,proto3" json:"carriers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListCarrierRes) Reset()         { *m = ListCarrierRes{} }
func (m *ListCarrierRes) String() string { return proto.CompactTextString(m) }
func (*ListCarrierRes) ProtoMessage()    {}
func (*ListCarrierRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d24829979d9c7c59, []int{4}
}

func (m *ListCarrierRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCarrierRes.Unmarshal(m, b)
}
func (m *ListCarrierRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCarrierRes.Marshal(b, m, deterministic)
}
func (m *ListCarrierRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCarrierRes.Merge(m, src)
}
func (m *ListCarrierRes) XXX_Size() int {
	return xxx_messageInfo_ListCarrierRes.Size(m)
}
func (m *ListCarrierRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCarrierRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListCarrierRes proto.InternalMessageInfo

func (m *ListCarrierRes) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListCarrierRes) GetCarriers() []*CarrierDetail {
	if m != nil {
		return m.Carriers
	}
	return nil
}

func init() {
	proto.RegisterEnum("shoppb.CarrierStatus", CarrierStatus_name, CarrierStatus_value)
	proto.RegisterType((*Carrier)(nil), "shoppb.Carrier")
	proto.RegisterType((*DelCarrierReq)(nil), "shoppb.DelCarrierReq")
	proto.RegisterType((*ListCarrierReq)(nil), "shoppb.ListCarrierReq")
	proto.RegisterType((*CarrierDetail)(nil), "shoppb.CarrierDetail")
	proto.RegisterType((*ListCarrierRes)(nil), "shoppb.ListCarrierRes")
}

func init() { proto.RegisterFile("shoppb/carrier.proto", fileDescriptor_d24829979d9c7c59) }

var fileDescriptor_d24829979d9c7c59 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x26, 0x59, 0xd6, 0x26, 0xa7, 0x34, 0x4c, 0x66, 0xa0, 0x50, 0x98, 0x88, 0x72, 0x15, 0x21,
	0x91, 0x88, 0xed, 0x05, 0xe8, 0xe8, 0x04, 0x93, 0xb8, 0x40, 0xd9, 0x15, 0xdc, 0x54, 0x4e, 0x6c,
	0xb5, 0x96, 0xd2, 0x38, 0xc4, 0x2e, 0x52, 0xf7, 0x1c, 0xf0, 0x1a, 0x3c, 0x16, 0xcf, 0x81, 0xfc,
	0x93, 0xae, 0xdd, 0x90, 0x80, 0xbb, 0x5d, 0xe5, 0xf8, 0xfb, 0xce, 0x27, 0x9f, 0xef, 0x73, 0x4f,
	0xe1, 0x58, 0x2c, 0x79, 0xdb, 0x96, 0x79, 0x85, 0xbb, 0x8e, 0xd1, 0x2e, 0x6b, 0x3b, 0x2e, 0x39,
	0x1a, 0x18, 0x74, 0xf2, 0xb8, 0xc4, 0x82, 0xb6, 0x65, 0x6e, 0x3e, 0x86, 0x4c, 0x7e, 0x3a, 0x30,
	0x7c, 0x67, 0xda, 0xd1, 0x09, 0x80, 0x55, 0xce, 0x19, 0x89, 0x9c, 0xd8, 0x49, 0xbd, 0x22, 0xb0,
	0xc8, 0x25, 0x41, 0x08, 0xbc, 0x06, 0xaf, 0x68, 0xe4, 0xc6, 0x4e, 0x1a, 0x14, 0xba, 0x56, 0x58,
	0xc5, 0x09, 0x8d, 0x0e, 0x0c, 0xa6, 0x6a, 0x85, 0x09, 0xde, 0xc9, 0xc8, 0x8b, 0x9d, 0x74, 0x5c,
	0xe8, 0x1a, 0xbd, 0x86, 0x81, 0x90, 0x58, 0xae, 0x45, 0x74, 0x18, 0x3b, 0x69, 0x78, 0xfa, 0x24,
	0x33, 0x43, 0x65, 0xf6, 0xee, 0x2b, 0x4d, 0x16, 0xb6, 0x09, 0x3d, 0x03, 0x1f, 0x93, 0x15, 0x6b,
	0xd4, 0x1c, 0x03, 0x3d, 0xc7, 0x50, 0x9f, 0x2f, 0x49, 0x92, 0xc1, 0x78, 0x46, 0x6b, 0x2b, 0x2b,
	0xe8, 0xd7, 0xbf, 0x4c, 0x9d, 0x7c, 0x77, 0x20, 0xfc, 0xc8, 0x84, 0xdc, 0x51, 0x20, 0xf0, 0x5a,
	0xbc, 0xa0, 0xb6, 0x57, 0xd7, 0xe8, 0x39, 0x04, 0xea, 0x3b, 0x17, 0xec, 0xda, 0x38, 0xf4, 0x0a,
	0x5f, 0x01, 0x57, 0xec, 0x9a, 0xa2, 0x10, 0x5c, 0x46, 0xb4, 0x47, 0xaf, 0x70, 0xd9, 0x4d, 0x12,
	0xde, 0x4e, 0x12, 0xff, 0xe7, 0x30, 0xf9, 0xe1, 0xc2, 0xd8, 0x32, 0x33, 0x2a, 0x31, 0xab, 0xef,
	0x51, 0xfa, 0x6a, 0x92, 0x8e, 0x62, 0x49, 0xc9, 0xbc, 0xdc, 0xd8, 0xfc, 0x03, 0x8b, 0x9c, 0x6f,
	0x14, 0xbd, 0x6e, 0x49, 0x4f, 0x0f, 0x0d, 0x6d, 0x11, 0x43, 0xf7, 0x6a, 0x2c, 0x23, 0x5f, 0x8f,
	0xd6, 0xab, 0xa7, 0x72, 0x57, 0x8d, 0x65, 0x14, 0x18, 0xda, 0x22, 0x53, 0x99, 0x7c, 0xbe, 0xf5,
	0x5a, 0x02, 0x1d, 0xc3, 0xa1, 0xe4, 0x12, 0xd7, 0x36, 0x12, 0x73, 0x40, 0x6f, 0xc0, 0xb7, 0xd9,
	0x88, 0xc8, 0x8d, 0x0f, 0xd2, 0xd1, 0x1d, 0x53, 0x26, 0xd6, 0x62, 0xdb, 0xf6, 0xea, 0xc3, 0x36,
	0x71, 0xe3, 0x17, 0xbd, 0x80, 0x68, 0x0f, 0xf8, 0x54, 0xe3, 0x8a, 0x2e, 0x79, 0x4d, 0x68, 0x77,
	0xf4, 0x00, 0x8d, 0x60, 0x78, 0xd1, 0xe0, 0xb2, 0xa6, 0xe4, 0xc8, 0x41, 0x0f, 0xc1, 0x9f, 0x31,
	0x61, 0x4e, 0xee, 0xe9, 0x2f, 0x07, 0xc2, 0x5e, 0x49, 0xbb, 0x6f, 0xac, 0x52, 0xcf, 0x0f, 0x53,
	0x42, 0xfa, 0x4d, 0x7a, 0x74, 0x6b, 0x96, 0x49, 0x98, 0xd9, 0xad, 0x9b, 0x36, 0x1b, 0x65, 0x2a,
	0x83, 0xd1, 0x05, 0x61, 0xf2, 0x9f, 0xfb, 0xcf, 0x00, 0x6e, 0x7e, 0xf5, 0x68, 0x6b, 0x75, 0x6f,
	0x13, 0xee, 0x88, 0xde, 0x42, 0xf8, 0x9e, 0xf6, 0x77, 0xa8, 0x54, 0xd1, 0xd3, 0x5e, 0xb8, 0xbf,
	0x11, 0x93, 0x3f, 0xe3, 0xe2, 0xfc, 0xe5, 0x97, 0x93, 0x05, 0x93, 0xcb, 0x75, 0x99, 0x55, 0x7c,
	0x95, 0x8b, 0x25, 0x6b, 0x56, 0x6c, 0xc1, 0xf3, 0xb6, 0xcc, 0x4d, 0x7f, 0x39, 0xd0, 0xff, 0x22,
	0x67, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x02, 0xb9, 0xcd, 0x18, 0x7a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CarrierServiceClient is the client API for CarrierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarrierServiceClient interface {
	AddCarrier(ctx context.Context, in *Carrier, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	EditCarrier(ctx context.Context, in *Carrier, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	DelCarrier(ctx context.Context, in *DelCarrierReq, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	GetCarrierList(ctx context.Context, in *ListCarrierReq, opts ...grpc.CallOption) (*ListCarrierRes, error)
}

type carrierServiceClient struct {
	cc *grpc.ClientConn
}

func NewCarrierServiceClient(cc *grpc.ClientConn) CarrierServiceClient {
	return &carrierServiceClient{cc}
}

func (c *carrierServiceClient) AddCarrier(ctx context.Context, in *Carrier, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/shoppb.CarrierService/AddCarrier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carrierServiceClient) EditCarrier(ctx context.Context, in *Carrier, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/shoppb.CarrierService/EditCarrier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carrierServiceClient) DelCarrier(ctx context.Context, in *DelCarrierReq, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/shoppb.CarrierService/DelCarrier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carrierServiceClient) GetCarrierList(ctx context.Context, in *ListCarrierReq, opts ...grpc.CallOption) (*ListCarrierRes, error) {
	out := new(ListCarrierRes)
	err := c.cc.Invoke(ctx, "/shoppb.CarrierService/GetCarrierList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarrierServiceServer is the server API for CarrierService service.
type CarrierServiceServer interface {
	AddCarrier(context.Context, *Carrier) (*basepb.AnyRes, error)
	EditCarrier(context.Context, *Carrier) (*basepb.AnyRes, error)
	DelCarrier(context.Context, *DelCarrierReq) (*basepb.AnyRes, error)
	GetCarrierList(context.Context, *ListCarrierReq) (*ListCarrierRes, error)
}

// UnimplementedCarrierServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCarrierServiceServer struct {
}

func (*UnimplementedCarrierServiceServer) AddCarrier(ctx context.Context, req *Carrier) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCarrier not implemented")
}
func (*UnimplementedCarrierServiceServer) EditCarrier(ctx context.Context, req *Carrier) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCarrier not implemented")
}
func (*UnimplementedCarrierServiceServer) DelCarrier(ctx context.Context, req *DelCarrierReq) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelCarrier not implemented")
}
func (*UnimplementedCarrierServiceServer) GetCarrierList(ctx context.Context, req *ListCarrierReq) (*ListCarrierRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCarrierList not implemented")
}

func RegisterCarrierServiceServer(s *grpc.Server, srv CarrierServiceServer) {
	s.RegisterService(&_CarrierService_serviceDesc, srv)
}

func _CarrierService_AddCarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Carrier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarrierServiceServer).AddCarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppb.CarrierService/AddCarrier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarrierServiceServer).AddCarrier(ctx, req.(*Carrier))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarrierService_EditCarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Carrier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarrierServiceServer).EditCarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppb.CarrierService/EditCarrier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarrierServiceServer).EditCarrier(ctx, req.(*Carrier))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarrierService_DelCarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelCarrierReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarrierServiceServer).DelCarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppb.CarrierService/DelCarrier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarrierServiceServer).DelCarrier(ctx, req.(*DelCarrierReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarrierService_GetCarrierList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCarrierReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarrierServiceServer).GetCarrierList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppb.CarrierService/GetCarrierList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarrierServiceServer).GetCarrierList(ctx, req.(*ListCarrierReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarrierService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shoppb.CarrierService",
	HandlerType: (*CarrierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCarrier",
			Handler:    _CarrierService_AddCarrier_Handler,
		},
		{
			MethodName: "EditCarrier",
			Handler:    _CarrierService_EditCarrier_Handler,
		},
		{
			MethodName: "DelCarrier",
			Handler:    _CarrierService_DelCarrier_Handler,
		},
		{
			MethodName: "GetCarrierList",
			Handler:    _CarrierService_GetCarrierList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shoppb/carrier.proto",
}
