// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shoppb/payment.proto

package shoppb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentCode int32

const (
	PaymentCode_CodeNone PaymentCode = 0
	PaymentCode_Wechat   PaymentCode = 1
	PaymentCode_Alipay   PaymentCode = 2
)

var PaymentCode_name = map[int32]string{
	0: "CodeNone",
	1: "Wechat",
	2: "Alipay",
}

var PaymentCode_value = map[string]int32{
	"CodeNone": 0,
	"Wechat":   1,
	"Alipay":   2,
}

func (x PaymentCode) String() string {
	return proto.EnumName(PaymentCode_name, int32(x))
}

func (PaymentCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a9ad8d900087ce41, []int{0}
}

type PaymentStatus int32

const (
	PaymentStatus_StatusNone PaymentStatus = 0
	PaymentStatus_Open       PaymentStatus = 1
	PaymentStatus_Close      PaymentStatus = 2
)

var PaymentStatus_name = map[int32]string{
	0: "StatusNone",
	1: "Open",
	2: "Close",
}

var PaymentStatus_value = map[string]int32{
	"StatusNone": 0,
	"Open":       1,
	"Close":      2,
}

func (x PaymentStatus) String() string {
	return proto.EnumName(PaymentStatus_name, int32(x))
}

func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a9ad8d900087ce41, []int{1}
}

type ListPaymentReq struct {
	Status               PaymentStatus `protobuf:"varint,1,opt,name=status,proto3,enum=shoppb.PaymentStatus" json:"status"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListPaymentReq) Reset()         { *m = ListPaymentReq{} }
func (m *ListPaymentReq) String() string { return proto.CompactTextString(m) }
func (*ListPaymentReq) ProtoMessage()    {}
func (*ListPaymentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ad8d900087ce41, []int{0}
}

func (m *ListPaymentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentReq.Unmarshal(m, b)
}
func (m *ListPaymentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentReq.Marshal(b, m, deterministic)
}
func (m *ListPaymentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentReq.Merge(m, src)
}
func (m *ListPaymentReq) XXX_Size() int {
	return xxx_messageInfo_ListPaymentReq.Size(m)
}
func (m *ListPaymentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentReq proto.InternalMessageInfo

func (m *ListPaymentReq) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return PaymentStatus_StatusNone
}

type Payment struct {
	Id                   uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Code                 string        `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	Params               string        `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
	Status               PaymentStatus `protobuf:"varint,5,opt,name=status,proto3,enum=shoppb.PaymentStatus" json:"status"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ad8d900087ce41, []int{1}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payment) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Payment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Payment) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *Payment) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return PaymentStatus_StatusNone
}

type ListPaymentRes struct {
	Payments             []*Payment `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListPaymentRes) Reset()         { *m = ListPaymentRes{} }
func (m *ListPaymentRes) String() string { return proto.CompactTextString(m) }
func (*ListPaymentRes) ProtoMessage()    {}
func (*ListPaymentRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ad8d900087ce41, []int{2}
}

func (m *ListPaymentRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentRes.Unmarshal(m, b)
}
func (m *ListPaymentRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentRes.Marshal(b, m, deterministic)
}
func (m *ListPaymentRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentRes.Merge(m, src)
}
func (m *ListPaymentRes) XXX_Size() int {
	return xxx_messageInfo_ListPaymentRes.Size(m)
}
func (m *ListPaymentRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentRes proto.InternalMessageInfo

func (m *ListPaymentRes) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

type PaymentCodeReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentCodeReq) Reset()         { *m = PaymentCodeReq{} }
func (m *PaymentCodeReq) String() string { return proto.CompactTextString(m) }
func (*PaymentCodeReq) ProtoMessage()    {}
func (*PaymentCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ad8d900087ce41, []int{3}
}

func (m *PaymentCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentCodeReq.Unmarshal(m, b)
}
func (m *PaymentCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentCodeReq.Marshal(b, m, deterministic)
}
func (m *PaymentCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentCodeReq.Merge(m, src)
}
func (m *PaymentCodeReq) XXX_Size() int {
	return xxx_messageInfo_PaymentCodeReq.Size(m)
}
func (m *PaymentCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentCodeReq proto.InternalMessageInfo

func (m *PaymentCodeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterEnum("shoppb.PaymentCode", PaymentCode_name, PaymentCode_value)
	proto.RegisterEnum("shoppb.PaymentStatus", PaymentStatus_name, PaymentStatus_value)
	proto.RegisterType((*ListPaymentReq)(nil), "shoppb.ListPaymentReq")
	proto.RegisterType((*Payment)(nil), "shoppb.Payment")
	proto.RegisterType((*ListPaymentRes)(nil), "shoppb.ListPaymentRes")
	proto.RegisterType((*PaymentCodeReq)(nil), "shoppb.PaymentCodeReq")
}

func init() { proto.RegisterFile("shoppb/payment.proto", fileDescriptor_a9ad8d900087ce41) }

var fileDescriptor_a9ad8d900087ce41 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x7d, 0x93, 0xa6, 0x79, 0xed, 0xed, 0x7b, 0x31, 0x5c, 0xb4, 0x84, 0x82, 0x58, 0x8a, 0x8b,
	0x52, 0x31, 0x81, 0xd6, 0x9d, 0x88, 0x1f, 0x15, 0xdc, 0x88, 0x4a, 0xba, 0x10, 0xdc, 0x4d, 0x92,
	0xa1, 0x19, 0x68, 0x32, 0x63, 0x67, 0x2a, 0xf4, 0x1f, 0xb8, 0xf3, 0x2f, 0x4b, 0x3e, 0xfa, 0x89,
	0x0b, 0x57, 0x73, 0xe6, 0xdc, 0x73, 0x2f, 0xe7, 0xdc, 0x19, 0x38, 0x54, 0x89, 0x90, 0x32, 0xf4,
	0x25, 0x5d, 0xa6, 0x2c, 0xd3, 0x9e, 0x9c, 0x0b, 0x2d, 0xd0, 0x2a, 0xd9, 0xde, 0x35, 0xd8, 0x8f,
	0x5c, 0xe9, 0x97, 0xb2, 0x18, 0xb0, 0x77, 0x3c, 0x07, 0x4b, 0x69, 0xaa, 0x17, 0xca, 0x25, 0x5d,
	0xd2, 0xb7, 0x87, 0x47, 0x5e, 0x29, 0xf5, 0x2a, 0xcd, 0xa4, 0x28, 0x06, 0x95, 0xa8, 0xf7, 0x49,
	0xe0, 0x6f, 0x55, 0x41, 0x1b, 0x0c, 0x1e, 0x17, 0x6d, 0x66, 0x60, 0xf0, 0x18, 0x11, 0xcc, 0x48,
	0xc4, 0xcc, 0x35, 0xba, 0xa4, 0xdf, 0x0c, 0x0a, 0x9c, 0x73, 0x19, 0x4d, 0x99, 0x5b, 0x2b, 0xb9,
	0x1c, 0x63, 0x1b, 0x2c, 0x49, 0xe7, 0x34, 0x55, 0xae, 0x59, 0xb0, 0xd5, 0x6d, 0xcb, 0x4a, 0xfd,
	0x37, 0x56, 0xae, 0xf6, 0xb2, 0x28, 0x3c, 0x83, 0x46, 0x15, 0x3b, 0x4f, 0x53, 0xeb, 0xb7, 0x86,
	0x07, 0x7b, 0x23, 0x82, 0xb5, 0xa0, 0x77, 0x0a, 0x76, 0x45, 0x8e, 0x45, 0xcc, 0xf2, 0x55, 0xac,
	0xfc, 0x93, 0x8d, 0xff, 0xc1, 0x08, 0x5a, 0x5b, 0x2a, 0xfc, 0x07, 0x8d, 0xfc, 0x7c, 0x12, 0x19,
	0x73, 0xfe, 0x20, 0x80, 0xf5, 0xca, 0xa2, 0x84, 0x6a, 0x87, 0xe4, 0xf8, 0x76, 0xc6, 0x25, 0x5d,
	0x3a, 0xc6, 0xe0, 0x02, 0xfe, 0xef, 0x58, 0x46, 0x1b, 0xa0, 0x44, 0x55, 0x63, 0x03, 0xcc, 0x67,
	0xc9, 0x32, 0x87, 0x60, 0x13, 0xea, 0xe3, 0x99, 0x50, 0xcc, 0x31, 0x86, 0x5f, 0x64, 0xed, 0x68,
	0xc2, 0xe6, 0x1f, 0x3c, 0x62, 0x78, 0x03, 0xf6, 0x03, 0x5b, 0x25, 0xcc, 0xc3, 0x62, 0x7b, 0x15,
	0x68, 0xf7, 0x19, 0x3b, 0x3f, 0xf3, 0x0a, 0x2f, 0xc1, 0xd9, 0x4c, 0xb8, 0x67, 0x9a, 0xf2, 0xd9,
	0x66, 0xc6, 0x6e, 0xfe, 0xce, 0xfe, 0xb2, 0xee, 0x4e, 0xde, 0x8e, 0xa7, 0x5c, 0x27, 0x8b, 0xd0,
	0x8b, 0x44, 0xea, 0xab, 0x84, 0x67, 0x29, 0x9f, 0x0a, 0x5f, 0x86, 0x7e, 0x29, 0x0c, 0xad, 0xe2,
	0x77, 0x8d, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x85, 0x44, 0x8d, 0xe1, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	GetPaymentList(ctx context.Context, in *ListPaymentReq, opts ...grpc.CallOption) (*ListPaymentRes, error)
	GetPaymentDetail(ctx context.Context, in *PaymentCodeReq, opts ...grpc.CallOption) (*Payment, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) GetPaymentList(ctx context.Context, in *ListPaymentReq, opts ...grpc.CallOption) (*ListPaymentRes, error) {
	out := new(ListPaymentRes)
	err := c.cc.Invoke(ctx, "/shoppb.PaymentService/GetPaymentList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentDetail(ctx context.Context, in *PaymentCodeReq, opts ...grpc.CallOption) (*Payment, error) {
	out := new(Payment)
	err := c.cc.Invoke(ctx, "/shoppb.PaymentService/GetPaymentDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	GetPaymentList(context.Context, *ListPaymentReq) (*ListPaymentRes, error)
	GetPaymentDetail(context.Context, *PaymentCodeReq) (*Payment, error)
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_GetPaymentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppb.PaymentService/GetPaymentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentList(ctx, req.(*ListPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppb.PaymentService/GetPaymentDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentDetail(ctx, req.(*PaymentCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shoppb.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentList",
			Handler:    _PaymentService_GetPaymentList_Handler,
		},
		{
			MethodName: "GetPaymentDetail",
			Handler:    _PaymentService_GetPaymentDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shoppb/payment.proto",
}
