// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderpb/order.proto

package orderpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/shinmigo/pb/basepb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderPaymentType int32

const (
	OrderPaymentType_PaymentTypePlaceholder OrderPaymentType = 0
	OrderPaymentType_Online                 OrderPaymentType = 1
)

var OrderPaymentType_name = map[int32]string{
	0: "PaymentTypePlaceholder",
	1: "Online",
}

var OrderPaymentType_value = map[string]int32{
	"PaymentTypePlaceholder": 0,
	"Online":                 1,
}

func (x OrderPaymentType) String() string {
	return proto.EnumName(OrderPaymentType_name, int32(x))
}

func (OrderPaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{0}
}

type OrderPaymentStatus int32

const (
	OrderPaymentStatus_PaymentStatusPlaceholder OrderPaymentStatus = 0
	OrderPaymentStatus_Unpaid                   OrderPaymentStatus = 1
	OrderPaymentStatus_PartPaid                 OrderPaymentStatus = 2
	OrderPaymentStatus_AllPaid                  OrderPaymentStatus = 3
)

var OrderPaymentStatus_name = map[int32]string{
	0: "PaymentStatusPlaceholder",
	1: "Unpaid",
	2: "PartPaid",
	3: "AllPaid",
}

var OrderPaymentStatus_value = map[string]int32{
	"PaymentStatusPlaceholder": 0,
	"Unpaid":                   1,
	"PartPaid":                 2,
	"AllPaid":                  3,
}

func (x OrderPaymentStatus) String() string {
	return proto.EnumName(OrderPaymentStatus_name, int32(x))
}

func (OrderPaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1}
}

type OrderShippingStatus int32

const (
	OrderShippingStatus_ShippingStatusPlaceholder OrderShippingStatus = 0
	OrderShippingStatus_NotShipped                OrderShippingStatus = 1
	OrderShippingStatus_PartShipped               OrderShippingStatus = 2
	OrderShippingStatus_AllShipped                OrderShippingStatus = 3
)

var OrderShippingStatus_name = map[int32]string{
	0: "ShippingStatusPlaceholder",
	1: "NotShipped",
	2: "PartShipped",
	3: "AllShipped",
}

var OrderShippingStatus_value = map[string]int32{
	"ShippingStatusPlaceholder": 0,
	"NotShipped":                1,
	"PartShipped":               2,
	"AllShipped":                3,
}

func (x OrderShippingStatus) String() string {
	return proto.EnumName(OrderShippingStatus_name, int32(x))
}

func (OrderShippingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{2}
}

type OrderConfirm int32

const (
	OrderConfirm_ConfirmPlaceholder OrderConfirm = 0
	OrderConfirm_ConfirmNo          OrderConfirm = 1
	OrderConfirm_ConfirmYes         OrderConfirm = 2
)

var OrderConfirm_name = map[int32]string{
	0: "ConfirmPlaceholder",
	1: "ConfirmNo",
	2: "ConfirmYes",
}

var OrderConfirm_value = map[string]int32{
	"ConfirmPlaceholder": 0,
	"ConfirmNo":          1,
	"ConfirmYes":         2,
}

func (x OrderConfirm) String() string {
	return proto.EnumName(OrderConfirm_name, int32(x))
}

func (OrderConfirm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{3}
}

type OrderStatus int32

const (
	OrderStatus_StatusPlaceholder OrderStatus = 0
	OrderStatus_PendingPayment    OrderStatus = 1
	OrderStatus_PendingReview     OrderStatus = 2
	OrderStatus_PendingShipment   OrderStatus = 3
	OrderStatus_PendingReceiving  OrderStatus = 4
	OrderStatus_PendingCompletion OrderStatus = 5
	OrderStatus_PendingComment    OrderStatus = 6
	OrderStatus_Canceled          OrderStatus = 7
)

var OrderStatus_name = map[int32]string{
	0: "StatusPlaceholder",
	1: "PendingPayment",
	2: "PendingReview",
	3: "PendingShipment",
	4: "PendingReceiving",
	5: "PendingCompletion",
	6: "PendingComment",
	7: "Canceled",
}

var OrderStatus_value = map[string]int32{
	"StatusPlaceholder": 0,
	"PendingPayment":    1,
	"PendingReview":     2,
	"PendingShipment":   3,
	"PendingReceiving":  4,
	"PendingCompletion": 5,
	"PendingComment":    6,
	"Canceled":          7,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{4}
}

type OrderType int32

const (
	OrderType_TypePlaceholder OrderType = 0
	OrderType_Normal          OrderType = 1
)

var OrderType_name = map[int32]string{
	0: "TypePlaceholder",
	1: "Normal",
}

var OrderType_value = map[string]int32{
	"TypePlaceholder": 0,
	"Normal":          1,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{5}
}

type OrderRefundStatus int32

const (
	OrderRefundStatus_RefundStatusPlaceholder OrderRefundStatus = 0
	OrderRefundStatus_NotRefund               OrderRefundStatus = 1
	OrderRefundStatus_PartRefund              OrderRefundStatus = 2
	OrderRefundStatus_AllRefund               OrderRefundStatus = 3
)

var OrderRefundStatus_name = map[int32]string{
	0: "RefundStatusPlaceholder",
	1: "NotRefund",
	2: "PartRefund",
	3: "AllRefund",
}

var OrderRefundStatus_value = map[string]int32{
	"RefundStatusPlaceholder": 0,
	"NotRefund":               1,
	"PartRefund":              2,
	"AllRefund":               3,
}

func (x OrderRefundStatus) String() string {
	return proto.EnumName(OrderRefundStatus_name, int32(x))
}

func (OrderRefundStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{6}
}

type OrderReturnStatus int32

const (
	OrderReturnStatus_ReturnStatusPlaceholder OrderReturnStatus = 0
	OrderReturnStatus_NotReturn               OrderReturnStatus = 1
	OrderReturnStatus_PartReturn              OrderReturnStatus = 2
	OrderReturnStatus_AllReturn               OrderReturnStatus = 3
)

var OrderReturnStatus_name = map[int32]string{
	0: "ReturnStatusPlaceholder",
	1: "NotReturn",
	2: "PartReturn",
	3: "AllReturn",
}

var OrderReturnStatus_value = map[string]int32{
	"ReturnStatusPlaceholder": 0,
	"NotReturn":               1,
	"PartReturn":              2,
	"AllReturn":               3,
}

func (x OrderReturnStatus) String() string {
	return proto.EnumName(OrderReturnStatus_name, int32(x))
}

func (OrderReturnStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{7}
}

type ListOrderReq struct {
	Page                 uint64      `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint64      `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StoreId              uint64      `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	MemberId             uint64      `protobuf:"varint,4,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	OrderId              uint64      `protobuf:"varint,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StartCreatedAt       string      `protobuf:"bytes,6,opt,name=start_created_at,json=startCreatedAt,proto3" json:"start_created_at,omitempty"`
	EndCreatedAt         string      `protobuf:"bytes,7,opt,name=end_created_at,json=endCreatedAt,proto3" json:"end_created_at,omitempty"`
	OrderStatus          OrderStatus `protobuf:"varint,8,opt,name=order_status,json=orderStatus,proto3,enum=orderpb.OrderStatus" json:"order_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListOrderReq) Reset()         { *m = ListOrderReq{} }
func (m *ListOrderReq) String() string { return proto.CompactTextString(m) }
func (*ListOrderReq) ProtoMessage()    {}
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{0}
}

func (m *ListOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderReq.Unmarshal(m, b)
}
func (m *ListOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderReq.Marshal(b, m, deterministic)
}
func (m *ListOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderReq.Merge(m, src)
}
func (m *ListOrderReq) XXX_Size() int {
	return xxx_messageInfo_ListOrderReq.Size(m)
}
func (m *ListOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderReq proto.InternalMessageInfo

func (m *ListOrderReq) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListOrderReq) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOrderReq) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *ListOrderReq) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *ListOrderReq) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *ListOrderReq) GetStartCreatedAt() string {
	if m != nil {
		return m.StartCreatedAt
	}
	return ""
}

func (m *ListOrderReq) GetEndCreatedAt() string {
	if m != nil {
		return m.EndCreatedAt
	}
	return ""
}

func (m *ListOrderReq) GetOrderStatus() OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return OrderStatus_StatusPlaceholder
}

type OrderDetail struct {
	OrderId              uint64                     `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StoreId              uint64                     `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	MemberId             uint64                     `protobuf:"varint,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	OrderType            OrderType                  `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=orderpb.OrderType" json:"order_type,omitempty"`
	Subtotal             float64                    `protobuf:"fixed64,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	GrandTotal           float64                    `protobuf:"fixed64,6,opt,name=grand_total,json=grandTotal,proto3" json:"grand_total,omitempty"`
	TotalPaid            float64                    `protobuf:"fixed64,7,opt,name=total_paid,json=totalPaid,proto3" json:"total_paid,omitempty"`
	ShippingAmount       float64                    `protobuf:"fixed64,8,opt,name=shipping_amount,json=shippingAmount,proto3" json:"shipping_amount,omitempty"`
	DiscountAmount       float64                    `protobuf:"fixed64,9,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	PaymentType          OrderPaymentType           `protobuf:"varint,10,opt,name=payment_type,json=paymentType,proto3,enum=orderpb.OrderPaymentType" json:"payment_type,omitempty"`
	PaymentStatus        OrderPaymentStatus         `protobuf:"varint,11,opt,name=payment_status,json=paymentStatus,proto3,enum=orderpb.OrderPaymentStatus" json:"payment_status,omitempty"`
	PaymentTime          string                     `protobuf:"bytes,12,opt,name=payment_time,json=paymentTime,proto3" json:"payment_time,omitempty"`
	ShippingStatus       OrderShippingStatus        `protobuf:"varint,13,opt,name=shipping_status,json=shippingStatus,proto3,enum=orderpb.OrderShippingStatus" json:"shipping_status,omitempty"`
	ShippingTime         string                     `protobuf:"bytes,14,opt,name=shipping_time,json=shippingTime,proto3" json:"shipping_time,omitempty"`
	Confirm              OrderConfirm               `protobuf:"varint,15,opt,name=confirm,proto3,enum=orderpb.OrderConfirm" json:"confirm,omitempty"`
	ConfigTime           string                     `protobuf:"bytes,16,opt,name=config_time,json=configTime,proto3" json:"config_time,omitempty"`
	OrderStatus          OrderStatus                `protobuf:"varint,17,opt,name=order_status,json=orderStatus,proto3,enum=orderpb.OrderStatus" json:"order_status,omitempty"`
	RefundStatus         OrderRefundStatus          `protobuf:"varint,18,opt,name=refund_status,json=refundStatus,proto3,enum=orderpb.OrderRefundStatus" json:"refund_status,omitempty"`
	ReturnStatus         OrderReturnStatus          `protobuf:"varint,19,opt,name=return_status,json=returnStatus,proto3,enum=orderpb.OrderReturnStatus" json:"return_status,omitempty"`
	UserNote             string                     `protobuf:"bytes,20,opt,name=user_note,json=userNote,proto3" json:"user_note,omitempty"`
	OrderItems           []*OrderDetail_OrderItems  `protobuf:"bytes,21,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	OrderAddress         *OrderDetail_OrderAddress  `protobuf:"bytes,22,opt,name=order_address,json=orderAddress,proto3" json:"order_address,omitempty"`
	OrderPayment         *OrderDetail_OrderPayment  `protobuf:"bytes,23,opt,name=order_payment,json=orderPayment,proto3" json:"order_payment,omitempty"`
	OrderShipment        *OrderDetail_OrderShipment `protobuf:"bytes,24,opt,name=order_shipment,json=orderShipment,proto3" json:"order_shipment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *OrderDetail) Reset()         { *m = OrderDetail{} }
func (m *OrderDetail) String() string { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()    {}
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1}
}

func (m *OrderDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail.Unmarshal(m, b)
}
func (m *OrderDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail.Marshal(b, m, deterministic)
}
func (m *OrderDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail.Merge(m, src)
}
func (m *OrderDetail) XXX_Size() int {
	return xxx_messageInfo_OrderDetail.Size(m)
}
func (m *OrderDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail proto.InternalMessageInfo

func (m *OrderDetail) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDetail) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *OrderDetail) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *OrderDetail) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_TypePlaceholder
}

func (m *OrderDetail) GetSubtotal() float64 {
	if m != nil {
		return m.Subtotal
	}
	return 0
}

func (m *OrderDetail) GetGrandTotal() float64 {
	if m != nil {
		return m.GrandTotal
	}
	return 0
}

func (m *OrderDetail) GetTotalPaid() float64 {
	if m != nil {
		return m.TotalPaid
	}
	return 0
}

func (m *OrderDetail) GetShippingAmount() float64 {
	if m != nil {
		return m.ShippingAmount
	}
	return 0
}

func (m *OrderDetail) GetDiscountAmount() float64 {
	if m != nil {
		return m.DiscountAmount
	}
	return 0
}

func (m *OrderDetail) GetPaymentType() OrderPaymentType {
	if m != nil {
		return m.PaymentType
	}
	return OrderPaymentType_PaymentTypePlaceholder
}

func (m *OrderDetail) GetPaymentStatus() OrderPaymentStatus {
	if m != nil {
		return m.PaymentStatus
	}
	return OrderPaymentStatus_PaymentStatusPlaceholder
}

func (m *OrderDetail) GetPaymentTime() string {
	if m != nil {
		return m.PaymentTime
	}
	return ""
}

func (m *OrderDetail) GetShippingStatus() OrderShippingStatus {
	if m != nil {
		return m.ShippingStatus
	}
	return OrderShippingStatus_ShippingStatusPlaceholder
}

func (m *OrderDetail) GetShippingTime() string {
	if m != nil {
		return m.ShippingTime
	}
	return ""
}

func (m *OrderDetail) GetConfirm() OrderConfirm {
	if m != nil {
		return m.Confirm
	}
	return OrderConfirm_ConfirmPlaceholder
}

func (m *OrderDetail) GetConfigTime() string {
	if m != nil {
		return m.ConfigTime
	}
	return ""
}

func (m *OrderDetail) GetOrderStatus() OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return OrderStatus_StatusPlaceholder
}

func (m *OrderDetail) GetRefundStatus() OrderRefundStatus {
	if m != nil {
		return m.RefundStatus
	}
	return OrderRefundStatus_RefundStatusPlaceholder
}

func (m *OrderDetail) GetReturnStatus() OrderReturnStatus {
	if m != nil {
		return m.ReturnStatus
	}
	return OrderReturnStatus_ReturnStatusPlaceholder
}

func (m *OrderDetail) GetUserNote() string {
	if m != nil {
		return m.UserNote
	}
	return ""
}

func (m *OrderDetail) GetOrderItems() []*OrderDetail_OrderItems {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

func (m *OrderDetail) GetOrderAddress() *OrderDetail_OrderAddress {
	if m != nil {
		return m.OrderAddress
	}
	return nil
}

func (m *OrderDetail) GetOrderPayment() *OrderDetail_OrderPayment {
	if m != nil {
		return m.OrderPayment
	}
	return nil
}

func (m *OrderDetail) GetOrderShipment() *OrderDetail_OrderShipment {
	if m != nil {
		return m.OrderShipment
	}
	return nil
}

type OrderDetail_OrderItems struct {
	OrderItemId          uint64   `protobuf:"varint,1,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	ProductId            uint64   `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sku                  string   `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Price                float64  `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice             float64  `protobuf:"fixed64,7,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	TotalPayable         float64  `protobuf:"fixed64,8,opt,name=total_payable,json=totalPayable,proto3" json:"total_payable,omitempty"`
	TotalDiscountAmount  float64  `protobuf:"fixed64,9,opt,name=total_discount_amount,json=totalDiscountAmount,proto3" json:"total_discount_amount,omitempty"`
	QtyOrdered           uint64   `protobuf:"varint,10,opt,name=qty_ordered,json=qtyOrdered,proto3" json:"qty_ordered,omitempty"`
	Weight               float64  `protobuf:"fixed64,11,opt,name=weight,proto3" json:"weight,omitempty"`
	Volume               float64  `protobuf:"fixed64,12,opt,name=volume,proto3" json:"volume,omitempty"`
	Spec                 string   `protobuf:"bytes,13,opt,name=spec,proto3" json:"spec,omitempty"`
	QtyShipped           uint64   `protobuf:"varint,14,opt,name=qty_shipped,json=qtyShipped,proto3" json:"qty_shipped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail_OrderItems) Reset()         { *m = OrderDetail_OrderItems{} }
func (m *OrderDetail_OrderItems) String() string { return proto.CompactTextString(m) }
func (*OrderDetail_OrderItems) ProtoMessage()    {}
func (*OrderDetail_OrderItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1, 0}
}

func (m *OrderDetail_OrderItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail_OrderItems.Unmarshal(m, b)
}
func (m *OrderDetail_OrderItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail_OrderItems.Marshal(b, m, deterministic)
}
func (m *OrderDetail_OrderItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail_OrderItems.Merge(m, src)
}
func (m *OrderDetail_OrderItems) XXX_Size() int {
	return xxx_messageInfo_OrderDetail_OrderItems.Size(m)
}
func (m *OrderDetail_OrderItems) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail_OrderItems.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail_OrderItems proto.InternalMessageInfo

func (m *OrderDetail_OrderItems) GetOrderItemId() uint64 {
	if m != nil {
		return m.OrderItemId
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetProductId() uint64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderDetail_OrderItems) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *OrderDetail_OrderItems) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *OrderDetail_OrderItems) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetOldPrice() float64 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetTotalPayable() float64 {
	if m != nil {
		return m.TotalPayable
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetTotalDiscountAmount() float64 {
	if m != nil {
		return m.TotalDiscountAmount
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetQtyOrdered() uint64 {
	if m != nil {
		return m.QtyOrdered
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *OrderDetail_OrderItems) GetQtyShipped() uint64 {
	if m != nil {
		return m.QtyShipped
	}
	return 0
}

type OrderDetail_OrderAddress struct {
	OrderAddressId       uint64   `protobuf:"varint,1,opt,name=order_address_id,json=orderAddressId,proto3" json:"order_address_id,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Telephone            string   `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Province             string   `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Region               string   `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Street               string   `protobuf:"bytes,7,opt,name=street,proto3" json:"street,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail_OrderAddress) Reset()         { *m = OrderDetail_OrderAddress{} }
func (m *OrderDetail_OrderAddress) String() string { return proto.CompactTextString(m) }
func (*OrderDetail_OrderAddress) ProtoMessage()    {}
func (*OrderDetail_OrderAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1, 1}
}

func (m *OrderDetail_OrderAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail_OrderAddress.Unmarshal(m, b)
}
func (m *OrderDetail_OrderAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail_OrderAddress.Marshal(b, m, deterministic)
}
func (m *OrderDetail_OrderAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail_OrderAddress.Merge(m, src)
}
func (m *OrderDetail_OrderAddress) XXX_Size() int {
	return xxx_messageInfo_OrderDetail_OrderAddress.Size(m)
}
func (m *OrderDetail_OrderAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail_OrderAddress.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail_OrderAddress proto.InternalMessageInfo

func (m *OrderDetail_OrderAddress) GetOrderAddressId() uint64 {
	if m != nil {
		return m.OrderAddressId
	}
	return 0
}

func (m *OrderDetail_OrderAddress) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

type OrderDetail_OrderPayment struct {
	OrderPaymentId       uint64   `protobuf:"varint,1,opt,name=order_payment_id,json=orderPaymentId,proto3" json:"order_payment_id,omitempty"`
	PaymentCode          string   `protobuf:"bytes,2,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	PaymentName          string   `protobuf:"bytes,3,opt,name=payment_name,json=paymentName,proto3" json:"payment_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail_OrderPayment) Reset()         { *m = OrderDetail_OrderPayment{} }
func (m *OrderDetail_OrderPayment) String() string { return proto.CompactTextString(m) }
func (*OrderDetail_OrderPayment) ProtoMessage()    {}
func (*OrderDetail_OrderPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1, 2}
}

func (m *OrderDetail_OrderPayment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail_OrderPayment.Unmarshal(m, b)
}
func (m *OrderDetail_OrderPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail_OrderPayment.Marshal(b, m, deterministic)
}
func (m *OrderDetail_OrderPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail_OrderPayment.Merge(m, src)
}
func (m *OrderDetail_OrderPayment) XXX_Size() int {
	return xxx_messageInfo_OrderDetail_OrderPayment.Size(m)
}
func (m *OrderDetail_OrderPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail_OrderPayment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail_OrderPayment proto.InternalMessageInfo

func (m *OrderDetail_OrderPayment) GetOrderPaymentId() uint64 {
	if m != nil {
		return m.OrderPaymentId
	}
	return 0
}

func (m *OrderDetail_OrderPayment) GetPaymentCode() string {
	if m != nil {
		return m.PaymentCode
	}
	return ""
}

func (m *OrderDetail_OrderPayment) GetPaymentName() string {
	if m != nil {
		return m.PaymentName
	}
	return ""
}

type OrderDetail_OrderShipment struct {
	CarrierName          string   `protobuf:"bytes,1,opt,name=carrier_name,json=carrierName,proto3" json:"carrier_name,omitempty"`
	TrackingNumber       string   `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail_OrderShipment) Reset()         { *m = OrderDetail_OrderShipment{} }
func (m *OrderDetail_OrderShipment) String() string { return proto.CompactTextString(m) }
func (*OrderDetail_OrderShipment) ProtoMessage()    {}
func (*OrderDetail_OrderShipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1, 3}
}

func (m *OrderDetail_OrderShipment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail_OrderShipment.Unmarshal(m, b)
}
func (m *OrderDetail_OrderShipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail_OrderShipment.Marshal(b, m, deterministic)
}
func (m *OrderDetail_OrderShipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail_OrderShipment.Merge(m, src)
}
func (m *OrderDetail_OrderShipment) XXX_Size() int {
	return xxx_messageInfo_OrderDetail_OrderShipment.Size(m)
}
func (m *OrderDetail_OrderShipment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail_OrderShipment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail_OrderShipment proto.InternalMessageInfo

func (m *OrderDetail_OrderShipment) GetCarrierName() string {
	if m != nil {
		return m.CarrierName
	}
	return ""
}

func (m *OrderDetail_OrderShipment) GetTrackingNumber() string {
	if m != nil {
		return m.TrackingNumber
	}
	return ""
}

type ListOrderRes struct {
	Total                uint64         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Orders               []*OrderDetail `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListOrderRes) Reset()         { *m = ListOrderRes{} }
func (m *ListOrderRes) String() string { return proto.CompactTextString(m) }
func (*ListOrderRes) ProtoMessage()    {}
func (*ListOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{2}
}

func (m *ListOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderRes.Unmarshal(m, b)
}
func (m *ListOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderRes.Marshal(b, m, deterministic)
}
func (m *ListOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderRes.Merge(m, src)
}
func (m *ListOrderRes) XXX_Size() int {
	return xxx_messageInfo_ListOrderRes.Size(m)
}
func (m *ListOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderRes proto.InternalMessageInfo

func (m *ListOrderRes) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListOrderRes) GetOrders() []*OrderDetail {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterEnum("orderpb.OrderPaymentType", OrderPaymentType_name, OrderPaymentType_value)
	proto.RegisterEnum("orderpb.OrderPaymentStatus", OrderPaymentStatus_name, OrderPaymentStatus_value)
	proto.RegisterEnum("orderpb.OrderShippingStatus", OrderShippingStatus_name, OrderShippingStatus_value)
	proto.RegisterEnum("orderpb.OrderConfirm", OrderConfirm_name, OrderConfirm_value)
	proto.RegisterEnum("orderpb.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterEnum("orderpb.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("orderpb.OrderRefundStatus", OrderRefundStatus_name, OrderRefundStatus_value)
	proto.RegisterEnum("orderpb.OrderReturnStatus", OrderReturnStatus_name, OrderReturnStatus_value)
	proto.RegisterType((*ListOrderReq)(nil), "orderpb.ListOrderReq")
	proto.RegisterType((*OrderDetail)(nil), "orderpb.OrderDetail")
	proto.RegisterType((*OrderDetail_OrderItems)(nil), "orderpb.OrderDetail.OrderItems")
	proto.RegisterType((*OrderDetail_OrderAddress)(nil), "orderpb.OrderDetail.OrderAddress")
	proto.RegisterType((*OrderDetail_OrderPayment)(nil), "orderpb.OrderDetail.OrderPayment")
	proto.RegisterType((*OrderDetail_OrderShipment)(nil), "orderpb.OrderDetail.OrderShipment")
	proto.RegisterType((*ListOrderRes)(nil), "orderpb.ListOrderRes")
}

func init() { proto.RegisterFile("orderpb/order.proto", fileDescriptor_87a9833f63666870) }

var fileDescriptor_87a9833f63666870 = []byte{
	// 1366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x9e, 0xec, 0xfc, 0xf9, 0xf8, 0x27, 0x0a, 0xf3, 0x53, 0xd5, 0x6d, 0xd7, 0x34, 0x1d, 0xb0,
	0x20, 0x28, 0x12, 0x2c, 0xbb, 0x18, 0x30, 0x14, 0xd8, 0xd2, 0xb4, 0x1b, 0x0c, 0x14, 0x69, 0xa0,
	0x74, 0x17, 0xdd, 0x80, 0x19, 0xb2, 0x78, 0x6a, 0x13, 0x95, 0x44, 0x95, 0xa2, 0x53, 0xb8, 0x17,
	0x7b, 0x91, 0x61, 0xcf, 0xb0, 0x77, 0xd9, 0x6b, 0xec, 0x25, 0x06, 0x1e, 0x52, 0xb6, 0x94, 0xb8,
	0xdb, 0xae, 0xcc, 0xef, 0x3b, 0x7f, 0x3c, 0x87, 0xe4, 0x39, 0x32, 0x6c, 0x4b, 0xc5, 0x51, 0xe5,
	0xa3, 0x13, 0xfa, 0x3d, 0xce, 0x95, 0xd4, 0x92, 0xad, 0x3b, 0xb2, 0xbf, 0x3d, 0x8a, 0x0a, 0xcc,
	0x47, 0x27, 0xf6, 0xc7, 0x4a, 0x0f, 0x7e, 0x6f, 0x40, 0xe7, 0xa5, 0x28, 0xf4, 0x2b, 0xa3, 0x14,
	0xe2, 0x7b, 0xc6, 0x60, 0x25, 0x8f, 0xc6, 0x18, 0x78, 0xfb, 0xde, 0xe1, 0x4a, 0x48, 0x6b, 0x76,
	0x0f, 0x5a, 0xe6, 0x77, 0x58, 0x88, 0x8f, 0x18, 0x34, 0x48, 0xb0, 0x61, 0x88, 0x2b, 0xf1, 0x11,
	0xd9, 0x5d, 0xd8, 0x28, 0xb4, 0x54, 0x38, 0x14, 0x3c, 0x68, 0x92, 0x6c, 0x9d, 0xf0, 0x80, 0x1b,
	0xbb, 0x14, 0xd3, 0x11, 0x2a, 0x23, 0x5b, 0xb1, 0x76, 0x96, 0x18, 0x70, 0x63, 0x47, 0x3b, 0x33,
	0xb2, 0x55, 0x6b, 0x47, 0x78, 0xc0, 0xd9, 0x21, 0xf8, 0x85, 0x8e, 0x94, 0x1e, 0xc6, 0x0a, 0x23,
	0x8d, 0x7c, 0x18, 0xe9, 0x60, 0x6d, 0xdf, 0x3b, 0x6c, 0x85, 0x3d, 0xe2, 0xcf, 0x2d, 0x7d, 0xa6,
	0xd9, 0x17, 0xd0, 0xc3, 0x8c, 0x57, 0xf5, 0xd6, 0x49, 0xaf, 0x83, 0x19, 0x5f, 0x68, 0x7d, 0x03,
	0x1d, 0x1b, 0xaa, 0xd0, 0x91, 0x9e, 0x16, 0xc1, 0xc6, 0xbe, 0x77, 0xd8, 0x3b, 0xdd, 0x39, 0x76,
	0x95, 0x39, 0xa6, 0xe4, 0xaf, 0x48, 0x16, 0xb6, 0xe5, 0x02, 0x1c, 0xfc, 0xbd, 0x09, 0x6d, 0x12,
	0x3e, 0x47, 0x1d, 0x89, 0xa4, 0xb6, 0x67, 0xaf, 0xbe, 0xe7, 0x6a, 0x19, 0x1a, 0xff, 0x52, 0x86,
	0xe6, 0x8d, 0x32, 0x7c, 0x05, 0x60, 0x5d, 0xea, 0x59, 0x8e, 0x54, 0xa4, 0xde, 0x29, 0xab, 0xef,
	0xec, 0xf5, 0x2c, 0xc7, 0xb0, 0x25, 0xcb, 0x25, 0xeb, 0xc3, 0x46, 0x31, 0x1d, 0x69, 0xa9, 0xa3,
	0x84, 0x2a, 0xe7, 0x85, 0x73, 0xcc, 0x1e, 0x42, 0x7b, 0xac, 0xa2, 0x8c, 0x0f, 0xad, 0x78, 0x8d,
	0xc4, 0x40, 0xd4, 0x6b, 0x52, 0x78, 0x00, 0x40, 0xa2, 0x61, 0x1e, 0x09, 0x4e, 0xd5, 0xf2, 0xc2,
	0x16, 0x31, 0x97, 0x91, 0xe0, 0xec, 0x4b, 0xd8, 0x2c, 0x26, 0x22, 0xcf, 0x45, 0x36, 0x1e, 0x46,
	0xa9, 0x9c, 0x66, 0x9a, 0xaa, 0xe5, 0x85, 0xbd, 0x92, 0x3e, 0x23, 0xd6, 0x28, 0x72, 0x51, 0xc4,
	0x66, 0x5d, 0x2a, 0xb6, 0xac, 0x62, 0x49, 0x3b, 0xc5, 0xa7, 0xd0, 0xc9, 0xa3, 0x59, 0x8a, 0x99,
	0xb6, 0x29, 0x02, 0xa5, 0x78, 0xb7, 0x9e, 0xe2, 0xa5, 0xd5, 0xa0, 0x4c, 0xdb, 0xf9, 0x02, 0xb0,
	0x67, 0xd0, 0x2b, 0xad, 0xdd, 0xe1, 0xb5, 0xc9, 0xfe, 0xde, 0x52, 0x7b, 0x77, 0x86, 0xdd, 0xbc,
	0x0a, 0xd9, 0xa3, 0xca, 0x0e, 0x44, 0x8a, 0x41, 0x87, 0xae, 0xc8, 0x3c, 0x8c, 0x48, 0x91, 0xbd,
	0xa8, 0xa4, 0xed, 0xe2, 0x74, 0x29, 0xce, 0xfd, 0x1b, 0x97, 0xc4, 0x29, 0xb9, 0x40, 0xf3, 0xa2,
	0xb8, 0x48, 0x8f, 0xa1, 0x3b, 0x77, 0x43, 0xa1, 0x7a, 0xf6, 0x36, 0x96, 0x24, 0xc5, 0x3a, 0x81,
	0xf5, 0x58, 0x66, 0x6f, 0x85, 0x4a, 0x83, 0x4d, 0x8a, 0xb1, 0x5b, 0x8f, 0x71, 0x6e, 0x85, 0x61,
	0xa9, 0x65, 0xce, 0x94, 0x96, 0xce, 0xa7, 0x4f, 0x3e, 0xc1, 0x52, 0xe4, 0xf1, 0xe6, 0xfd, 0xde,
	0xfa, 0x9f, 0xf7, 0x9b, 0x7d, 0x07, 0x5d, 0x85, 0x6f, 0xa7, 0x19, 0x2f, 0x2d, 0x19, 0x59, 0xf6,
	0xeb, 0x96, 0x21, 0xa9, 0x38, 0xfb, 0x8e, 0xaa, 0x20, 0xeb, 0x40, 0x4f, 0x55, 0x56, 0x3a, 0xd8,
	0x5e, 0xee, 0xc0, 0xa8, 0x2c, 0x1c, 0x2c, 0x90, 0x79, 0x1b, 0xd3, 0x02, 0xd5, 0x30, 0x93, 0x1a,
	0x83, 0x1d, 0xca, 0x6c, 0xc3, 0x10, 0x17, 0x52, 0x23, 0xfb, 0x1e, 0xda, 0xee, 0xb9, 0x69, 0x4c,
	0x8b, 0x60, 0x77, 0xbf, 0x79, 0xd8, 0x3e, 0x7d, 0x58, 0xf7, 0x6d, 0x5f, 0xa6, 0x5d, 0x0f, 0x8c,
	0x5a, 0x68, 0xdf, 0x13, 0xad, 0xd9, 0x0f, 0xd0, 0xb5, 0x1e, 0x22, 0xce, 0x15, 0x16, 0x45, 0xb0,
	0xb7, 0xef, 0x1d, 0xb6, 0x4f, 0x1f, 0x7d, 0xda, 0xc7, 0x99, 0x55, 0x0c, 0x6d, 0x45, 0x1d, 0x5a,
	0xf8, 0x71, 0x97, 0x26, 0xb8, 0xf3, 0x5f, 0x7e, 0xdc, 0x8d, 0x74, 0x7e, 0x1c, 0x62, 0x03, 0xe8,
	0xb9, 0x93, 0x9a, 0x88, 0x9c, 0x1c, 0x05, 0xe4, 0xe8, 0xe0, 0xd3, 0x8e, 0xae, 0x9c, 0x66, 0x68,
	0x77, 0x50, 0xc2, 0xfe, 0x1f, 0x4d, 0x80, 0x45, 0xd6, 0xec, 0xa0, 0xdc, 0xa1, 0xa9, 0xd5, 0xa2,
	0x3f, 0xb5, 0xe7, 0xc5, 0x18, 0x70, 0xf3, 0xf6, 0x73, 0x25, 0xf9, 0x34, 0xd6, 0x8b, 0x2e, 0xd5,
	0x72, 0xcc, 0x80, 0x9b, 0xd6, 0x9f, 0x45, 0x29, 0x52, 0x8b, 0x6a, 0x85, 0xb4, 0x66, 0x3e, 0x34,
	0x8b, 0x77, 0x53, 0xea, 0x4b, 0xad, 0xd0, 0x2c, 0xd9, 0x0e, 0xac, 0x8a, 0xd4, 0x4c, 0x88, 0x55,
	0xe2, 0x2c, 0x30, 0x6c, 0xae, 0x44, 0x8c, 0xae, 0xe3, 0x58, 0x60, 0x4e, 0x57, 0x26, 0x7c, 0x68,
	0x25, 0xb6, 0xd7, 0x6c, 0xc8, 0x84, 0x5f, 0x92, 0xf0, 0x31, 0x74, 0xcb, 0x4e, 0x34, 0x8b, 0x46,
	0x09, 0xba, 0x46, 0xd3, 0x71, 0xcd, 0x88, 0x38, 0x76, 0x0a, 0xbb, 0x56, 0x69, 0x79, 0xb3, 0xd9,
	0x26, 0xe1, 0xf3, 0x7a, 0xc7, 0x79, 0x08, 0xed, 0xf7, 0x7a, 0x36, 0xa4, 0xcc, 0x91, 0x53, 0xc3,
	0x59, 0x09, 0xe1, 0xbd, 0x9e, 0xbd, 0xb2, 0x0c, 0xdb, 0x83, 0xb5, 0x0f, 0x28, 0xc6, 0x13, 0x4d,
	0xcd, 0xc4, 0x0b, 0x1d, 0x32, 0xfc, 0xb5, 0x4c, 0xa6, 0xae, 0x45, 0x78, 0xa1, 0x43, 0xa6, 0x30,
	0x45, 0x8e, 0x31, 0xb5, 0x84, 0x56, 0x48, 0xeb, 0x32, 0x08, 0xbd, 0x6c, 0xe4, 0xf4, 0xd0, 0x6d,
	0x90, 0x2b, 0xcb, 0xf4, 0xff, 0xf2, 0xa0, 0x53, 0xbd, 0x51, 0x66, 0xaa, 0xd5, 0xee, 0xe2, 0xe2,
	0x90, 0x7a, 0xd5, 0xbb, 0x36, 0xe0, 0xa6, 0xc1, 0x2b, 0x8c, 0x51, 0x5c, 0xa3, 0xa2, 0x53, 0x6a,
	0x85, 0x73, 0xcc, 0xee, 0x43, 0x4b, 0x63, 0x82, 0xf9, 0x44, 0x66, 0xe5, 0x49, 0x2d, 0x08, 0x63,
	0x99, 0x2b, 0x79, 0x2d, 0xb2, 0x18, 0xdd, 0x99, 0xcd, 0xb1, 0xc9, 0x22, 0x16, 0x7a, 0xe6, 0xce,
	0x8d, 0xd6, 0x26, 0x63, 0x85, 0x63, 0x21, 0x33, 0x37, 0x5f, 0x1d, 0x32, 0x7c, 0xa1, 0x15, 0x62,
	0x39, 0x4f, 0x1d, 0xea, 0xff, 0xe6, 0x72, 0x2a, 0xef, 0xf3, 0x3c, 0xa7, 0xb2, 0xc1, 0xde, 0xc8,
	0xc9, 0xe9, 0x0d, 0x78, 0xb5, 0x09, 0xc7, 0x92, 0xa3, 0xcb, 0xab, 0x6c, 0xc2, 0xe7, 0x92, 0x63,
	0x55, 0xa5, 0x72, 0x0f, 0x4b, 0x95, 0x8b, 0x28, 0xc5, 0xfe, 0x2f, 0xd0, 0xad, 0x3d, 0x0a, 0x63,
	0x13, 0x47, 0x4a, 0x09, 0xd3, 0x42, 0x8c, 0x8d, 0x67, 0x6d, 0x1c, 0x67, 0x6c, 0xcc, 0xa4, 0xd2,
	0x2a, 0x8a, 0xdf, 0x99, 0xa6, 0x9c, 0x4d, 0xcd, 0xd8, 0x75, 0xc1, 0x7b, 0x25, 0x7d, 0x41, 0xec,
	0x41, 0x58, 0xfb, 0x14, 0x2a, 0xcc, 0x9d, 0xb6, 0x53, 0xd4, 0x66, 0x64, 0x01, 0x7b, 0x02, 0x6b,
	0x94, 0x5a, 0x11, 0x34, 0xa8, 0x1f, 0xed, 0x2c, 0x7b, 0xba, 0xa1, 0xd3, 0x39, 0xfa, 0x16, 0xfc,
	0x9b, 0x03, 0x8e, 0xf5, 0x61, 0xaf, 0x02, 0x2f, 0x93, 0x28, 0xc6, 0x89, 0x4c, 0x38, 0x2a, 0xff,
	0x33, 0x06, 0xb0, 0xf6, 0x2a, 0x4b, 0x44, 0x86, 0xbe, 0x77, 0xf4, 0x06, 0xd8, 0xed, 0xe1, 0xc6,
	0xee, 0x43, 0x50, 0x23, 0x6e, 0xd9, 0xff, 0x94, 0x99, 0xd1, 0xee, 0x7b, 0xac, 0x03, 0x1b, 0x97,
	0x91, 0xd2, 0x66, 0xae, 0xfb, 0x0d, 0xd6, 0x86, 0xf5, 0xb3, 0x84, 0x86, 0xbc, 0xdf, 0x3c, 0x42,
	0xd8, 0x5e, 0x32, 0xcf, 0xd8, 0x03, 0xb8, 0x5b, 0x67, 0xea, 0xce, 0x7b, 0x00, 0x17, 0x52, 0xbb,
	0x0b, 0xee, 0x7b, 0x6c, 0x13, 0xda, 0x26, 0x40, 0x49, 0x34, 0x8c, 0xc2, 0x59, 0x92, 0x94, 0xb8,
	0x79, 0xf4, 0xc2, 0x5d, 0x17, 0x37, 0xd2, 0xd8, 0x1e, 0x30, 0xb7, 0xac, 0x3b, 0xee, 0x42, 0xcb,
	0xf1, 0x17, 0xd2, 0xf7, 0x8c, 0x1b, 0x07, 0xdf, 0x60, 0xe1, 0x37, 0x8e, 0xfe, 0xf4, 0xdc, 0x67,
	0x98, 0xdb, 0xe6, 0x2e, 0x6c, 0x2d, 0xdb, 0x1e, 0x83, 0xde, 0x25, 0x66, 0x5c, 0x64, 0x63, 0x57,
	0x20, 0xdf, 0x63, 0x5b, 0xd0, 0x75, 0x5c, 0x88, 0xd7, 0x02, 0x3f, 0xf8, 0x0d, 0xb6, 0x0d, 0x9b,
	0x8e, 0x2a, 0x6f, 0x91, 0xdf, 0x64, 0x3b, 0xe0, 0xcf, 0xf5, 0xcc, 0x4b, 0x13, 0xd9, 0xd8, 0x5f,
	0x31, 0x81, 0x1c, 0x7b, 0x2e, 0xd3, 0x3c, 0x41, 0x2d, 0x64, 0xe6, 0xaf, 0x56, 0x02, 0x9d, 0xcb,
	0x94, 0x1c, 0xac, 0x99, 0x62, 0x9f, 0x47, 0x59, 0x8c, 0x09, 0x72, 0x7f, 0xfd, 0xe8, 0x09, 0xb4,
	0xe6, 0x9f, 0x6e, 0x26, 0xe0, 0xd2, 0x83, 0xbe, 0x90, 0x2a, 0x8d, 0x12, 0xdf, 0x3b, 0xfa, 0x15,
	0xb6, 0x6e, 0x0d, 0x5a, 0x76, 0x0f, 0xee, 0x54, 0xf1, 0xad, 0x82, 0x5d, 0x48, 0x6d, 0xe5, 0xb6,
	0x60, 0xe6, 0x20, 0x1c, 0x6e, 0x18, 0xf1, 0x59, 0x92, 0x38, 0xd8, 0xac, 0xf8, 0xaf, 0x4d, 0xde,
	0x3b, 0x55, 0xbc, 0xdc, 0xbf, 0x91, 0x57, 0xfd, 0x13, 0x5e, 0xf8, 0x27, 0xd8, 0x3c, 0x7d, 0xe9,
	0x8e, 0xf9, 0x0a, 0xd5, 0xb5, 0xe9, 0xec, 0x4f, 0xa1, 0xf3, 0x23, 0xda, 0x77, 0x64, 0x1e, 0x14,
	0x5b, 0x7c, 0xe0, 0x54, 0xff, 0x6a, 0xf4, 0x97, 0xd2, 0xc5, 0xb3, 0xfd, 0x9f, 0x3f, 0x1f, 0x0b,
	0x3d, 0x99, 0x8e, 0x8e, 0x63, 0x99, 0x9e, 0x14, 0x13, 0x91, 0xa5, 0x62, 0x2c, 0x4f, 0xca, 0xbf,
	0x35, 0xf9, 0x68, 0xb4, 0x46, 0xff, 0x5d, 0xbe, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xab, 0x22,
	0xee, 0x54, 0xf0, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	GetOrderList(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderRes, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetOrderList(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderRes, error) {
	out := new(ListOrderRes)
	err := c.cc.Invoke(ctx, "/orderpb.OrderService/GetOrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	GetOrderList(context.Context, *ListOrderReq) (*ListOrderRes, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) GetOrderList(ctx context.Context, req *ListOrderReq) (*ListOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderList not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_GetOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.OrderService/GetOrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderList(ctx, req.(*ListOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderpb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderList",
			Handler:    _OrderService_GetOrderList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderpb/order.proto",
}
