// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderpb/order.proto

package orderpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basepb "github.com/shinmigo/pb/basepb"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderPaymentType int32

const (
	OrderPaymentType_PaymentTypePlaceholder OrderPaymentType = 0
	OrderPaymentType_Online                 OrderPaymentType = 1
)

var OrderPaymentType_name = map[int32]string{
	0: "PaymentTypePlaceholder",
	1: "Online",
}

var OrderPaymentType_value = map[string]int32{
	"PaymentTypePlaceholder": 0,
	"Online":                 1,
}

func (x OrderPaymentType) String() string {
	return proto.EnumName(OrderPaymentType_name, int32(x))
}

func (OrderPaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{0}
}

type OrderPaymentStatus int32

const (
	OrderPaymentStatus_PaymentStatusPlaceholder OrderPaymentStatus = 0
	OrderPaymentStatus_Unpaid                   OrderPaymentStatus = 1
	OrderPaymentStatus_PartPaid                 OrderPaymentStatus = 2
	OrderPaymentStatus_AllPaid                  OrderPaymentStatus = 3
)

var OrderPaymentStatus_name = map[int32]string{
	0: "PaymentStatusPlaceholder",
	1: "Unpaid",
	2: "PartPaid",
	3: "AllPaid",
}

var OrderPaymentStatus_value = map[string]int32{
	"PaymentStatusPlaceholder": 0,
	"Unpaid":                   1,
	"PartPaid":                 2,
	"AllPaid":                  3,
}

func (x OrderPaymentStatus) String() string {
	return proto.EnumName(OrderPaymentStatus_name, int32(x))
}

func (OrderPaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1}
}

type OrderShippingStatus int32

const (
	OrderShippingStatus_ShippingStatusPlaceholder OrderShippingStatus = 0
	OrderShippingStatus_NotShipped                OrderShippingStatus = 1
	OrderShippingStatus_PartShipped               OrderShippingStatus = 2
	OrderShippingStatus_AllShipped                OrderShippingStatus = 3
)

var OrderShippingStatus_name = map[int32]string{
	0: "ShippingStatusPlaceholder",
	1: "NotShipped",
	2: "PartShipped",
	3: "AllShipped",
}

var OrderShippingStatus_value = map[string]int32{
	"ShippingStatusPlaceholder": 0,
	"NotShipped":                1,
	"PartShipped":               2,
	"AllShipped":                3,
}

func (x OrderShippingStatus) String() string {
	return proto.EnumName(OrderShippingStatus_name, int32(x))
}

func (OrderShippingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{2}
}

type OrderConfirm int32

const (
	OrderConfirm_ConfirmPlaceholder OrderConfirm = 0
	OrderConfirm_ConfirmNo          OrderConfirm = 1
	OrderConfirm_ConfirmYes         OrderConfirm = 2
)

var OrderConfirm_name = map[int32]string{
	0: "ConfirmPlaceholder",
	1: "ConfirmNo",
	2: "ConfirmYes",
}

var OrderConfirm_value = map[string]int32{
	"ConfirmPlaceholder": 0,
	"ConfirmNo":          1,
	"ConfirmYes":         2,
}

func (x OrderConfirm) String() string {
	return proto.EnumName(OrderConfirm_name, int32(x))
}

func (OrderConfirm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{3}
}

type OrderStatus int32

const (
	OrderStatus_StatusPlaceholder OrderStatus = 0
	OrderStatus_PendingPayment    OrderStatus = 1
	OrderStatus_PendingReview     OrderStatus = 2
	OrderStatus_PendingShipment   OrderStatus = 3
	OrderStatus_PendingReceiving  OrderStatus = 4
	OrderStatus_PendingComment    OrderStatus = 5
	OrderStatus_Completed         OrderStatus = 6
	OrderStatus_Canceled          OrderStatus = 7
)

var OrderStatus_name = map[int32]string{
	0: "StatusPlaceholder",
	1: "PendingPayment",
	2: "PendingReview",
	3: "PendingShipment",
	4: "PendingReceiving",
	5: "PendingComment",
	6: "Completed",
	7: "Canceled",
}

var OrderStatus_value = map[string]int32{
	"StatusPlaceholder": 0,
	"PendingPayment":    1,
	"PendingReview":     2,
	"PendingShipment":   3,
	"PendingReceiving":  4,
	"PendingComment":    5,
	"Completed":         6,
	"Canceled":          7,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{4}
}

type OrderType int32

const (
	OrderType_TypePlaceholder OrderType = 0
	OrderType_Normal          OrderType = 1
)

var OrderType_name = map[int32]string{
	0: "TypePlaceholder",
	1: "Normal",
}

var OrderType_value = map[string]int32{
	"TypePlaceholder": 0,
	"Normal":          1,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{5}
}

type OrderRefundStatus int32

const (
	OrderRefundStatus_RefundStatusPlaceholder OrderRefundStatus = 0
	OrderRefundStatus_NotRefund               OrderRefundStatus = 1
	OrderRefundStatus_PartRefund              OrderRefundStatus = 2
	OrderRefundStatus_AllRefund               OrderRefundStatus = 3
)

var OrderRefundStatus_name = map[int32]string{
	0: "RefundStatusPlaceholder",
	1: "NotRefund",
	2: "PartRefund",
	3: "AllRefund",
}

var OrderRefundStatus_value = map[string]int32{
	"RefundStatusPlaceholder": 0,
	"NotRefund":               1,
	"PartRefund":              2,
	"AllRefund":               3,
}

func (x OrderRefundStatus) String() string {
	return proto.EnumName(OrderRefundStatus_name, int32(x))
}

func (OrderRefundStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{6}
}

type OrderReturnStatus int32

const (
	OrderReturnStatus_ReturnStatusPlaceholder OrderReturnStatus = 0
	OrderReturnStatus_NotReturn               OrderReturnStatus = 1
	OrderReturnStatus_PartReturn              OrderReturnStatus = 2
	OrderReturnStatus_AllReturn               OrderReturnStatus = 3
)

var OrderReturnStatus_name = map[int32]string{
	0: "ReturnStatusPlaceholder",
	1: "NotReturn",
	2: "PartReturn",
	3: "AllReturn",
}

var OrderReturnStatus_value = map[string]int32{
	"ReturnStatusPlaceholder": 0,
	"NotReturn":               1,
	"PartReturn":              2,
	"AllReturn":               3,
}

func (x OrderReturnStatus) String() string {
	return proto.EnumName(OrderReturnStatus_name, int32(x))
}

func (OrderReturnStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{7}
}

type ListOrderReq struct {
	Page                 uint64        `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	PageSize             uint64        `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	StoreId              uint64        `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id"`
	MemberId             uint64        `protobuf:"varint,4,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	OrderId              uint64        `protobuf:"varint,5,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	StartCreatedAt       string        `protobuf:"bytes,6,opt,name=start_created_at,json=startCreatedAt,proto3" json:"start_created_at"`
	EndCreatedAt         string        `protobuf:"bytes,7,opt,name=end_created_at,json=endCreatedAt,proto3" json:"end_created_at"`
	OrderStatus          []OrderStatus `protobuf:"varint,8,rep,packed,name=order_status,json=orderStatus,proto3,enum=orderpb.OrderStatus" json:"order_status"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListOrderReq) Reset()         { *m = ListOrderReq{} }
func (m *ListOrderReq) String() string { return proto.CompactTextString(m) }
func (*ListOrderReq) ProtoMessage()    {}
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{0}
}

func (m *ListOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderReq.Unmarshal(m, b)
}
func (m *ListOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderReq.Marshal(b, m, deterministic)
}
func (m *ListOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderReq.Merge(m, src)
}
func (m *ListOrderReq) XXX_Size() int {
	return xxx_messageInfo_ListOrderReq.Size(m)
}
func (m *ListOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderReq proto.InternalMessageInfo

func (m *ListOrderReq) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListOrderReq) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOrderReq) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *ListOrderReq) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *ListOrderReq) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *ListOrderReq) GetStartCreatedAt() string {
	if m != nil {
		return m.StartCreatedAt
	}
	return ""
}

func (m *ListOrderReq) GetEndCreatedAt() string {
	if m != nil {
		return m.EndCreatedAt
	}
	return ""
}

func (m *ListOrderReq) GetOrderStatus() []OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return nil
}

type OrderDetail struct {
	OrderId              uint64                     `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	StoreId              uint64                     `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id"`
	MemberId             uint64                     `protobuf:"varint,3,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	OrderType            OrderType                  `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=orderpb.OrderType" json:"order_type"`
	Subtotal             float64                    `protobuf:"fixed64,5,opt,name=subtotal,proto3" json:"subtotal"`
	GrandTotal           float64                    `protobuf:"fixed64,6,opt,name=grand_total,json=grandTotal,proto3" json:"grand_total"`
	TotalPaid            float64                    `protobuf:"fixed64,7,opt,name=total_paid,json=totalPaid,proto3" json:"total_paid"`
	ShippingAmount       float64                    `protobuf:"fixed64,8,opt,name=shipping_amount,json=shippingAmount,proto3" json:"shipping_amount"`
	DiscountAmount       float64                    `protobuf:"fixed64,9,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount"`
	PaymentType          OrderPaymentType           `protobuf:"varint,10,opt,name=payment_type,json=paymentType,proto3,enum=orderpb.OrderPaymentType" json:"payment_type"`
	PaymentStatus        OrderPaymentStatus         `protobuf:"varint,11,opt,name=payment_status,json=paymentStatus,proto3,enum=orderpb.OrderPaymentStatus" json:"payment_status"`
	PaymentTime          string                     `protobuf:"bytes,12,opt,name=payment_time,json=paymentTime,proto3" json:"payment_time"`
	ShippingStatus       OrderShippingStatus        `protobuf:"varint,13,opt,name=shipping_status,json=shippingStatus,proto3,enum=orderpb.OrderShippingStatus" json:"shipping_status"`
	ShippingTime         string                     `protobuf:"bytes,14,opt,name=shipping_time,json=shippingTime,proto3" json:"shipping_time"`
	Confirm              OrderConfirm               `protobuf:"varint,15,opt,name=confirm,proto3,enum=orderpb.OrderConfirm" json:"confirm"`
	ConfirmTime          string                     `protobuf:"bytes,16,opt,name=confirm_time,json=confirmTime,proto3" json:"confirm_time"`
	OrderStatus          OrderStatus                `protobuf:"varint,17,opt,name=order_status,json=orderStatus,proto3,enum=orderpb.OrderStatus" json:"order_status"`
	RefundStatus         OrderRefundStatus          `protobuf:"varint,18,opt,name=refund_status,json=refundStatus,proto3,enum=orderpb.OrderRefundStatus" json:"refund_status"`
	ReturnStatus         OrderReturnStatus          `protobuf:"varint,19,opt,name=return_status,json=returnStatus,proto3,enum=orderpb.OrderReturnStatus" json:"return_status"`
	UserNote             string                     `protobuf:"bytes,20,opt,name=user_note,json=userNote,proto3" json:"user_note"`
	OrderItems           []*OrderDetail_OrderItems  `protobuf:"bytes,21,rep,name=order_items,json=orderItems,proto3" json:"order_items"`
	OrderAddress         *OrderDetail_OrderAddress  `protobuf:"bytes,22,opt,name=order_address,json=orderAddress,proto3" json:"order_address"`
	OrderShipment        *OrderDetail_OrderShipment `protobuf:"bytes,24,opt,name=order_shipment,json=orderShipment,proto3" json:"order_shipment"`
	CreatedAt            string                     `protobuf:"bytes,25,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	TotalQtyOrdered      uint64                     `protobuf:"varint,26,opt,name=total_qty_ordered,json=totalQtyOrdered,proto3" json:"total_qty_ordered"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *OrderDetail) Reset()         { *m = OrderDetail{} }
func (m *OrderDetail) String() string { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()    {}
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1}
}

func (m *OrderDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail.Unmarshal(m, b)
}
func (m *OrderDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail.Marshal(b, m, deterministic)
}
func (m *OrderDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail.Merge(m, src)
}
func (m *OrderDetail) XXX_Size() int {
	return xxx_messageInfo_OrderDetail.Size(m)
}
func (m *OrderDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail proto.InternalMessageInfo

func (m *OrderDetail) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDetail) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *OrderDetail) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *OrderDetail) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_TypePlaceholder
}

func (m *OrderDetail) GetSubtotal() float64 {
	if m != nil {
		return m.Subtotal
	}
	return 0
}

func (m *OrderDetail) GetGrandTotal() float64 {
	if m != nil {
		return m.GrandTotal
	}
	return 0
}

func (m *OrderDetail) GetTotalPaid() float64 {
	if m != nil {
		return m.TotalPaid
	}
	return 0
}

func (m *OrderDetail) GetShippingAmount() float64 {
	if m != nil {
		return m.ShippingAmount
	}
	return 0
}

func (m *OrderDetail) GetDiscountAmount() float64 {
	if m != nil {
		return m.DiscountAmount
	}
	return 0
}

func (m *OrderDetail) GetPaymentType() OrderPaymentType {
	if m != nil {
		return m.PaymentType
	}
	return OrderPaymentType_PaymentTypePlaceholder
}

func (m *OrderDetail) GetPaymentStatus() OrderPaymentStatus {
	if m != nil {
		return m.PaymentStatus
	}
	return OrderPaymentStatus_PaymentStatusPlaceholder
}

func (m *OrderDetail) GetPaymentTime() string {
	if m != nil {
		return m.PaymentTime
	}
	return ""
}

func (m *OrderDetail) GetShippingStatus() OrderShippingStatus {
	if m != nil {
		return m.ShippingStatus
	}
	return OrderShippingStatus_ShippingStatusPlaceholder
}

func (m *OrderDetail) GetShippingTime() string {
	if m != nil {
		return m.ShippingTime
	}
	return ""
}

func (m *OrderDetail) GetConfirm() OrderConfirm {
	if m != nil {
		return m.Confirm
	}
	return OrderConfirm_ConfirmPlaceholder
}

func (m *OrderDetail) GetConfirmTime() string {
	if m != nil {
		return m.ConfirmTime
	}
	return ""
}

func (m *OrderDetail) GetOrderStatus() OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return OrderStatus_StatusPlaceholder
}

func (m *OrderDetail) GetRefundStatus() OrderRefundStatus {
	if m != nil {
		return m.RefundStatus
	}
	return OrderRefundStatus_RefundStatusPlaceholder
}

func (m *OrderDetail) GetReturnStatus() OrderReturnStatus {
	if m != nil {
		return m.ReturnStatus
	}
	return OrderReturnStatus_ReturnStatusPlaceholder
}

func (m *OrderDetail) GetUserNote() string {
	if m != nil {
		return m.UserNote
	}
	return ""
}

func (m *OrderDetail) GetOrderItems() []*OrderDetail_OrderItems {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

func (m *OrderDetail) GetOrderAddress() *OrderDetail_OrderAddress {
	if m != nil {
		return m.OrderAddress
	}
	return nil
}

func (m *OrderDetail) GetOrderShipment() *OrderDetail_OrderShipment {
	if m != nil {
		return m.OrderShipment
	}
	return nil
}

func (m *OrderDetail) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *OrderDetail) GetTotalQtyOrdered() uint64 {
	if m != nil {
		return m.TotalQtyOrdered
	}
	return 0
}

type OrderDetail_OrderItems struct {
	OrderItemId          uint64   `protobuf:"varint,1,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id"`
	ProductId            uint64   `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	Sku                  string   `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image"`
	Price                float64  `protobuf:"fixed64,6,opt,name=price,proto3" json:"price"`
	OldPrice             float64  `protobuf:"fixed64,7,opt,name=old_price,json=oldPrice,proto3" json:"old_price"`
	TotalPayable         float64  `protobuf:"fixed64,8,opt,name=total_payable,json=totalPayable,proto3" json:"total_payable"`
	TotalDiscountAmount  float64  `protobuf:"fixed64,9,opt,name=total_discount_amount,json=totalDiscountAmount,proto3" json:"total_discount_amount"`
	QtyOrdered           uint64   `protobuf:"varint,10,opt,name=qty_ordered,json=qtyOrdered,proto3" json:"qty_ordered"`
	Weight               float64  `protobuf:"fixed64,11,opt,name=weight,proto3" json:"weight"`
	Volume               float64  `protobuf:"fixed64,12,opt,name=volume,proto3" json:"volume"`
	Spec                 string   `protobuf:"bytes,13,opt,name=spec,proto3" json:"spec"`
	QtyShipped           uint64   `protobuf:"varint,14,opt,name=qty_shipped,json=qtyShipped,proto3" json:"qty_shipped"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail_OrderItems) Reset()         { *m = OrderDetail_OrderItems{} }
func (m *OrderDetail_OrderItems) String() string { return proto.CompactTextString(m) }
func (*OrderDetail_OrderItems) ProtoMessage()    {}
func (*OrderDetail_OrderItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1, 0}
}

func (m *OrderDetail_OrderItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail_OrderItems.Unmarshal(m, b)
}
func (m *OrderDetail_OrderItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail_OrderItems.Marshal(b, m, deterministic)
}
func (m *OrderDetail_OrderItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail_OrderItems.Merge(m, src)
}
func (m *OrderDetail_OrderItems) XXX_Size() int {
	return xxx_messageInfo_OrderDetail_OrderItems.Size(m)
}
func (m *OrderDetail_OrderItems) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail_OrderItems.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail_OrderItems proto.InternalMessageInfo

func (m *OrderDetail_OrderItems) GetOrderItemId() uint64 {
	if m != nil {
		return m.OrderItemId
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetProductId() uint64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderDetail_OrderItems) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *OrderDetail_OrderItems) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *OrderDetail_OrderItems) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetOldPrice() float64 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetTotalPayable() float64 {
	if m != nil {
		return m.TotalPayable
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetTotalDiscountAmount() float64 {
	if m != nil {
		return m.TotalDiscountAmount
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetQtyOrdered() uint64 {
	if m != nil {
		return m.QtyOrdered
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *OrderDetail_OrderItems) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *OrderDetail_OrderItems) GetQtyShipped() uint64 {
	if m != nil {
		return m.QtyShipped
	}
	return 0
}

type OrderDetail_OrderAddress struct {
	OrderAddressId       uint64   `protobuf:"varint,1,opt,name=order_address_id,json=orderAddressId,proto3" json:"order_address_id"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver"`
	Telephone            string   `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone"`
	Province             string   `protobuf:"bytes,4,opt,name=province,proto3" json:"province"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city"`
	Region               string   `protobuf:"bytes,6,opt,name=region,proto3" json:"region"`
	Street               string   `protobuf:"bytes,7,opt,name=street,proto3" json:"street"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail_OrderAddress) Reset()         { *m = OrderDetail_OrderAddress{} }
func (m *OrderDetail_OrderAddress) String() string { return proto.CompactTextString(m) }
func (*OrderDetail_OrderAddress) ProtoMessage()    {}
func (*OrderDetail_OrderAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1, 1}
}

func (m *OrderDetail_OrderAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail_OrderAddress.Unmarshal(m, b)
}
func (m *OrderDetail_OrderAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail_OrderAddress.Marshal(b, m, deterministic)
}
func (m *OrderDetail_OrderAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail_OrderAddress.Merge(m, src)
}
func (m *OrderDetail_OrderAddress) XXX_Size() int {
	return xxx_messageInfo_OrderDetail_OrderAddress.Size(m)
}
func (m *OrderDetail_OrderAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail_OrderAddress.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail_OrderAddress proto.InternalMessageInfo

func (m *OrderDetail_OrderAddress) GetOrderAddressId() uint64 {
	if m != nil {
		return m.OrderAddressId
	}
	return 0
}

func (m *OrderDetail_OrderAddress) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *OrderDetail_OrderAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

type OrderDetail_OrderShipment struct {
	CarrierName          string   `protobuf:"bytes,1,opt,name=carrier_name,json=carrierName,proto3" json:"carrier_name"`
	TrackingNumber       string   `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetail_OrderShipment) Reset()         { *m = OrderDetail_OrderShipment{} }
func (m *OrderDetail_OrderShipment) String() string { return proto.CompactTextString(m) }
func (*OrderDetail_OrderShipment) ProtoMessage()    {}
func (*OrderDetail_OrderShipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1, 2}
}

func (m *OrderDetail_OrderShipment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail_OrderShipment.Unmarshal(m, b)
}
func (m *OrderDetail_OrderShipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail_OrderShipment.Marshal(b, m, deterministic)
}
func (m *OrderDetail_OrderShipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail_OrderShipment.Merge(m, src)
}
func (m *OrderDetail_OrderShipment) XXX_Size() int {
	return xxx_messageInfo_OrderDetail_OrderShipment.Size(m)
}
func (m *OrderDetail_OrderShipment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail_OrderShipment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail_OrderShipment proto.InternalMessageInfo

func (m *OrderDetail_OrderShipment) GetCarrierName() string {
	if m != nil {
		return m.CarrierName
	}
	return ""
}

func (m *OrderDetail_OrderShipment) GetTrackingNumber() string {
	if m != nil {
		return m.TrackingNumber
	}
	return ""
}

type ListOrderRes struct {
	Total                uint64         `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Orders               []*OrderDetail `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListOrderRes) Reset()         { *m = ListOrderRes{} }
func (m *ListOrderRes) String() string { return proto.CompactTextString(m) }
func (*ListOrderRes) ProtoMessage()    {}
func (*ListOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{2}
}

func (m *ListOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderRes.Unmarshal(m, b)
}
func (m *ListOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderRes.Marshal(b, m, deterministic)
}
func (m *ListOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderRes.Merge(m, src)
}
func (m *ListOrderRes) XXX_Size() int {
	return xxx_messageInfo_ListOrderRes.Size(m)
}
func (m *ListOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderRes proto.InternalMessageInfo

func (m *ListOrderRes) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListOrderRes) GetOrders() []*OrderDetail {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetOrderStatusReq struct {
	StoreId              uint64   `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id"`
	MemberId             uint64   `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderStatusReq) Reset()         { *m = GetOrderStatusReq{} }
func (m *GetOrderStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetOrderStatusReq) ProtoMessage()    {}
func (*GetOrderStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{3}
}

func (m *GetOrderStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderStatusReq.Unmarshal(m, b)
}
func (m *GetOrderStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderStatusReq.Marshal(b, m, deterministic)
}
func (m *GetOrderStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderStatusReq.Merge(m, src)
}
func (m *GetOrderStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetOrderStatusReq.Size(m)
}
func (m *GetOrderStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderStatusReq proto.InternalMessageInfo

func (m *GetOrderStatusReq) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *GetOrderStatusReq) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

type ListOrderStatusRes struct {
	OrderStatistics      []*ListOrderStatusRes_OrderStatistics `protobuf:"bytes,1,rep,name=order_statistics,json=orderStatistics,proto3" json:"order_statistics"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ListOrderStatusRes) Reset()         { *m = ListOrderStatusRes{} }
func (m *ListOrderStatusRes) String() string { return proto.CompactTextString(m) }
func (*ListOrderStatusRes) ProtoMessage()    {}
func (*ListOrderStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{4}
}

func (m *ListOrderStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderStatusRes.Unmarshal(m, b)
}
func (m *ListOrderStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderStatusRes.Marshal(b, m, deterministic)
}
func (m *ListOrderStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderStatusRes.Merge(m, src)
}
func (m *ListOrderStatusRes) XXX_Size() int {
	return xxx_messageInfo_ListOrderStatusRes.Size(m)
}
func (m *ListOrderStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderStatusRes proto.InternalMessageInfo

func (m *ListOrderStatusRes) GetOrderStatistics() []*ListOrderStatusRes_OrderStatistics {
	if m != nil {
		return m.OrderStatistics
	}
	return nil
}

type ListOrderStatusRes_OrderStatistics struct {
	OrderStatus          uint64   `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3" json:"order_status"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderStatusRes_OrderStatistics) Reset()         { *m = ListOrderStatusRes_OrderStatistics{} }
func (m *ListOrderStatusRes_OrderStatistics) String() string { return proto.CompactTextString(m) }
func (*ListOrderStatusRes_OrderStatistics) ProtoMessage()    {}
func (*ListOrderStatusRes_OrderStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{4, 0}
}

func (m *ListOrderStatusRes_OrderStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderStatusRes_OrderStatistics.Unmarshal(m, b)
}
func (m *ListOrderStatusRes_OrderStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderStatusRes_OrderStatistics.Marshal(b, m, deterministic)
}
func (m *ListOrderStatusRes_OrderStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderStatusRes_OrderStatistics.Merge(m, src)
}
func (m *ListOrderStatusRes_OrderStatistics) XXX_Size() int {
	return xxx_messageInfo_ListOrderStatusRes_OrderStatistics.Size(m)
}
func (m *ListOrderStatusRes_OrderStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderStatusRes_OrderStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderStatusRes_OrderStatistics proto.InternalMessageInfo

func (m *ListOrderStatusRes_OrderStatistics) GetOrderStatus() uint64 {
	if m != nil {
		return m.OrderStatus
	}
	return 0
}

func (m *ListOrderStatusRes_OrderStatistics) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Order struct {
	StoreId              uint64            `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id"`
	MemberId             uint64            `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	AddressId            uint64            `protobuf:"varint,3,opt,name=address_id,json=addressId,proto3" json:"address_id"`
	UserNode             string            `protobuf:"bytes,5,opt,name=user_node,json=userNode,proto3" json:"user_node"`
	Products             []*Order_Products `protobuf:"bytes,6,rep,name=products,proto3" json:"products"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{5}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *Order) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *Order) GetAddressId() uint64 {
	if m != nil {
		return m.AddressId
	}
	return 0
}

func (m *Order) GetUserNode() string {
	if m != nil {
		return m.UserNode
	}
	return ""
}

func (m *Order) GetProducts() []*Order_Products {
	if m != nil {
		return m.Products
	}
	return nil
}

type Order_Products struct {
	ProductId            uint64   `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id"`
	ProductSpecId        uint64   `protobuf:"varint,2,opt,name=product_spec_id,json=productSpecId,proto3" json:"product_spec_id"`
	Qty                  uint64   `protobuf:"varint,3,opt,name=qty,proto3" json:"qty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_Products) Reset()         { *m = Order_Products{} }
func (m *Order_Products) String() string { return proto.CompactTextString(m) }
func (*Order_Products) ProtoMessage()    {}
func (*Order_Products) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{5, 0}
}

func (m *Order_Products) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_Products.Unmarshal(m, b)
}
func (m *Order_Products) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_Products.Marshal(b, m, deterministic)
}
func (m *Order_Products) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_Products.Merge(m, src)
}
func (m *Order_Products) XXX_Size() int {
	return xxx_messageInfo_Order_Products.Size(m)
}
func (m *Order_Products) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_Products.DiscardUnknown(m)
}

var xxx_messageInfo_Order_Products proto.InternalMessageInfo

func (m *Order_Products) GetProductId() uint64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Order_Products) GetProductSpecId() uint64 {
	if m != nil {
		return m.ProductSpecId
	}
	return 0
}

func (m *Order_Products) GetQty() uint64 {
	if m != nil {
		return m.Qty
	}
	return 0
}

type PayOrderReq struct {
	OrderId              []uint64 `protobuf:"varint,1,rep,packed,name=order_id,json=orderId,proto3" json:"order_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrderReq) Reset()         { *m = PayOrderReq{} }
func (m *PayOrderReq) String() string { return proto.CompactTextString(m) }
func (*PayOrderReq) ProtoMessage()    {}
func (*PayOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{6}
}

func (m *PayOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderReq.Unmarshal(m, b)
}
func (m *PayOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderReq.Marshal(b, m, deterministic)
}
func (m *PayOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderReq.Merge(m, src)
}
func (m *PayOrderReq) XXX_Size() int {
	return xxx_messageInfo_PayOrderReq.Size(m)
}
func (m *PayOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderReq proto.InternalMessageInfo

func (m *PayOrderReq) GetOrderId() []uint64 {
	if m != nil {
		return m.OrderId
	}
	return nil
}

type CancelOrderReq struct {
	MemberId             uint64   `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	StoreId              uint64   `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id"`
	OrderId              []uint64 `protobuf:"varint,3,rep,packed,name=order_id,json=orderId,proto3" json:"order_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderReq) Reset()         { *m = CancelOrderReq{} }
func (m *CancelOrderReq) String() string { return proto.CompactTextString(m) }
func (*CancelOrderReq) ProtoMessage()    {}
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{7}
}

func (m *CancelOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderReq.Unmarshal(m, b)
}
func (m *CancelOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderReq.Marshal(b, m, deterministic)
}
func (m *CancelOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderReq.Merge(m, src)
}
func (m *CancelOrderReq) XXX_Size() int {
	return xxx_messageInfo_CancelOrderReq.Size(m)
}
func (m *CancelOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderReq proto.InternalMessageInfo

func (m *CancelOrderReq) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *CancelOrderReq) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *CancelOrderReq) GetOrderId() []uint64 {
	if m != nil {
		return m.OrderId
	}
	return nil
}

type DeleteOrderReq struct {
	MemberId             uint64   `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	StoreId              uint64   `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id"`
	OrderId              []uint64 `protobuf:"varint,3,rep,packed,name=order_id,json=orderId,proto3" json:"order_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderReq) Reset()         { *m = DeleteOrderReq{} }
func (m *DeleteOrderReq) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderReq) ProtoMessage()    {}
func (*DeleteOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{8}
}

func (m *DeleteOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderReq.Unmarshal(m, b)
}
func (m *DeleteOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderReq.Marshal(b, m, deterministic)
}
func (m *DeleteOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderReq.Merge(m, src)
}
func (m *DeleteOrderReq) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderReq.Size(m)
}
func (m *DeleteOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderReq proto.InternalMessageInfo

func (m *DeleteOrderReq) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *DeleteOrderReq) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *DeleteOrderReq) GetOrderId() []uint64 {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func init() {
	proto.RegisterEnum("orderpb.OrderPaymentType", OrderPaymentType_name, OrderPaymentType_value)
	proto.RegisterEnum("orderpb.OrderPaymentStatus", OrderPaymentStatus_name, OrderPaymentStatus_value)
	proto.RegisterEnum("orderpb.OrderShippingStatus", OrderShippingStatus_name, OrderShippingStatus_value)
	proto.RegisterEnum("orderpb.OrderConfirm", OrderConfirm_name, OrderConfirm_value)
	proto.RegisterEnum("orderpb.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterEnum("orderpb.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("orderpb.OrderRefundStatus", OrderRefundStatus_name, OrderRefundStatus_value)
	proto.RegisterEnum("orderpb.OrderReturnStatus", OrderReturnStatus_name, OrderReturnStatus_value)
	proto.RegisterType((*ListOrderReq)(nil), "orderpb.ListOrderReq")
	proto.RegisterType((*OrderDetail)(nil), "orderpb.OrderDetail")
	proto.RegisterType((*OrderDetail_OrderItems)(nil), "orderpb.OrderDetail.OrderItems")
	proto.RegisterType((*OrderDetail_OrderAddress)(nil), "orderpb.OrderDetail.OrderAddress")
	proto.RegisterType((*OrderDetail_OrderShipment)(nil), "orderpb.OrderDetail.OrderShipment")
	proto.RegisterType((*ListOrderRes)(nil), "orderpb.ListOrderRes")
	proto.RegisterType((*GetOrderStatusReq)(nil), "orderpb.GetOrderStatusReq")
	proto.RegisterType((*ListOrderStatusRes)(nil), "orderpb.ListOrderStatusRes")
	proto.RegisterType((*ListOrderStatusRes_OrderStatistics)(nil), "orderpb.ListOrderStatusRes.OrderStatistics")
	proto.RegisterType((*Order)(nil), "orderpb.Order")
	proto.RegisterType((*Order_Products)(nil), "orderpb.Order.Products")
	proto.RegisterType((*PayOrderReq)(nil), "orderpb.PayOrderReq")
	proto.RegisterType((*CancelOrderReq)(nil), "orderpb.CancelOrderReq")
	proto.RegisterType((*DeleteOrderReq)(nil), "orderpb.DeleteOrderReq")
}

func init() { proto.RegisterFile("orderpb/order.proto", fileDescriptor_87a9833f63666870) }

var fileDescriptor_87a9833f63666870 = []byte{
	// 1629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x6e, 0xdb, 0xc6,
	0x12, 0x3e, 0x94, 0x6c, 0x59, 0x1a, 0x49, 0x14, 0xbd, 0xfe, 0x09, 0x2d, 0x27, 0x27, 0x8e, 0x72,
	0x70, 0x62, 0xe8, 0x04, 0xf6, 0xa9, 0x03, 0xb4, 0x40, 0x11, 0xa0, 0x55, 0x9c, 0xb4, 0x50, 0x5b,
	0x38, 0x2a, 0x9d, 0x16, 0x48, 0x0b, 0x54, 0xa0, 0xb8, 0x1b, 0x79, 0x11, 0x8a, 0xa4, 0xc9, 0x95,
	0x03, 0xe5, 0x3d, 0x7a, 0x55, 0xf4, 0xba, 0xaf, 0xd0, 0xe7, 0xe8, 0x3b, 0xf4, 0xbe, 0x8f, 0x50,
	0xec, 0xec, 0xf2, 0x4f, 0x52, 0x52, 0xa0, 0x40, 0xaf, 0xb4, 0xf3, 0xcd, 0xcf, 0xee, 0xce, 0xce,
	0x7e, 0x3b, 0x14, 0xec, 0x84, 0x31, 0x65, 0x71, 0x34, 0x39, 0xc5, 0xdf, 0x93, 0x28, 0x0e, 0x45,
	0x48, 0xb6, 0x34, 0xd8, 0xdd, 0x99, 0xb8, 0x09, 0x8b, 0x26, 0xa7, 0xea, 0x47, 0x69, 0x7b, 0x3f,
	0x55, 0xa0, 0xf5, 0x15, 0x4f, 0xc4, 0x73, 0x69, 0xe4, 0xb0, 0x6b, 0x42, 0x60, 0x23, 0x72, 0xa7,
	0xcc, 0x36, 0x8e, 0x8c, 0xe3, 0x0d, 0x07, 0xc7, 0xe4, 0x10, 0x1a, 0xf2, 0x77, 0x9c, 0xf0, 0xb7,
	0xcc, 0xae, 0xa0, 0xa2, 0x2e, 0x81, 0x4b, 0xfe, 0x96, 0x91, 0x03, 0xa8, 0x27, 0x22, 0x8c, 0xd9,
	0x98, 0x53, 0xbb, 0x8a, 0xba, 0x2d, 0x94, 0x87, 0x54, 0xfa, 0xcd, 0xd8, 0x6c, 0xc2, 0x62, 0xa9,
	0xdb, 0x50, 0x7e, 0x0a, 0x18, 0x52, 0xe9, 0x87, 0x2b, 0x93, 0xba, 0x4d, 0xe5, 0x87, 0xf2, 0x90,
	0x92, 0x63, 0xb0, 0x12, 0xe1, 0xc6, 0x62, 0xec, 0xc5, 0xcc, 0x15, 0x8c, 0x8e, 0x5d, 0x61, 0xd7,
	0x8e, 0x8c, 0xe3, 0x86, 0x63, 0x22, 0x7e, 0xae, 0xe0, 0x81, 0x20, 0xff, 0x01, 0x93, 0x05, 0xb4,
	0x68, 0xb7, 0x85, 0x76, 0x2d, 0x16, 0xd0, 0xdc, 0xea, 0x23, 0x68, 0xa9, 0xa9, 0x12, 0xe1, 0x8a,
	0x79, 0x62, 0xd7, 0x8f, 0xaa, 0xc7, 0xe6, 0xd9, 0xee, 0x89, 0xce, 0xcc, 0x09, 0x6e, 0xfe, 0x12,
	0x75, 0x4e, 0x33, 0xcc, 0x85, 0xde, 0x1f, 0x26, 0x34, 0x51, 0xf9, 0x94, 0x09, 0x97, 0xfb, 0xa5,
	0x35, 0x1b, 0xe5, 0x35, 0x17, 0xd3, 0x50, 0x79, 0x4f, 0x1a, 0xaa, 0x4b, 0x69, 0xf8, 0x00, 0x40,
	0x85, 0x14, 0x8b, 0x88, 0x61, 0x92, 0xcc, 0x33, 0x52, 0x5e, 0xd9, 0x8b, 0x45, 0xc4, 0x9c, 0x46,
	0x98, 0x0e, 0x49, 0x17, 0xea, 0xc9, 0x7c, 0x22, 0x42, 0xe1, 0xfa, 0x98, 0x39, 0xc3, 0xc9, 0x64,
	0x72, 0x17, 0x9a, 0xd3, 0xd8, 0x0d, 0xe8, 0x58, 0xa9, 0x6b, 0xa8, 0x06, 0x84, 0x5e, 0xa0, 0xc1,
	0x1d, 0x00, 0x54, 0x8d, 0x23, 0x97, 0x53, 0xcc, 0x96, 0xe1, 0x34, 0x10, 0x19, 0xb9, 0x9c, 0x92,
	0x07, 0xd0, 0x49, 0xae, 0x78, 0x14, 0xf1, 0x60, 0x3a, 0x76, 0x67, 0xe1, 0x3c, 0x10, 0x76, 0x1d,
	0x6d, 0xcc, 0x14, 0x1e, 0x20, 0x2a, 0x0d, 0x29, 0x4f, 0x3c, 0x39, 0x4e, 0x0d, 0x1b, 0xca, 0x30,
	0x85, 0xb5, 0xe1, 0x63, 0x68, 0x45, 0xee, 0x62, 0xc6, 0x02, 0xa1, 0xb6, 0x08, 0xb8, 0xc5, 0x83,
	0xf2, 0x16, 0x47, 0xca, 0x02, 0x77, 0xda, 0x8c, 0x72, 0x81, 0x3c, 0x01, 0x33, 0xf5, 0xd6, 0x87,
	0xd7, 0x44, 0xff, 0xc3, 0xb5, 0xfe, 0xfa, 0x0c, 0xdb, 0x51, 0x51, 0x24, 0xf7, 0x0a, 0x2b, 0xe0,
	0x33, 0x66, 0xb7, 0xb0, 0x44, 0xb2, 0x69, 0xf8, 0x8c, 0x91, 0x67, 0x85, 0x6d, 0xeb, 0x79, 0xda,
	0x38, 0xcf, 0xed, 0xa5, 0x22, 0xd1, 0x46, 0x7a, 0xa2, 0x2c, 0x29, 0x7a, 0xa6, 0xfb, 0xd0, 0xce,
	0xc2, 0xe0, 0x54, 0xa6, 0xaa, 0xc6, 0x14, 0xc4, 0xb9, 0x4e, 0x61, 0xcb, 0x0b, 0x83, 0x57, 0x3c,
	0x9e, 0xd9, 0x1d, 0x9c, 0x63, 0xaf, 0x3c, 0xc7, 0xb9, 0x52, 0x3a, 0xa9, 0x95, 0x5c, 0xbf, 0x1e,
	0xaa, 0xa0, 0x96, 0x5a, 0xbf, 0xc6, 0x30, 0xe6, 0x72, 0x85, 0x6f, 0x63, 0xe0, 0xbf, 0xae, 0x70,
	0xf2, 0x09, 0xb4, 0x63, 0xf6, 0x6a, 0x1e, 0xd0, 0xd4, 0x93, 0xa0, 0x67, 0xb7, 0xec, 0xe9, 0xa0,
	0x89, 0xf6, 0x6f, 0xc5, 0x05, 0x49, 0x05, 0x10, 0xf3, 0x38, 0x48, 0x03, 0xec, 0xac, 0x0f, 0x20,
	0x4d, 0xf2, 0x00, 0xb9, 0x24, 0x6f, 0xc7, 0x3c, 0x61, 0xf1, 0x38, 0x08, 0x05, 0xb3, 0x77, 0x71,
	0x6b, 0x75, 0x09, 0x5c, 0x84, 0x82, 0x91, 0x4f, 0xa1, 0xa9, 0x2f, 0x9c, 0x60, 0xb3, 0xc4, 0xde,
	0x3b, 0xaa, 0x1e, 0x37, 0xcf, 0xee, 0x96, 0x63, 0xab, 0xbb, 0xa9, 0xc6, 0x43, 0x69, 0xe6, 0xa8,
	0x1b, 0x85, 0x63, 0xf2, 0x19, 0xb4, 0x55, 0x04, 0x97, 0xd2, 0x98, 0x25, 0x89, 0xbd, 0x7f, 0x64,
	0x1c, 0x37, 0xcf, 0xee, 0xbd, 0x3b, 0xc6, 0x40, 0x19, 0x3a, 0x2a, 0xa3, 0x5a, 0x22, 0x43, 0x30,
	0x75, 0x86, 0xaf, 0x78, 0x24, 0xeb, 0xc6, 0xb6, 0x31, 0x50, 0xef, 0xdd, 0x81, 0x2e, 0xb5, 0xa5,
	0xa3, 0x56, 0x90, 0x8a, 0xf2, 0x0a, 0x16, 0x08, 0xeb, 0x00, 0xb7, 0xdc, 0xf0, 0x32, 0xb6, 0xea,
	0xc3, 0xb6, 0xba, 0xa1, 0xd7, 0x62, 0x31, 0x46, 0x4f, 0x46, 0xed, 0x2e, 0xd2, 0x46, 0x07, 0x15,
	0x5f, 0x8b, 0xc5, 0x73, 0x05, 0x77, 0x7f, 0xae, 0x02, 0xe4, 0x1b, 0x27, 0xbd, 0x74, 0xb3, 0x32,
	0x5d, 0x39, 0x49, 0x35, 0xb3, 0x7c, 0x0c, 0xa9, 0x9c, 0x3d, 0x8a, 0x43, 0x3a, 0xf7, 0x44, 0x4e,
	0x55, 0x0d, 0x8d, 0x0c, 0xa9, 0xe4, 0xff, 0xc0, 0x9d, 0x31, 0xe4, 0xa9, 0x86, 0x83, 0x63, 0x62,
	0x41, 0x35, 0x79, 0x3d, 0x47, 0x72, 0x6a, 0x38, 0x72, 0x48, 0x76, 0x61, 0x93, 0xcf, 0xe4, 0x33,
	0xb1, 0x89, 0x98, 0x12, 0x24, 0x1a, 0xc5, 0xdc, 0x63, 0x9a, 0x76, 0x94, 0x20, 0x0f, 0x38, 0xf4,
	0xe9, 0x58, 0x69, 0x14, 0xe1, 0xd4, 0x43, 0x9f, 0x8e, 0x50, 0x79, 0x1f, 0xda, 0x29, 0x1d, 0x2d,
	0xdc, 0x89, 0xcf, 0x34, 0xdb, 0xb4, 0x34, 0x23, 0x21, 0x46, 0xce, 0x60, 0x4f, 0x19, 0xad, 0x67,
	0x9c, 0x1d, 0x54, 0x3e, 0x2d, 0xd3, 0xce, 0x5d, 0x68, 0x16, 0xf3, 0x07, 0xb8, 0x4f, 0xb8, 0xce,
	0x52, 0x47, 0xf6, 0xa1, 0xf6, 0x86, 0xf1, 0xe9, 0x95, 0x40, 0x46, 0x31, 0x1c, 0x2d, 0x49, 0xfc,
	0x26, 0xf4, 0xe7, 0x9a, 0x27, 0x0c, 0x47, 0x4b, 0x32, 0x31, 0x49, 0xc4, 0x3c, 0xe4, 0x85, 0x86,
	0x83, 0xe3, 0x74, 0x12, 0xbc, 0xde, 0x8c, 0xe2, 0x6d, 0x57, 0x93, 0x5c, 0x2a, 0xa4, 0xfb, 0x9b,
	0x01, 0xad, 0x62, 0x51, 0xc9, 0xa7, 0xad, 0x54, 0x8e, 0xf9, 0x21, 0x99, 0xc5, 0x72, 0x1b, 0x52,
	0xc9, 0xf2, 0x31, 0xf3, 0x18, 0xbf, 0x61, 0x31, 0x9e, 0x52, 0xc3, 0xc9, 0x64, 0x72, 0x1b, 0x1a,
	0x82, 0xf9, 0x2c, 0xba, 0x0a, 0x83, 0xf4, 0xa4, 0x72, 0x40, 0x7a, 0x46, 0x71, 0x78, 0xc3, 0x03,
	0x8f, 0xe9, 0x33, 0xcb, 0x64, 0xb9, 0x0b, 0x8f, 0x8b, 0x85, 0x3e, 0x37, 0x1c, 0xcb, 0x1d, 0xc7,
	0x6c, 0xca, 0xc3, 0x40, 0x3f, 0xb2, 0x5a, 0x92, 0x78, 0x22, 0x62, 0xc6, 0xd2, 0x47, 0x55, 0x4b,
	0xdd, 0xef, 0xa1, 0x5d, 0xaa, 0x6f, 0x24, 0x28, 0x37, 0x8e, 0xb9, 0xbc, 0xc5, 0xb2, 0x76, 0x0c,
	0x4d, 0x50, 0x0a, 0xbb, 0x90, 0x25, 0xf4, 0x00, 0x3a, 0x22, 0x76, 0xbd, 0xd7, 0x92, 0x19, 0x83,
	0xb9, 0x7c, 0xfb, 0xf4, 0xa6, 0xcc, 0x14, 0xbe, 0x40, 0xb4, 0xe7, 0x94, 0xfa, 0x91, 0x44, 0xd6,
	0x94, 0x7a, 0xca, 0x54, 0x96, 0x94, 0x40, 0x1e, 0x42, 0x0d, 0xd3, 0x95, 0xd8, 0x15, 0xa4, 0x84,
	0xdd, 0x75, 0xb7, 0xd0, 0xd1, 0x36, 0xbd, 0x2f, 0x61, 0xfb, 0x73, 0x26, 0x8a, 0x1c, 0xc8, 0xae,
	0x4b, 0x0f, 0xb6, 0xf1, 0x9e, 0x07, 0xbb, 0x52, 0x7e, 0xb0, 0x7b, 0xbf, 0x1a, 0x40, 0xb2, 0x15,
	0xa6, 0xe1, 0x12, 0xf2, 0x6d, 0x7a, 0xb0, 0x92, 0x06, 0x79, 0x22, 0xb8, 0x97, 0xd8, 0x06, 0xae,
	0xed, 0x7f, 0xd9, 0xda, 0x56, 0xdd, 0x72, 0x62, 0x56, 0x2e, 0x4e, 0x27, 0x2c, 0x03, 0xdd, 0x2f,
	0xa0, 0xb3, 0x64, 0x23, 0xd3, 0x5d, 0x22, 0xfb, 0xe2, 0x25, 0xd7, 0xa4, 0xba, 0x0b, 0x9b, 0x78,
	0x19, 0xf4, 0xea, 0x95, 0xd0, 0xfb, 0xb1, 0x02, 0x9b, 0x18, 0xec, 0xef, 0x6e, 0x5e, 0x92, 0x47,
	0xa1, 0x70, 0x55, 0x2f, 0xd3, 0x70, 0xb3, 0x9a, 0xcd, 0xb9, 0x9c, 0xa6, 0xd4, 0xa0, 0xb9, 0x9c,
	0x32, 0xf2, 0x08, 0xcb, 0x52, 0xd2, 0x4c, 0x62, 0xd7, 0x30, 0x33, 0xb7, 0xca, 0xa7, 0x76, 0x32,
	0xd2, 0x6a, 0x27, 0x33, 0xec, 0x7a, 0x50, 0x4f, 0xd1, 0x25, 0xe6, 0x32, 0x96, 0x99, 0xeb, 0xbf,
	0xd0, 0x49, 0xd5, 0xf2, 0x72, 0xe6, 0xcb, 0x6f, 0x6b, 0xf8, 0x32, 0x62, 0xde, 0x90, 0x4a, 0x36,
	0xbb, 0x16, 0x0b, 0xbd, 0x78, 0x39, 0xec, 0x1d, 0x43, 0x73, 0xe4, 0x2e, 0xb2, 0x16, 0xb8, 0xdc,
	0xe5, 0x55, 0x0b, 0x5d, 0x5e, 0xcf, 0x03, 0xf3, 0xdc, 0x0d, 0x3c, 0xe6, 0x67, 0xc6, 0xa5, 0x74,
	0x19, 0xab, 0x3d, 0xee, 0xbb, 0x9a, 0xc2, 0xe2, 0x24, 0xd5, 0x95, 0x49, 0x9e, 0x32, 0x9f, 0x09,
	0xf6, 0x0f, 0x4e, 0xd2, 0xff, 0x18, 0xac, 0xe5, 0xce, 0x8b, 0x74, 0x61, 0xbf, 0x20, 0x8e, 0x7c,
	0xd7, 0x63, 0x57, 0xa1, 0x4f, 0x59, 0x6c, 0xfd, 0x8b, 0x00, 0xd4, 0x9e, 0x07, 0x3e, 0x0f, 0x98,
	0x65, 0xf4, 0x5f, 0x02, 0x59, 0xed, 0xba, 0xc8, 0x6d, 0xb0, 0x4b, 0xc0, 0x8a, 0xff, 0x37, 0x81,
	0xec, 0x39, 0x2d, 0x83, 0xb4, 0xa0, 0x3e, 0x72, 0x63, 0x21, 0x1b, 0x4e, 0xab, 0x42, 0x9a, 0xb0,
	0x35, 0xf0, 0xb1, 0xfb, 0xb4, 0xaa, 0x7d, 0x06, 0x3b, 0x6b, 0x1a, 0x2d, 0x72, 0x07, 0x0e, 0xca,
	0x48, 0x39, 0xb8, 0x09, 0x70, 0x11, 0x0a, 0x4d, 0xba, 0x96, 0x41, 0x3a, 0xf2, 0x40, 0xe3, 0x0c,
	0xa8, 0x48, 0x83, 0x81, 0xef, 0xa7, 0x72, 0xb5, 0xff, 0x4c, 0xd3, 0xb2, 0xee, 0xb5, 0xc8, 0x3e,
	0x10, 0x3d, 0x2c, 0x07, 0x6e, 0x43, 0x43, 0xe3, 0x17, 0xa1, 0x65, 0xc8, 0x30, 0x5a, 0x7c, 0xc9,
	0x12, 0xab, 0xd2, 0xff, 0xc5, 0xd0, 0xdf, 0x07, 0x7a, 0x99, 0x7b, 0xb0, 0xbd, 0x6e, 0x79, 0x04,
	0xcc, 0x11, 0x0b, 0x28, 0x0f, 0xa6, 0x3a, 0x41, 0x96, 0x41, 0xb6, 0xa1, 0xad, 0x31, 0x87, 0xdd,
	0x70, 0xf6, 0xc6, 0xaa, 0x90, 0x1d, 0xe8, 0x68, 0x28, 0x65, 0x56, 0xab, 0x4a, 0x76, 0xc1, 0xca,
	0xec, 0x24, 0xfb, 0xf3, 0x60, 0x6a, 0x6d, 0x14, 0x22, 0x9e, 0x87, 0x33, 0xb4, 0xdc, 0x54, 0x6b,
	0x9d, 0x45, 0xb2, 0x70, 0xa8, 0x55, 0x93, 0x49, 0x56, 0xa5, 0xca, 0xa8, 0xb5, 0xd5, 0x7f, 0x08,
	0x8d, 0xec, 0x5b, 0x42, 0x4e, 0xb4, 0xf6, 0x80, 0x2f, 0xc2, 0x78, 0xe6, 0xfa, 0x96, 0xd1, 0xff,
	0x01, 0xb6, 0x57, 0xfa, 0x3e, 0x72, 0x08, 0xb7, 0x8a, 0xf2, 0x4a, 0xa2, 0x2e, 0x42, 0xa1, 0xf4,
	0x2a, 0x51, 0xf2, 0x00, 0xb4, 0x5c, 0x91, 0xea, 0x81, 0xef, 0x6b, 0xb1, 0x5a, 0x88, 0x5f, 0x6a,
	0x04, 0x6f, 0x15, 0xe5, 0xf5, 0xf1, 0xa5, 0xbe, 0x18, 0x1f, 0xe5, 0x3c, 0x3e, 0x8a, 0xd5, 0xb3,
	0xdf, 0x2b, 0xfa, 0x7c, 0x2f, 0x59, 0x7c, 0x23, 0xdb, 0x8c, 0xc7, 0xd0, 0x4a, 0x5f, 0x00, 0x49,
	0xc2, 0x64, 0x6f, 0x95, 0x93, 0x1d, 0x76, 0xdd, 0x5d, 0x0b, 0x63, 0xef, 0x57, 0x7e, 0x3f, 0x48,
	0xde, 0xde, 0xae, 0x3c, 0x2c, 0xdd, 0xc3, 0xf7, 0xf0, 0x3d, 0xe9, 0x43, 0x7d, 0x40, 0xa9, 0x22,
	0x61, 0xb3, 0x4c, 0x7f, 0x5d, 0xf3, 0x44, 0x7f, 0x9a, 0x0f, 0x82, 0x85, 0xb4, 0xfd, 0xbf, 0xbc,
	0x26, 0x8a, 0x96, 0x48, 0xfe, 0xc0, 0x15, 0x98, 0x6a, 0xc5, 0xe3, 0x43, 0x68, 0x16, 0xe8, 0x89,
	0xe4, 0xfc, 0x5a, 0x26, 0xad, 0x75, 0x7e, 0x05, 0xc6, 0x29, 0xf8, 0x95, 0x79, 0x68, 0xd9, 0xef,
	0xc9, 0xd1, 0x77, 0xff, 0x9e, 0x72, 0x71, 0x35, 0x9f, 0x9c, 0x78, 0xe1, 0xec, 0x34, 0xb9, 0xe2,
	0xc1, 0x8c, 0x4f, 0xc3, 0xd3, 0xf4, 0x1f, 0x88, 0x68, 0x32, 0xa9, 0xe1, 0xdf, 0x0c, 0x8f, 0xfe,
	0x0c, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xd9, 0x46, 0x4a, 0x9b, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	GetOrderList(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderRes, error)
	GetOrderStatus(ctx context.Context, in *GetOrderStatusReq, opts ...grpc.CallOption) (*ListOrderStatusRes, error)
	AddOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*basepb.AnyRes, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetOrderList(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderRes, error) {
	out := new(ListOrderRes)
	err := c.cc.Invoke(ctx, "/orderpb.OrderService/GetOrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderStatus(ctx context.Context, in *GetOrderStatusReq, opts ...grpc.CallOption) (*ListOrderStatusRes, error) {
	out := new(ListOrderStatusRes)
	err := c.cc.Invoke(ctx, "/orderpb.OrderService/GetOrderStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AddOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/orderpb.OrderService/AddOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/orderpb.OrderService/PayOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/orderpb.OrderService/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/orderpb.OrderService/DeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	GetOrderList(context.Context, *ListOrderReq) (*ListOrderRes, error)
	GetOrderStatus(context.Context, *GetOrderStatusReq) (*ListOrderStatusRes, error)
	AddOrder(context.Context, *Order) (*basepb.AnyRes, error)
	PayOrder(context.Context, *PayOrderReq) (*basepb.AnyRes, error)
	CancelOrder(context.Context, *CancelOrderReq) (*basepb.AnyRes, error)
	DeleteOrder(context.Context, *DeleteOrderReq) (*basepb.AnyRes, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_GetOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.OrderService/GetOrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderList(ctx, req.(*ListOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.OrderService/GetOrderStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderStatus(ctx, req.(*GetOrderStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.OrderService/AddOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_PayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.OrderService/PayOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PayOrder(ctx, req.(*PayOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.OrderService/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.OrderService/DeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DeleteOrder(ctx, req.(*DeleteOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderpb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderList",
			Handler:    _OrderService_GetOrderList_Handler,
		},
		{
			MethodName: "GetOrderStatus",
			Handler:    _OrderService_GetOrderStatus_Handler,
		},
		{
			MethodName: "AddOrder",
			Handler:    _OrderService_AddOrder_Handler,
		},
		{
			MethodName: "PayOrder",
			Handler:    _OrderService_PayOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderService_CancelOrder_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _OrderService_DeleteOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderpb/order.proto",
}
