// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basepb/basepb.proto

package basepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnyRes struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                uint32   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnyRes) Reset()         { *m = AnyRes{} }
func (m *AnyRes) String() string { return proto.CompactTextString(m) }
func (*AnyRes) ProtoMessage()    {}
func (*AnyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_722048aedd2e50a3, []int{0}
}

func (m *AnyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyRes.Unmarshal(m, b)
}
func (m *AnyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyRes.Marshal(b, m, deterministic)
}
func (m *AnyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyRes.Merge(m, src)
}
func (m *AnyRes) XXX_Size() int {
	return xxx_messageInfo_AnyRes.Size(m)
}
func (m *AnyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyRes.DiscardUnknown(m)
}

var xxx_messageInfo_AnyRes proto.InternalMessageInfo

func (m *AnyRes) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AnyRes) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

// 根据主键id修改状态
type EditStatusReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	AdminId              uint64   `protobuf:"varint,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditStatusReq) Reset()         { *m = EditStatusReq{} }
func (m *EditStatusReq) String() string { return proto.CompactTextString(m) }
func (*EditStatusReq) ProtoMessage()    {}
func (*EditStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_722048aedd2e50a3, []int{1}
}

func (m *EditStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditStatusReq.Unmarshal(m, b)
}
func (m *EditStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditStatusReq.Marshal(b, m, deterministic)
}
func (m *EditStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditStatusReq.Merge(m, src)
}
func (m *EditStatusReq) XXX_Size() int {
	return xxx_messageInfo_EditStatusReq.Size(m)
}
func (m *EditStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditStatusReq proto.InternalMessageInfo

func (m *EditStatusReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditStatusReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *EditStatusReq) GetAdminId() uint64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

// 根据主键id获取单例
type GetOneReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneReq) Reset()         { *m = GetOneReq{} }
func (m *GetOneReq) String() string { return proto.CompactTextString(m) }
func (*GetOneReq) ProtoMessage()    {}
func (*GetOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_722048aedd2e50a3, []int{2}
}

func (m *GetOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneReq.Unmarshal(m, b)
}
func (m *GetOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneReq.Marshal(b, m, deterministic)
}
func (m *GetOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneReq.Merge(m, src)
}
func (m *GetOneReq) XXX_Size() int {
	return xxx_messageInfo_GetOneReq.Size(m)
}
func (m *GetOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneReq proto.InternalMessageInfo

func (m *GetOneReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 根据主键id删除
type DelReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelReq) Reset()         { *m = DelReq{} }
func (m *DelReq) String() string { return proto.CompactTextString(m) }
func (*DelReq) ProtoMessage()    {}
func (*DelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_722048aedd2e50a3, []int{3}
}

func (m *DelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelReq.Unmarshal(m, b)
}
func (m *DelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelReq.Marshal(b, m, deterministic)
}
func (m *DelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelReq.Merge(m, src)
}
func (m *DelReq) XXX_Size() int {
	return xxx_messageInfo_DelReq.Size(m)
}
func (m *DelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelReq proto.InternalMessageInfo

func (m *DelReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*AnyRes)(nil), "basepb.AnyRes")
	proto.RegisterType((*EditStatusReq)(nil), "basepb.EditStatusReq")
	proto.RegisterType((*GetOneReq)(nil), "basepb.GetOneReq")
	proto.RegisterType((*DelReq)(nil), "basepb.DelReq")
}

func init() { proto.RegisterFile("basepb/basepb.proto", fileDescriptor_722048aedd2e50a3) }

var fileDescriptor_722048aedd2e50a3 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4a, 0x2c, 0x4e,
	0x2d, 0x48, 0xd2, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x1e, 0x17, 0x9b, 0x63, 0x5e, 0x65, 0x50, 0x6a, 0xb1, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x08, 0x17, 0x6b, 0x71, 0x49, 0x62,
	0x49, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x84, 0xa3, 0x14, 0xc4, 0xc5, 0xeb, 0x9a,
	0x92, 0x59, 0x12, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x1c, 0x94, 0x5a, 0x88, 0xa1, 0x4d, 0x8c, 0x8b,
	0xad, 0x18, 0x2c, 0x09, 0xd6, 0xc7, 0x1a, 0x04, 0xe5, 0x09, 0x49, 0x72, 0x71, 0x24, 0xa6, 0xe4,
	0x66, 0xe6, 0xc5, 0x67, 0xa6, 0x48, 0x30, 0x83, 0x55, 0xb3, 0x83, 0xf9, 0x9e, 0x29, 0x4a, 0xd2,
	0x5c, 0x9c, 0xee, 0xa9, 0x25, 0xfe, 0x79, 0xa9, 0x58, 0xcc, 0x53, 0x92, 0xe0, 0x62, 0x73, 0x49,
	0xcd, 0xc1, 0x22, 0xe3, 0x24, 0x1f, 0x25, 0x9b, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c,
	0x9f, 0xab, 0x5f, 0x9c, 0x91, 0x99, 0x97, 0x9b, 0x99, 0x9e, 0xaf, 0x0f, 0xf7, 0x69, 0x12, 0x1b,
	0xd8, 0xab, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xc9, 0xe9, 0x7b, 0x01, 0x01, 0x00,
	0x00,
}
