// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tag.proto

package productpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tag struct {
	TagId                uint64   `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	StoreId              uint64   `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AdminId              uint64   `protobuf:"varint,4,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{0}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTagId() uint64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *Tag) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetAdminId() uint64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

type TagDetail struct {
	TagId                uint64   `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	StoreId              uint64   `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy            uint64   `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            uint64   `protobuf:"varint,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagDetail) Reset()         { *m = TagDetail{} }
func (m *TagDetail) String() string { return proto.CompactTextString(m) }
func (*TagDetail) ProtoMessage()    {}
func (*TagDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{1}
}

func (m *TagDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagDetail.Unmarshal(m, b)
}
func (m *TagDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagDetail.Marshal(b, m, deterministic)
}
func (m *TagDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagDetail.Merge(m, src)
}
func (m *TagDetail) XXX_Size() int {
	return xxx_messageInfo_TagDetail.Size(m)
}
func (m *TagDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TagDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TagDetail proto.InternalMessageInfo

func (m *TagDetail) GetTagId() uint64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *TagDetail) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *TagDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TagDetail) GetCreatedBy() uint64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *TagDetail) GetUpdatedBy() uint64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *TagDetail) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *TagDetail) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type DelTagReq struct {
	TagId                uint64   `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTagReq) Reset()         { *m = DelTagReq{} }
func (m *DelTagReq) String() string { return proto.CompactTextString(m) }
func (*DelTagReq) ProtoMessage()    {}
func (*DelTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{2}
}

func (m *DelTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTagReq.Unmarshal(m, b)
}
func (m *DelTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTagReq.Marshal(b, m, deterministic)
}
func (m *DelTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTagReq.Merge(m, src)
}
func (m *DelTagReq) XXX_Size() int {
	return xxx_messageInfo_DelTagReq.Size(m)
}
func (m *DelTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelTagReq proto.InternalMessageInfo

func (m *DelTagReq) GetTagId() uint64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

type AnyRes struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                uint32   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnyRes) Reset()         { *m = AnyRes{} }
func (m *AnyRes) String() string { return proto.CompactTextString(m) }
func (*AnyRes) ProtoMessage()    {}
func (*AnyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{3}
}

func (m *AnyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyRes.Unmarshal(m, b)
}
func (m *AnyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyRes.Marshal(b, m, deterministic)
}
func (m *AnyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyRes.Merge(m, src)
}
func (m *AnyRes) XXX_Size() int {
	return xxx_messageInfo_AnyRes.Size(m)
}
func (m *AnyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyRes.DiscardUnknown(m)
}

var xxx_messageInfo_AnyRes proto.InternalMessageInfo

func (m *AnyRes) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AnyRes) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type ListTagReq struct {
	Page                 uint64   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint64   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTagReq) Reset()         { *m = ListTagReq{} }
func (m *ListTagReq) String() string { return proto.CompactTextString(m) }
func (*ListTagReq) ProtoMessage()    {}
func (*ListTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{4}
}

func (m *ListTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagReq.Unmarshal(m, b)
}
func (m *ListTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagReq.Marshal(b, m, deterministic)
}
func (m *ListTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagReq.Merge(m, src)
}
func (m *ListTagReq) XXX_Size() int {
	return xxx_messageInfo_ListTagReq.Size(m)
}
func (m *ListTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagReq proto.InternalMessageInfo

func (m *ListTagReq) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListTagReq) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListTagReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListTagReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListTagRes struct {
	Total                uint64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Tags                 []*TagDetail `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListTagRes) Reset()         { *m = ListTagRes{} }
func (m *ListTagRes) String() string { return proto.CompactTextString(m) }
func (*ListTagRes) ProtoMessage()    {}
func (*ListTagRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{5}
}

func (m *ListTagRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagRes.Unmarshal(m, b)
}
func (m *ListTagRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagRes.Marshal(b, m, deterministic)
}
func (m *ListTagRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagRes.Merge(m, src)
}
func (m *ListTagRes) XXX_Size() int {
	return xxx_messageInfo_ListTagRes.Size(m)
}
func (m *ListTagRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagRes proto.InternalMessageInfo

func (m *ListTagRes) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListTagRes) GetTags() []*TagDetail {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Tag)(nil), "productpb.Tag")
	proto.RegisterType((*TagDetail)(nil), "productpb.TagDetail")
	proto.RegisterType((*DelTagReq)(nil), "productpb.DelTagReq")
	proto.RegisterType((*AnyRes)(nil), "productpb.AnyRes")
	proto.RegisterType((*ListTagReq)(nil), "productpb.ListTagReq")
	proto.RegisterType((*ListTagRes)(nil), "productpb.ListTagRes")
}

func init() { proto.RegisterFile("tag.proto", fileDescriptor_27f545bcde37ecb5) }

var fileDescriptor_27f545bcde37ecb5 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x25, 0x1f, 0x4d, 0x5f, 0xae, 0xf8, 0xc0, 0xe1, 0x3d, 0x88, 0x15, 0xa1, 0x64, 0x15, 0x50,
	0x02, 0xd6, 0x9d, 0xbb, 0x48, 0x45, 0x0a, 0x5d, 0xa5, 0xd9, 0x97, 0xdb, 0xce, 0x38, 0x0c, 0xb4,
	0x4d, 0xcc, 0xdc, 0x0a, 0xed, 0x7f, 0x74, 0xeb, 0xef, 0x91, 0x99, 0x4c, 0xd2, 0x08, 0x15, 0x5c,
	0xb8, 0xca, 0xdc, 0x7b, 0xce, 0xb9, 0x1f, 0x67, 0x26, 0x10, 0x13, 0xca, 0xbc, 0x69, 0x6b, 0xaa,
	0x59, 0xdc, 0xb4, 0x35, 0x3f, 0xef, 0xa9, 0xd9, 0xa5, 0xdf, 0x20, 0xa8, 0x50, 0xb2, 0x67, 0x88,
	0x08, 0xe5, 0x56, 0xf1, 0xc4, 0x9b, 0x7b, 0x59, 0x58, 0x4e, 0x08, 0xe5, 0x8a, 0xb3, 0xd7, 0xf0,
	0xa0, 0xa9, 0x6e, 0x85, 0x01, 0x7c, 0x0b, 0x4c, 0x6d, 0xbc, 0xe2, 0x8c, 0x41, 0x78, 0xc2, 0xa3,
	0x48, 0x82, 0xb9, 0x97, 0xc5, 0xa5, 0x3d, 0x1b, 0x3a, 0xf2, 0xa3, 0x3a, 0x19, 0x7a, 0xd8, 0xd1,
	0x6d, 0xbc, 0xe2, 0xe9, 0x4f, 0x0f, 0xe2, 0x0a, 0xe5, 0x52, 0x10, 0xaa, 0xc3, 0x7f, 0x6a, 0xf7,
	0x16, 0x60, 0xdf, 0x0a, 0x24, 0xc1, 0xb7, 0xbb, 0x8b, 0x6b, 0x18, 0xbb, 0xcc, 0xe7, 0x8b, 0x81,
	0xcf, 0x0d, 0xef, 0xe1, 0x49, 0x07, 0xbb, 0x4c, 0x07, 0xf7, 0x6a, 0xa4, 0x24, 0xb2, 0x75, 0x7b,
	0x75, 0x41, 0x63, 0x35, 0x52, 0x32, 0xed, 0x60, 0x97, 0x29, 0x28, 0x4d, 0x21, 0x5e, 0x8a, 0x43,
	0x85, 0xb2, 0x14, 0xdf, 0xff, 0xb2, 0x4e, 0x9a, 0x43, 0x54, 0x9c, 0x2e, 0xa5, 0xd0, 0xec, 0x11,
	0xfc, 0x01, 0xf4, 0x15, 0x67, 0x4f, 0x30, 0xd1, 0x84, 0x24, 0xec, 0x96, 0x2f, 0xcb, 0x2e, 0x48,
	0x11, 0x60, 0xad, 0x34, 0xb9, 0xa2, 0x0c, 0xc2, 0x06, 0xa5, 0x70, 0x2a, 0x7b, 0x66, 0x6f, 0x20,
	0x36, 0xdf, 0xad, 0x56, 0x57, 0xe1, 0x1c, 0x7a, 0x30, 0x89, 0x8d, 0xba, 0x0a, 0xd7, 0x24, 0x18,
	0x9a, 0xf4, 0x96, 0x85, 0x37, 0xcb, 0xd2, 0xf5, 0xa8, 0x85, 0x36, 0x63, 0x50, 0x4d, 0x78, 0x18,
	0xc6, 0x36, 0x01, 0xcb, 0x20, 0x24, 0x94, 0x3a, 0xf1, 0xe7, 0x41, 0xf6, 0x62, 0xf1, 0x94, 0x0f,
	0x8f, 0x25, 0x1f, 0x2e, 0xb0, 0xb4, 0x8c, 0xc5, 0x2f, 0x0f, 0xa0, 0x42, 0xb9, 0x11, 0xed, 0x0f,
	0xb5, 0x17, 0xec, 0x1d, 0x44, 0x05, 0xe7, 0xe6, 0x39, 0x3d, 0xfe, 0x29, 0x9a, 0xbd, 0x1a, 0xc5,
	0xce, 0x92, 0xf7, 0x30, 0xfd, 0xc2, 0x15, 0xfd, 0x23, 0xfb, 0x03, 0x44, 0x9d, 0xdd, 0x6c, 0x3c,
	0xcf, 0x70, 0x03, 0xf7, 0x24, 0x9f, 0x00, 0xbe, 0x0a, 0x53, 0xdf, 0x2c, 0xcc, 0x9e, 0x47, 0x84,
	0x9b, 0xc9, 0xb3, 0xbb, 0x69, 0xbd, 0x8b, 0xec, 0x7f, 0xf2, 0xf1, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb2, 0x7f, 0x45, 0xcc, 0x34, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TagServiceClient is the client API for TagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TagServiceClient interface {
	AddTag(ctx context.Context, in *Tag, opts ...grpc.CallOption) (*AnyRes, error)
	EditTag(ctx context.Context, in *Tag, opts ...grpc.CallOption) (*AnyRes, error)
	DelTag(ctx context.Context, in *DelTagReq, opts ...grpc.CallOption) (*AnyRes, error)
	GetTagList(ctx context.Context, in *ListTagReq, opts ...grpc.CallOption) (*ListTagRes, error)
}

type tagServiceClient struct {
	cc *grpc.ClientConn
}

func NewTagServiceClient(cc *grpc.ClientConn) TagServiceClient {
	return &tagServiceClient{cc}
}

func (c *tagServiceClient) AddTag(ctx context.Context, in *Tag, opts ...grpc.CallOption) (*AnyRes, error) {
	out := new(AnyRes)
	err := c.cc.Invoke(ctx, "/productpb.TagService/AddTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) EditTag(ctx context.Context, in *Tag, opts ...grpc.CallOption) (*AnyRes, error) {
	out := new(AnyRes)
	err := c.cc.Invoke(ctx, "/productpb.TagService/EditTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) DelTag(ctx context.Context, in *DelTagReq, opts ...grpc.CallOption) (*AnyRes, error) {
	out := new(AnyRes)
	err := c.cc.Invoke(ctx, "/productpb.TagService/DelTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) GetTagList(ctx context.Context, in *ListTagReq, opts ...grpc.CallOption) (*ListTagRes, error) {
	out := new(ListTagRes)
	err := c.cc.Invoke(ctx, "/productpb.TagService/GetTagList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServiceServer is the server API for TagService service.
type TagServiceServer interface {
	AddTag(context.Context, *Tag) (*AnyRes, error)
	EditTag(context.Context, *Tag) (*AnyRes, error)
	DelTag(context.Context, *DelTagReq) (*AnyRes, error)
	GetTagList(context.Context, *ListTagReq) (*ListTagRes, error)
}

func RegisterTagServiceServer(s *grpc.Server, srv TagServiceServer) {
	s.RegisterService(&_TagService_serviceDesc, srv)
}

func _TagService_AddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).AddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productpb.TagService/AddTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).AddTag(ctx, req.(*Tag))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_EditTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).EditTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productpb.TagService/EditTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).EditTag(ctx, req.(*Tag))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_DelTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).DelTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productpb.TagService/DelTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).DelTag(ctx, req.(*DelTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_GetTagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).GetTagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productpb.TagService/GetTagList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).GetTagList(ctx, req.(*ListTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TagService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "productpb.TagService",
	HandlerType: (*TagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTag",
			Handler:    _TagService_AddTag_Handler,
		},
		{
			MethodName: "EditTag",
			Handler:    _TagService_EditTag_Handler,
		},
		{
			MethodName: "DelTag",
			Handler:    _TagService_DelTag_Handler,
		},
		{
			MethodName: "GetTagList",
			Handler:    _TagService_GetTagList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tag.proto",
}
