// Code generated by protoc-gen-go. DO NOT EDIT.
// source: memberpb/address.proto

package memberpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basepb "github.com/shinmigo/pb/basepb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddressCategory int32

const (
	AddressCategory_Placeholder AddressCategory = 0
	AddressCategory_Home        AddressCategory = 1
	AddressCategory_Company     AddressCategory = 2
)

var AddressCategory_name = map[int32]string{
	0: "Placeholder",
	1: "Home",
	2: "Company",
}

var AddressCategory_value = map[string]int32{
	"Placeholder": 0,
	"Home":        1,
	"Company":     2,
}

func (x AddressCategory) String() string {
	return proto.EnumName(AddressCategory_name, int32(x))
}

func (AddressCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_93efbff1c0452860, []int{0}
}

type AddressIsDefault int32

const (
	AddressIsDefault_None AddressIsDefault = 0
	AddressIsDefault_Used AddressIsDefault = 1
)

var AddressIsDefault_name = map[int32]string{
	0: "None",
	1: "Used",
}

var AddressIsDefault_value = map[string]int32{
	"None": 0,
	"Used": 1,
}

func (x AddressIsDefault) String() string {
	return proto.EnumName(AddressIsDefault_name, int32(x))
}

func (AddressIsDefault) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_93efbff1c0452860, []int{1}
}

type Address struct {
	AddressId            uint64           `protobuf:"varint,1,opt,name=address_id,json=addressId,proto3" json:"address_id"`
	MemberId             uint64           `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	Category             AddressCategory  `protobuf:"varint,3,opt,name=category,proto3,enum=memberpb.AddressCategory" json:"category"`
	Name                 string           `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Mobile               string           `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile"`
	Tel                  string           `protobuf:"bytes,6,opt,name=tel,proto3" json:"tel"`
	Postcode             string           `protobuf:"bytes,7,opt,name=postcode,proto3" json:"postcode"`
	Address              string           `protobuf:"bytes,8,opt,name=address,proto3" json:"address"`
	CodeProv             uint64           `protobuf:"varint,9,opt,name=code_prov,json=codeProv,proto3" json:"code_prov"`
	CodeCity             uint64           `protobuf:"varint,10,opt,name=code_city,json=codeCity,proto3" json:"code_city"`
	CodeCoun             uint64           `protobuf:"varint,11,opt,name=code_coun,json=codeCoun,proto3" json:"code_coun"`
	CodeTown             uint64           `protobuf:"varint,12,opt,name=code_town,json=codeTown,proto3" json:"code_town"`
	IsDefault            AddressIsDefault `protobuf:"varint,13,opt,name=is_default,json=isDefault,proto3,enum=memberpb.AddressIsDefault" json:"is_default"`
	Longitude            string           `protobuf:"bytes,14,opt,name=longitude,proto3" json:"longitude"`
	Latitude             string           `protobuf:"bytes,15,opt,name=latitude,proto3" json:"latitude"`
	AdminId              uint64           `protobuf:"varint,16,opt,name=admin_id,json=adminId,proto3" json:"admin_id"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_93efbff1c0452860, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddressId() uint64 {
	if m != nil {
		return m.AddressId
	}
	return 0
}

func (m *Address) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *Address) GetCategory() AddressCategory {
	if m != nil {
		return m.Category
	}
	return AddressCategory_Placeholder
}

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Address) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *Address) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Address) GetCodeProv() uint64 {
	if m != nil {
		return m.CodeProv
	}
	return 0
}

func (m *Address) GetCodeCity() uint64 {
	if m != nil {
		return m.CodeCity
	}
	return 0
}

func (m *Address) GetCodeCoun() uint64 {
	if m != nil {
		return m.CodeCoun
	}
	return 0
}

func (m *Address) GetCodeTown() uint64 {
	if m != nil {
		return m.CodeTown
	}
	return 0
}

func (m *Address) GetIsDefault() AddressIsDefault {
	if m != nil {
		return m.IsDefault
	}
	return AddressIsDefault_None
}

func (m *Address) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *Address) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Address) GetAdminId() uint64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

type AddressDetail struct {
	AddressId            uint64           `protobuf:"varint,1,opt,name=address_id,json=addressId,proto3" json:"address_id"`
	MemberId             uint64           `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	Category             AddressCategory  `protobuf:"varint,3,opt,name=category,proto3,enum=memberpb.AddressCategory" json:"category"`
	Name                 string           `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Mobile               string           `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile"`
	Tel                  string           `protobuf:"bytes,6,opt,name=tel,proto3" json:"tel"`
	Postcode             string           `protobuf:"bytes,7,opt,name=postcode,proto3" json:"postcode"`
	Address              string           `protobuf:"bytes,8,opt,name=address,proto3" json:"address"`
	CodeProv             uint64           `protobuf:"varint,9,opt,name=code_prov,json=codeProv,proto3" json:"code_prov"`
	CodeCity             uint64           `protobuf:"varint,10,opt,name=code_city,json=codeCity,proto3" json:"code_city"`
	CodeCoun             uint64           `protobuf:"varint,11,opt,name=code_coun,json=codeCoun,proto3" json:"code_coun"`
	CodeTown             uint64           `protobuf:"varint,12,opt,name=code_town,json=codeTown,proto3" json:"code_town"`
	IsDefault            AddressIsDefault `protobuf:"varint,13,opt,name=is_default,json=isDefault,proto3,enum=memberpb.AddressIsDefault" json:"is_default"`
	Longitude            string           `protobuf:"bytes,14,opt,name=longitude,proto3" json:"longitude"`
	Latitude             string           `protobuf:"bytes,15,opt,name=latitude,proto3" json:"latitude"`
	CreatedBy            uint64           `protobuf:"varint,16,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedBy            uint64           `protobuf:"varint,17,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	CreatedAt            string           `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string           `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddressDetail) Reset()         { *m = AddressDetail{} }
func (m *AddressDetail) String() string { return proto.CompactTextString(m) }
func (*AddressDetail) ProtoMessage()    {}
func (*AddressDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_93efbff1c0452860, []int{1}
}

func (m *AddressDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressDetail.Unmarshal(m, b)
}
func (m *AddressDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressDetail.Marshal(b, m, deterministic)
}
func (m *AddressDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressDetail.Merge(m, src)
}
func (m *AddressDetail) XXX_Size() int {
	return xxx_messageInfo_AddressDetail.Size(m)
}
func (m *AddressDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressDetail.DiscardUnknown(m)
}

var xxx_messageInfo_AddressDetail proto.InternalMessageInfo

func (m *AddressDetail) GetAddressId() uint64 {
	if m != nil {
		return m.AddressId
	}
	return 0
}

func (m *AddressDetail) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *AddressDetail) GetCategory() AddressCategory {
	if m != nil {
		return m.Category
	}
	return AddressCategory_Placeholder
}

func (m *AddressDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddressDetail) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AddressDetail) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *AddressDetail) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *AddressDetail) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddressDetail) GetCodeProv() uint64 {
	if m != nil {
		return m.CodeProv
	}
	return 0
}

func (m *AddressDetail) GetCodeCity() uint64 {
	if m != nil {
		return m.CodeCity
	}
	return 0
}

func (m *AddressDetail) GetCodeCoun() uint64 {
	if m != nil {
		return m.CodeCoun
	}
	return 0
}

func (m *AddressDetail) GetCodeTown() uint64 {
	if m != nil {
		return m.CodeTown
	}
	return 0
}

func (m *AddressDetail) GetIsDefault() AddressIsDefault {
	if m != nil {
		return m.IsDefault
	}
	return AddressIsDefault_None
}

func (m *AddressDetail) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *AddressDetail) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *AddressDetail) GetCreatedBy() uint64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *AddressDetail) GetUpdatedBy() uint64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *AddressDetail) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *AddressDetail) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListAddressReq struct {
	MemberId             uint64   `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	Page                 uint64   `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	PageSize             uint64   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAddressReq) Reset()         { *m = ListAddressReq{} }
func (m *ListAddressReq) String() string { return proto.CompactTextString(m) }
func (*ListAddressReq) ProtoMessage()    {}
func (*ListAddressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_93efbff1c0452860, []int{2}
}

func (m *ListAddressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAddressReq.Unmarshal(m, b)
}
func (m *ListAddressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAddressReq.Marshal(b, m, deterministic)
}
func (m *ListAddressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAddressReq.Merge(m, src)
}
func (m *ListAddressReq) XXX_Size() int {
	return xxx_messageInfo_ListAddressReq.Size(m)
}
func (m *ListAddressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAddressReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListAddressReq proto.InternalMessageInfo

func (m *ListAddressReq) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *ListAddressReq) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAddressReq) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListAddressRes struct {
	Total                uint64           `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Addresses            []*AddressDetail `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListAddressRes) Reset()         { *m = ListAddressRes{} }
func (m *ListAddressRes) String() string { return proto.CompactTextString(m) }
func (*ListAddressRes) ProtoMessage()    {}
func (*ListAddressRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_93efbff1c0452860, []int{3}
}

func (m *ListAddressRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAddressRes.Unmarshal(m, b)
}
func (m *ListAddressRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAddressRes.Marshal(b, m, deterministic)
}
func (m *ListAddressRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAddressRes.Merge(m, src)
}
func (m *ListAddressRes) XXX_Size() int {
	return xxx_messageInfo_ListAddressRes.Size(m)
}
func (m *ListAddressRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAddressRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListAddressRes proto.InternalMessageInfo

func (m *ListAddressRes) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListAddressRes) GetAddresses() []*AddressDetail {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterEnum("memberpb.AddressCategory", AddressCategory_name, AddressCategory_value)
	proto.RegisterEnum("memberpb.AddressIsDefault", AddressIsDefault_name, AddressIsDefault_value)
	proto.RegisterType((*Address)(nil), "memberpb.Address")
	proto.RegisterType((*AddressDetail)(nil), "memberpb.AddressDetail")
	proto.RegisterType((*ListAddressReq)(nil), "memberpb.ListAddressReq")
	proto.RegisterType((*ListAddressRes)(nil), "memberpb.ListAddressRes")
}

func init() { proto.RegisterFile("memberpb/address.proto", fileDescriptor_93efbff1c0452860) }

var fileDescriptor_93efbff1c0452860 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xfe, 0xe5, 0x4f, 0x9b, 0x64, 0xf2, 0x6b, 0xea, 0x6e, 0x51, 0xd9, 0x06, 0x2a, 0x42, 0x0e,
	0x28, 0xaa, 0x50, 0x82, 0x8a, 0x7a, 0xe8, 0x05, 0x29, 0x6d, 0x50, 0x89, 0x04, 0xa5, 0x72, 0xe1,
	0x82, 0x04, 0xd1, 0x3a, 0x3b, 0xa4, 0x2b, 0xd9, 0x5e, 0xd7, 0xde, 0xb4, 0x72, 0xdf, 0x8a, 0xe7,
	0xe1, 0x35, 0x78, 0x00, 0xb4, 0xde, 0x75, 0xdc, 0x26, 0xea, 0x81, 0x2b, 0xe2, 0xe4, 0x9d, 0xef,
	0x9b, 0x6f, 0x66, 0xe7, 0x8f, 0xd6, 0xb0, 0x13, 0x60, 0xe0, 0x61, 0x1c, 0x79, 0x03, 0xc6, 0x79,
	0x8c, 0x49, 0xd2, 0x8f, 0x62, 0xa9, 0x24, 0xa9, 0xe7, 0x78, 0x7b, 0xdb, 0x63, 0x09, 0x46, 0xde,
	0xc0, 0x7c, 0x0c, 0xdd, 0xfd, 0x55, 0x81, 0xda, 0xd0, 0x08, 0xc8, 0x1e, 0x80, 0xd5, 0x4e, 0x04,
	0xa7, 0xa5, 0x4e, 0xa9, 0x57, 0x75, 0x1b, 0x16, 0x19, 0x73, 0xf2, 0x04, 0x1a, 0x26, 0x96, 0x66,
	0xcb, 0x19, 0x6b, 0x83, 0x8f, 0x39, 0x39, 0x84, 0xfa, 0x94, 0x29, 0x9c, 0xc9, 0x38, 0xa5, 0x95,
	0x4e, 0xa9, 0xd7, 0x3a, 0xd8, 0xed, 0xe7, 0x99, 0xfb, 0x36, 0xc1, 0x89, 0x75, 0x70, 0x17, 0xae,
	0x84, 0x40, 0x35, 0x64, 0x01, 0xd2, 0x6a, 0xa7, 0xd4, 0x6b, 0xb8, 0xd9, 0x99, 0xec, 0xc0, 0x7a,
	0x20, 0x3d, 0xe1, 0x23, 0x5d, 0xcb, 0x50, 0x6b, 0x11, 0x07, 0x2a, 0x0a, 0x7d, 0xba, 0x9e, 0x81,
	0xfa, 0x48, 0xda, 0x50, 0x8f, 0x64, 0xa2, 0xa6, 0x92, 0x23, 0xad, 0x65, 0xf0, 0xc2, 0x26, 0x14,
	0x6a, 0xf6, 0xea, 0xb4, 0x9e, 0x51, 0xb9, 0xa9, 0xeb, 0xd0, 0x1e, 0x93, 0x28, 0x96, 0xd7, 0xb4,
	0x61, 0xea, 0xd0, 0xc0, 0x79, 0x2c, 0xaf, 0x17, 0xe4, 0x54, 0xa8, 0x94, 0x42, 0x41, 0x9e, 0x08,
	0x95, 0x16, 0xa4, 0x9c, 0x87, 0xb4, 0x79, 0x87, 0x94, 0xf3, 0x70, 0x41, 0x2a, 0x79, 0x13, 0xd2,
	0xff, 0x0b, 0xf2, 0x93, 0xbc, 0x09, 0xc9, 0x11, 0x80, 0x48, 0x26, 0x1c, 0xbf, 0xb3, 0xb9, 0xaf,
	0xe8, 0x46, 0xd6, 0xa0, 0xf6, 0x4a, 0x83, 0xc6, 0xc9, 0xc8, 0x78, 0xb8, 0x0d, 0x91, 0x1f, 0xc9,
	0x53, 0x68, 0xf8, 0x32, 0x9c, 0x09, 0x35, 0xe7, 0x48, 0x5b, 0x59, 0x29, 0x05, 0xa0, 0x5b, 0xe0,
	0x33, 0x65, 0xc8, 0x4d, 0xd3, 0x82, 0xdc, 0x26, 0xbb, 0x50, 0x67, 0x3c, 0x10, 0xa1, 0x9e, 0x97,
	0x93, 0x5d, 0xa8, 0x96, 0xd9, 0x63, 0xde, 0xfd, 0x59, 0x85, 0x0d, 0x9b, 0x74, 0x84, 0x8a, 0x09,
	0xff, 0xdf, 0xf0, 0xff, 0xb2, 0xe1, 0xef, 0x01, 0x4c, 0x63, 0x64, 0x0a, 0xf9, 0xc4, 0x4b, 0xed,
	0xf8, 0x1b, 0x16, 0x39, 0x4e, 0x35, 0x3d, 0x8f, 0x78, 0x4e, 0x6f, 0x19, 0xda, 0x22, 0x86, 0xce,
	0xd5, 0x4c, 0x51, 0x62, 0x12, 0x5b, 0x64, 0xa8, 0xee, 0xaa, 0x99, 0xa2, 0xdb, 0x86, 0xb6, 0xc8,
	0x50, 0x75, 0xbf, 0x41, 0xeb, 0xbd, 0x48, 0x94, 0x2d, 0xcc, 0xc5, 0xab, 0xfb, 0xeb, 0x53, 0x5a,
	0x5a, 0x1f, 0x02, 0xd5, 0x88, 0xcd, 0xd0, 0xae, 0x55, 0x76, 0xd6, 0x02, 0xfd, 0x9d, 0x24, 0xe2,
	0x16, 0xb3, 0x9d, 0xaa, 0xba, 0x75, 0x0d, 0x5c, 0x88, 0x5b, 0xec, 0x7e, 0x5d, 0x8a, 0x9f, 0x90,
	0x47, 0xb0, 0xa6, 0xa4, 0x62, 0xbe, 0x8d, 0x6d, 0x0c, 0x72, 0x08, 0xf9, 0x06, 0x63, 0x42, 0xcb,
	0x9d, 0x4a, 0xaf, 0x79, 0xf0, 0x78, 0xa5, 0xef, 0x66, 0xff, 0xdd, 0xc2, 0x73, 0xff, 0x08, 0x36,
	0x97, 0x96, 0x96, 0x6c, 0x42, 0xf3, 0xdc, 0x67, 0x53, 0xbc, 0x94, 0x3e, 0xc7, 0xd8, 0xf9, 0x8f,
	0xd4, 0xa1, 0xfa, 0x4e, 0x06, 0xe8, 0x94, 0x48, 0x13, 0x6a, 0x27, 0x32, 0x88, 0x58, 0x98, 0x3a,
	0xe5, 0xfd, 0x17, 0xe0, 0x2c, 0x8f, 0x53, 0xbb, 0x9e, 0xc9, 0x10, 0x8d, 0xe8, 0x73, 0x82, 0xdc,
	0x29, 0x1d, 0xfc, 0x28, 0x43, 0xcb, 0x3a, 0x5e, 0x60, 0x7c, 0x2d, 0xa6, 0x48, 0x06, 0x00, 0x43,
	0xce, 0xf3, 0xb7, 0x78, 0x6b, 0xe5, 0x9e, 0xed, 0x56, 0xdf, 0xbe, 0xdc, 0xc3, 0x30, 0xd5, 0x35,
	0xbf, 0x82, 0xe6, 0x5b, 0x2e, 0xd4, 0x1f, 0x28, 0x5e, 0x02, 0x8c, 0xd0, 0xcf, 0x05, 0x0b, 0x76,
	0x84, 0xbe, 0x8b, 0x57, 0x2b, 0xde, 0x67, 0x40, 0x4f, 0x31, 0x0f, 0xaf, 0xfb, 0x7d, 0x9c, 0x7e,
	0xc8, 0x47, 0x46, 0x8b, 0x64, 0xf7, 0x27, 0xdd, 0x7e, 0x88, 0x49, 0xc8, 0x1b, 0x70, 0x8a, 0x78,
	0xf6, 0xd5, 0xd9, 0xca, 0x73, 0x9e, 0xa2, 0xfa, 0x18, 0xa2, 0x0e, 0xf0, 0xd0, 0x84, 0x8e, 0x9f,
	0x7f, 0x79, 0x36, 0x13, 0xea, 0x72, 0xee, 0xf5, 0xa7, 0x32, 0x18, 0x24, 0x97, 0x22, 0x0c, 0xc4,
	0x4c, 0x0e, 0x22, 0x6f, 0x90, 0x0b, 0xbc, 0xf5, 0xec, 0xa7, 0xf6, 0xfa, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf2, 0x85, 0xeb, 0x71, 0x0d, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddressServiceClient is the client API for AddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressServiceClient interface {
	AddAddress(ctx context.Context, in *Address, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	EditAddress(ctx context.Context, in *Address, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	DelAddress(ctx context.Context, in *basepb.DelReq, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	// 根据会员id获取收货地址，会员id必传
	GetAddressListByMemberId(ctx context.Context, in *ListAddressReq, opts ...grpc.CallOption) (*ListAddressRes, error)
	GetAddressDetail(ctx context.Context, in *basepb.GetOneReq, opts ...grpc.CallOption) (*AddressDetail, error)
}

type addressServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddressServiceClient(cc *grpc.ClientConn) AddressServiceClient {
	return &addressServiceClient{cc}
}

func (c *addressServiceClient) AddAddress(ctx context.Context, in *Address, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/memberpb.AddressService/AddAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) EditAddress(ctx context.Context, in *Address, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/memberpb.AddressService/EditAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) DelAddress(ctx context.Context, in *basepb.DelReq, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/memberpb.AddressService/DelAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) GetAddressListByMemberId(ctx context.Context, in *ListAddressReq, opts ...grpc.CallOption) (*ListAddressRes, error) {
	out := new(ListAddressRes)
	err := c.cc.Invoke(ctx, "/memberpb.AddressService/GetAddressListByMemberId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) GetAddressDetail(ctx context.Context, in *basepb.GetOneReq, opts ...grpc.CallOption) (*AddressDetail, error) {
	out := new(AddressDetail)
	err := c.cc.Invoke(ctx, "/memberpb.AddressService/GetAddressDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressServiceServer is the server API for AddressService service.
type AddressServiceServer interface {
	AddAddress(context.Context, *Address) (*basepb.AnyRes, error)
	EditAddress(context.Context, *Address) (*basepb.AnyRes, error)
	DelAddress(context.Context, *basepb.DelReq) (*basepb.AnyRes, error)
	// 根据会员id获取收货地址，会员id必传
	GetAddressListByMemberId(context.Context, *ListAddressReq) (*ListAddressRes, error)
	GetAddressDetail(context.Context, *basepb.GetOneReq) (*AddressDetail, error)
}

// UnimplementedAddressServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddressServiceServer struct {
}

func (*UnimplementedAddressServiceServer) AddAddress(ctx context.Context, req *Address) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAddress not implemented")
}
func (*UnimplementedAddressServiceServer) EditAddress(ctx context.Context, req *Address) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditAddress not implemented")
}
func (*UnimplementedAddressServiceServer) DelAddress(ctx context.Context, req *basepb.DelReq) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelAddress not implemented")
}
func (*UnimplementedAddressServiceServer) GetAddressListByMemberId(ctx context.Context, req *ListAddressReq) (*ListAddressRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressListByMemberId not implemented")
}
func (*UnimplementedAddressServiceServer) GetAddressDetail(ctx context.Context, req *basepb.GetOneReq) (*AddressDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressDetail not implemented")
}

func RegisterAddressServiceServer(s *grpc.Server, srv AddressServiceServer) {
	s.RegisterService(&_AddressService_serviceDesc, srv)
}

func _AddressService_AddAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).AddAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.AddressService/AddAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).AddAddress(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_EditAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).EditAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.AddressService/EditAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).EditAddress(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_DelAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(basepb.DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).DelAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.AddressService/DelAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).DelAddress(ctx, req.(*basepb.DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_GetAddressListByMemberId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).GetAddressListByMemberId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.AddressService/GetAddressListByMemberId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).GetAddressListByMemberId(ctx, req.(*ListAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_GetAddressDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(basepb.GetOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).GetAddressDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.AddressService/GetAddressDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).GetAddressDetail(ctx, req.(*basepb.GetOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "memberpb.AddressService",
	HandlerType: (*AddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAddress",
			Handler:    _AddressService_AddAddress_Handler,
		},
		{
			MethodName: "EditAddress",
			Handler:    _AddressService_EditAddress_Handler,
		},
		{
			MethodName: "DelAddress",
			Handler:    _AddressService_DelAddress_Handler,
		},
		{
			MethodName: "GetAddressListByMemberId",
			Handler:    _AddressService_GetAddressListByMemberId_Handler,
		},
		{
			MethodName: "GetAddressDetail",
			Handler:    _AddressService_GetAddressDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memberpb/address.proto",
}
