// Code generated by protoc-gen-go. DO NOT EDIT.
// source: memberpb/member.proto

package memberpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basepb "github.com/shinmigo/pb/basepb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MemberGender int32

const (
	MemberGender_Unknown MemberGender = 0
	MemberGender_Woman   MemberGender = 1
	MemberGender_Man     MemberGender = 2
)

var MemberGender_name = map[int32]string{
	0: "Unknown",
	1: "Woman",
	2: "Man",
}

var MemberGender_value = map[string]int32{
	"Unknown": 0,
	"Woman":   1,
	"Man":     2,
}

func (x MemberGender) String() string {
	return proto.EnumName(MemberGender_name, int32(x))
}

func (MemberGender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{0}
}

type MemberStatus int32

const (
	MemberStatus_Placeholder MemberStatus = 0
	MemberStatus_Normal      MemberStatus = 1
	MemberStatus_Freeze      MemberStatus = 2
)

var MemberStatus_name = map[int32]string{
	0: "Placeholder",
	1: "Normal",
	2: "Freeze",
}

var MemberStatus_value = map[string]int32{
	"Placeholder": 0,
	"Normal":      1,
	"Freeze":      2,
}

func (x MemberStatus) String() string {
	return proto.EnumName(MemberStatus_name, int32(x))
}

func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{1}
}

type MemberIdReq struct {
	MemberId             uint64   `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberIdReq) Reset()         { *m = MemberIdReq{} }
func (m *MemberIdReq) String() string { return proto.CompactTextString(m) }
func (*MemberIdReq) ProtoMessage()    {}
func (*MemberIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{0}
}

func (m *MemberIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberIdReq.Unmarshal(m, b)
}
func (m *MemberIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberIdReq.Marshal(b, m, deterministic)
}
func (m *MemberIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberIdReq.Merge(m, src)
}
func (m *MemberIdReq) XXX_Size() int {
	return xxx_messageInfo_MemberIdReq.Size(m)
}
func (m *MemberIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_MemberIdReq proto.InternalMessageInfo

func (m *MemberIdReq) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

type MobilePasswdReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobilePasswdReq) Reset()         { *m = MobilePasswdReq{} }
func (m *MobilePasswdReq) String() string { return proto.CompactTextString(m) }
func (*MobilePasswdReq) ProtoMessage()    {}
func (*MobilePasswdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{1}
}

func (m *MobilePasswdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobilePasswdReq.Unmarshal(m, b)
}
func (m *MobilePasswdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobilePasswdReq.Marshal(b, m, deterministic)
}
func (m *MobilePasswdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobilePasswdReq.Merge(m, src)
}
func (m *MobilePasswdReq) XXX_Size() int {
	return xxx_messageInfo_MobilePasswdReq.Size(m)
}
func (m *MobilePasswdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MobilePasswdReq.DiscardUnknown(m)
}

var xxx_messageInfo_MobilePasswdReq proto.InternalMessageInfo

func (m *MobilePasswdReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MobilePasswdReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MobilePasswdReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type LoginRes struct {
	MemberId             uint64       `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	Nickname             string       `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	Mobile               string       `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile"`
	Name                 string       `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Gender               MemberGender `protobuf:"varint,6,opt,name=gender,proto3,enum=memberpb.MemberGender" json:"gender"`
	IdCard               string       `protobuf:"bytes,7,opt,name=id_card,json=idCard,proto3" json:"id_card"`
	Birthday             string       `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday"`
	Avatar               string       `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar"`
	Email                string       `protobuf:"bytes,10,opt,name=email,proto3" json:"email"`
	MemberLevelId        uint64       `protobuf:"varint,13,opt,name=member_level_id,json=memberLevelId,proto3" json:"member_level_id"`
	Point                int64        `protobuf:"varint,14,opt,name=point,proto3" json:"point"`
	Balance              float64      `protobuf:"fixed64,15,opt,name=balance,proto3" json:"balance"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{2}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *LoginRes) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *LoginRes) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRes) GetGender() MemberGender {
	if m != nil {
		return m.Gender
	}
	return MemberGender_Unknown
}

func (m *LoginRes) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *LoginRes) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *LoginRes) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *LoginRes) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRes) GetMemberLevelId() uint64 {
	if m != nil {
		return m.MemberLevelId
	}
	return 0
}

func (m *LoginRes) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *LoginRes) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type Member struct {
	MemberId             uint64       `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	Nickname             string       `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	Mobile               string       `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile"`
	RegisterIp           string       `protobuf:"bytes,4,opt,name=register_ip,json=registerIp,proto3" json:"register_ip"`
	Name                 string       `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Gender               MemberGender `protobuf:"varint,6,opt,name=gender,proto3,enum=memberpb.MemberGender" json:"gender"`
	IdCard               string       `protobuf:"bytes,7,opt,name=id_card,json=idCard,proto3" json:"id_card"`
	Birthday             string       `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday"`
	Avatar               string       `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar"`
	Email                string       `protobuf:"bytes,10,opt,name=email,proto3" json:"email"`
	Status               MemberStatus `protobuf:"varint,11,opt,name=status,proto3,enum=memberpb.MemberStatus" json:"status"`
	Remark               string       `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark"`
	MemberLevelId        uint64       `protobuf:"varint,13,opt,name=member_level_id,json=memberLevelId,proto3" json:"member_level_id"`
	Point                int64        `protobuf:"varint,14,opt,name=point,proto3" json:"point"`
	Balance              float64      `protobuf:"fixed64,15,opt,name=balance,proto3" json:"balance"`
	AdminId              uint64       `protobuf:"varint,16,opt,name=admin_id,json=adminId,proto3" json:"admin_id"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{3}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *Member) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Member) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Member) GetRegisterIp() string {
	if m != nil {
		return m.RegisterIp
	}
	return ""
}

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetGender() MemberGender {
	if m != nil {
		return m.Gender
	}
	return MemberGender_Unknown
}

func (m *Member) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *Member) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Member) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Member) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Member) GetStatus() MemberStatus {
	if m != nil {
		return m.Status
	}
	return MemberStatus_Placeholder
}

func (m *Member) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *Member) GetMemberLevelId() uint64 {
	if m != nil {
		return m.MemberLevelId
	}
	return 0
}

func (m *Member) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *Member) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Member) GetAdminId() uint64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

type MemberDetail struct {
	MemberId             uint64       `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	Nickname             string       `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	Mobile               string       `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile"`
	RegisterIp           string       `protobuf:"bytes,4,opt,name=register_ip,json=registerIp,proto3" json:"register_ip"`
	Name                 string       `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Gender               MemberGender `protobuf:"varint,6,opt,name=gender,proto3,enum=memberpb.MemberGender" json:"gender"`
	IdCard               string       `protobuf:"bytes,7,opt,name=id_card,json=idCard,proto3" json:"id_card"`
	Birthday             string       `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday"`
	Avatar               string       `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar"`
	Email                string       `protobuf:"bytes,10,opt,name=email,proto3" json:"email"`
	Status               MemberStatus `protobuf:"varint,11,opt,name=status,proto3,enum=memberpb.MemberStatus" json:"status"`
	Remark               string       `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark"`
	MemberLevelId        uint64       `protobuf:"varint,13,opt,name=member_level_id,json=memberLevelId,proto3" json:"member_level_id"`
	Point                int64        `protobuf:"varint,14,opt,name=point,proto3" json:"point"`
	Balance              float64      `protobuf:"fixed64,15,opt,name=balance,proto3" json:"balance"`
	CreatedBy            uint64       `protobuf:"varint,16,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedBy            uint64       `protobuf:"varint,17,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	CreatedAt            string       `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string       `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MemberDetail) Reset()         { *m = MemberDetail{} }
func (m *MemberDetail) String() string { return proto.CompactTextString(m) }
func (*MemberDetail) ProtoMessage()    {}
func (*MemberDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{4}
}

func (m *MemberDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberDetail.Unmarshal(m, b)
}
func (m *MemberDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberDetail.Marshal(b, m, deterministic)
}
func (m *MemberDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberDetail.Merge(m, src)
}
func (m *MemberDetail) XXX_Size() int {
	return xxx_messageInfo_MemberDetail.Size(m)
}
func (m *MemberDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberDetail.DiscardUnknown(m)
}

var xxx_messageInfo_MemberDetail proto.InternalMessageInfo

func (m *MemberDetail) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *MemberDetail) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *MemberDetail) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MemberDetail) GetRegisterIp() string {
	if m != nil {
		return m.RegisterIp
	}
	return ""
}

func (m *MemberDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberDetail) GetGender() MemberGender {
	if m != nil {
		return m.Gender
	}
	return MemberGender_Unknown
}

func (m *MemberDetail) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *MemberDetail) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *MemberDetail) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *MemberDetail) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MemberDetail) GetStatus() MemberStatus {
	if m != nil {
		return m.Status
	}
	return MemberStatus_Placeholder
}

func (m *MemberDetail) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *MemberDetail) GetMemberLevelId() uint64 {
	if m != nil {
		return m.MemberLevelId
	}
	return 0
}

func (m *MemberDetail) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *MemberDetail) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *MemberDetail) GetCreatedBy() uint64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *MemberDetail) GetUpdatedBy() uint64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *MemberDetail) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MemberDetail) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetMemberReq struct {
	Page                 uint64   `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	PageSize             uint64   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	MemberId             uint64   `protobuf:"varint,3,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile"`
	Nickname             string   `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberReq) Reset()         { *m = GetMemberReq{} }
func (m *GetMemberReq) String() string { return proto.CompactTextString(m) }
func (*GetMemberReq) ProtoMessage()    {}
func (*GetMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{5}
}

func (m *GetMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberReq.Unmarshal(m, b)
}
func (m *GetMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberReq.Marshal(b, m, deterministic)
}
func (m *GetMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberReq.Merge(m, src)
}
func (m *GetMemberReq) XXX_Size() int {
	return xxx_messageInfo_GetMemberReq.Size(m)
}
func (m *GetMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberReq proto.InternalMessageInfo

func (m *GetMemberReq) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetMemberReq) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetMemberReq) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *GetMemberReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetMemberReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetMemberReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type ListMemberRes struct {
	Total                uint64          `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Members              []*MemberDetail `protobuf:"bytes,2,rep,name=members,proto3" json:"members"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListMemberRes) Reset()         { *m = ListMemberRes{} }
func (m *ListMemberRes) String() string { return proto.CompactTextString(m) }
func (*ListMemberRes) ProtoMessage()    {}
func (*ListMemberRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8652353e99042959, []int{6}
}

func (m *ListMemberRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMemberRes.Unmarshal(m, b)
}
func (m *ListMemberRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMemberRes.Marshal(b, m, deterministic)
}
func (m *ListMemberRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMemberRes.Merge(m, src)
}
func (m *ListMemberRes) XXX_Size() int {
	return xxx_messageInfo_ListMemberRes.Size(m)
}
func (m *ListMemberRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMemberRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListMemberRes proto.InternalMessageInfo

func (m *ListMemberRes) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListMemberRes) GetMembers() []*MemberDetail {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterEnum("memberpb.MemberGender", MemberGender_name, MemberGender_value)
	proto.RegisterEnum("memberpb.MemberStatus", MemberStatus_name, MemberStatus_value)
	proto.RegisterType((*MemberIdReq)(nil), "memberpb.MemberIdReq")
	proto.RegisterType((*MobilePasswdReq)(nil), "memberpb.MobilePasswdReq")
	proto.RegisterType((*LoginRes)(nil), "memberpb.LoginRes")
	proto.RegisterType((*Member)(nil), "memberpb.Member")
	proto.RegisterType((*MemberDetail)(nil), "memberpb.MemberDetail")
	proto.RegisterType((*GetMemberReq)(nil), "memberpb.GetMemberReq")
	proto.RegisterType((*ListMemberRes)(nil), "memberpb.ListMemberRes")
}

func init() { proto.RegisterFile("memberpb/member.proto", fileDescriptor_8652353e99042959) }

var fileDescriptor_8652353e99042959 = []byte{
	// 820 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xee, 0x7a, 0xed, 0xb5, 0x7d, 0x1c, 0xc7, 0x9b, 0x29, 0x49, 0xa7, 0x46, 0xa8, 0xc6, 0x17,
	0xc8, 0x8a, 0xc4, 0x1a, 0x95, 0x0b, 0x84, 0x84, 0x10, 0x0e, 0xd0, 0xc8, 0x52, 0x02, 0xd5, 0x56,
	0x55, 0x25, 0x6e, 0xa2, 0x59, 0xcf, 0x91, 0x33, 0xca, 0xfe, 0x75, 0x76, 0x92, 0xca, 0x79, 0x22,
	0xde, 0x83, 0xb7, 0x40, 0x3c, 0x02, 0x0f, 0x81, 0xe6, 0x67, 0xb7, 0x76, 0x4a, 0x11, 0x42, 0x70,
	0x11, 0x89, 0xab, 0x9d, 0x73, 0xce, 0x77, 0xce, 0x7e, 0xe7, 0xcc, 0x37, 0x3b, 0x0b, 0x87, 0x19,
	0x66, 0x09, 0xca, 0x32, 0x99, 0xdb, 0x45, 0x54, 0xca, 0x42, 0x15, 0xa4, 0x57, 0xbb, 0xc7, 0x0f,
	0x13, 0x56, 0x61, 0x99, 0xcc, 0xed, 0xc3, 0x86, 0xa7, 0xc7, 0x30, 0x38, 0x37, 0x80, 0x25, 0x8f,
	0xf1, 0x35, 0xf9, 0x10, 0xfa, 0x16, 0x7f, 0x21, 0x38, 0xf5, 0x26, 0xde, 0xac, 0x1d, 0xbb, 0x02,
	0x4b, 0x3e, 0x7d, 0x09, 0xa3, 0xf3, 0x22, 0x11, 0x29, 0x3e, 0x67, 0x55, 0xf5, 0xc6, 0xe0, 0x8f,
	0x20, 0xc8, 0x8c, 0xcb, 0x80, 0xfb, 0xb1, 0xb3, 0xc8, 0x18, 0x7a, 0xa5, 0x06, 0x15, 0x92, 0xd3,
	0x96, 0x89, 0x34, 0x36, 0xd9, 0x87, 0x96, 0x28, 0xa9, 0x6f, 0xbc, 0x2d, 0x51, 0x4e, 0x7f, 0x6d,
	0x41, 0xef, 0xac, 0x58, 0x8b, 0x3c, 0xc6, 0xea, 0x2f, 0x09, 0xe8, 0xaa, 0xb9, 0x58, 0x5d, 0xe5,
	0x2c, 0xc3, 0xba, 0x6a, 0x6d, 0x6f, 0x31, 0xf1, 0x77, 0x98, 0x10, 0x68, 0x1b, 0x7c, 0xc7, 0x78,
	0xcd, 0x9a, 0x44, 0x10, 0xac, 0x31, 0xe7, 0x28, 0x69, 0x30, 0xf1, 0x66, 0xfb, 0x4f, 0x8f, 0xa2,
	0x7a, 0x48, 0x91, 0x1d, 0xc6, 0xa9, 0x89, 0xc6, 0x0e, 0x45, 0x1e, 0x41, 0x57, 0xf0, 0x8b, 0x15,
	0x93, 0x9c, 0x76, 0x6d, 0x71, 0xc1, 0xbf, 0x65, 0xd2, 0x10, 0x4a, 0x84, 0x54, 0x97, 0x9c, 0x6d,
	0x68, 0xcf, 0x12, 0xaa, 0x6d, 0x4d, 0x88, 0xdd, 0x30, 0xc5, 0x24, 0xed, 0xdb, 0x1c, 0x6b, 0x91,
	0x0f, 0xa0, 0x83, 0x19, 0x13, 0x29, 0x05, 0xe3, 0xb6, 0x06, 0xf9, 0x04, 0x46, 0xae, 0xef, 0x14,
	0x6f, 0x30, 0xd5, 0xdd, 0x0f, 0x4d, 0xf7, 0x43, 0xeb, 0x3e, 0xd3, 0xde, 0x25, 0xd7, 0xd9, 0x65,
	0x21, 0x72, 0x45, 0xf7, 0x27, 0xde, 0xcc, 0x8f, 0xad, 0x41, 0x28, 0x74, 0x13, 0x96, 0xb2, 0x7c,
	0x85, 0x74, 0x34, 0xf1, 0x66, 0x5e, 0x5c, 0x9b, 0xd3, 0xdf, 0x7c, 0x08, 0x6c, 0x4f, 0xff, 0xfe,
	0x68, 0x9f, 0xc0, 0x40, 0xe2, 0x5a, 0x54, 0x4a, 0x97, 0x2c, 0x69, 0xdb, 0x04, 0xa1, 0x76, 0x2d,
	0xcb, 0xfb, 0x32, 0xfb, 0x08, 0x82, 0x4a, 0x31, 0x75, 0x5d, 0xd1, 0xc1, 0x9f, 0x53, 0x7a, 0x61,
	0xa2, 0xb1, 0x43, 0xe9, 0xea, 0x12, 0x33, 0x26, 0xaf, 0xe8, 0x9e, 0xad, 0x6e, 0xad, 0xff, 0x6a,
	0x0f, 0xc9, 0x63, 0xe8, 0x31, 0x9e, 0x89, 0x5c, 0x17, 0x0c, 0x4d, 0xc1, 0xae, 0xb1, 0x97, 0x7c,
	0xfa, 0x4b, 0x1b, 0xf6, 0x2c, 0xc7, 0xef, 0x50, 0xe9, 0x5e, 0xfe, 0xdf, 0xe4, 0x7b, 0xba, 0xc9,
	0x1f, 0x01, 0xac, 0x24, 0x32, 0x85, 0xfc, 0x22, 0xd9, 0xb8, 0x6d, 0xee, 0x3b, 0xcf, 0xc9, 0x46,
	0x87, 0xaf, 0x4b, 0x5e, 0x87, 0x0f, 0x6c, 0xd8, 0x79, 0x6c, 0xb8, 0xce, 0x66, 0x8a, 0x12, 0xc3,
	0xb8, 0xce, 0x5e, 0xa8, 0xed, 0x6c, 0xa6, 0xe8, 0x43, 0x1b, 0x76, 0x9e, 0x85, 0x9a, 0xfe, 0xec,
	0xc1, 0xde, 0x29, 0x2a, 0x3b, 0x07, 0xfd, 0x59, 0x27, 0xd0, 0x2e, 0xd9, 0x1a, 0x9d, 0x80, 0xcc,
	0x5a, 0x2b, 0x4b, 0x3f, 0x2f, 0x2a, 0x71, 0x6b, 0xd5, 0xd3, 0xd6, 0xdf, 0xf4, 0x35, 0xbe, 0x10,
	0xb7, 0xb8, 0x2b, 0x3b, 0xff, 0x8e, 0xec, 0x8e, 0x9a, 0xd1, 0x6b, 0xf5, 0x74, 0xb6, 0x47, 0xec,
	0x24, 0xd7, 0xb9, 0x7b, 0x79, 0x34, 0x32, 0x0d, 0x76, 0x65, 0x3a, 0x7d, 0x05, 0xc3, 0x33, 0x51,
	0x35, 0x54, 0x2b, 0x3d, 0x67, 0x55, 0x28, 0x96, 0x3a, 0xae, 0xd6, 0x20, 0x9f, 0x41, 0xd7, 0xbe,
	0xbe, 0xa2, 0xad, 0x89, 0x3f, 0x1b, 0xbc, 0xbb, 0xdd, 0xf6, 0xbc, 0xc4, 0x35, 0xec, 0x78, 0x5e,
	0x1f, 0x24, 0x2b, 0x4d, 0x32, 0x80, 0xee, 0xcb, 0xfc, 0x2a, 0x2f, 0xde, 0xe4, 0xe1, 0x03, 0xd2,
	0x87, 0xce, 0xab, 0x22, 0x63, 0x79, 0xe8, 0x91, 0x2e, 0xf8, 0xe7, 0x2c, 0x0f, 0x5b, 0xc7, 0x5f,
	0xd4, 0x09, 0x56, 0x38, 0x64, 0x04, 0x83, 0xe7, 0x29, 0x5b, 0xe1, 0x65, 0x91, 0x72, 0x94, 0xe1,
	0x03, 0x02, 0x10, 0xfc, 0x50, 0xc8, 0x8c, 0xa5, 0xa1, 0xa7, 0xd7, 0xcf, 0x24, 0xe2, 0x2d, 0x86,
	0xad, 0xa7, 0xbf, 0xfb, 0x30, 0x74, 0x99, 0x28, 0x6f, 0xc4, 0x0a, 0xc9, 0x02, 0xc2, 0xd8, 0x1d,
	0xa8, 0x93, 0x8d, 0xbd, 0x62, 0xc9, 0xe3, 0x2d, 0xc2, 0xbb, 0x97, 0xee, 0x98, 0xbc, 0x0d, 0x35,
	0xf7, 0xe6, 0xd7, 0x30, 0x34, 0xeb, 0x7f, 0x9e, 0x7f, 0xd0, 0x28, 0xe0, 0x59, 0x21, 0x8d, 0x9f,
	0x1c, 0xde, 0x1d, 0xda, 0xf2, 0xbd, 0xf9, 0x9f, 0x42, 0x7f, 0xc1, 0xb9, 0xbb, 0x69, 0xc2, 0xbb,
	0x79, 0xe3, 0xfd, 0xc8, 0xfd, 0x75, 0x2c, 0xf2, 0x8d, 0x86, 0x47, 0x00, 0xdf, 0x73, 0xa1, 0xfe,
	0x36, 0xfe, 0x4b, 0x08, 0xdf, 0xe2, 0xdd, 0xc0, 0x0f, 0x6b, 0x8c, 0x8e, 0xb8, 0xd3, 0x8b, 0xaf,
	0xdf, 0x49, 0xfd, 0x06, 0x86, 0x4d, 0x67, 0x5a, 0x3a, 0x64, 0x4b, 0x0a, 0xdb, 0xa2, 0x1f, 0x3f,
	0xda, 0x6a, 0x6b, 0x47, 0x62, 0x5f, 0xc1, 0xa8, 0x01, 0xba, 0xcf, 0xec, 0x41, 0xfd, 0x92, 0x53,
	0x54, 0x3f, 0xe6, 0xa8, 0xd3, 0xdf, 0xa3, 0xb0, 0x93, 0x8f, 0x7f, 0x7a, 0xb2, 0x16, 0xea, 0xf2,
	0x3a, 0x89, 0x56, 0x45, 0x36, 0xaf, 0x2e, 0x45, 0x9e, 0x89, 0x75, 0x31, 0x6f, 0xfe, 0xd3, 0xca,
	0x24, 0x09, 0xcc, 0xbf, 0xd8, 0xe7, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xbc, 0xeb, 0xe8,
	0xc3, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemberServiceClient is the client API for MemberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberServiceClient interface {
	RegisterByMobile(ctx context.Context, in *MobilePasswdReq, opts ...grpc.CallOption) (*LoginRes, error)
	LoginByMobile(ctx context.Context, in *MobilePasswdReq, opts ...grpc.CallOption) (*LoginRes, error)
	GetMemberForLogin(ctx context.Context, in *MemberIdReq, opts ...grpc.CallOption) (*LoginRes, error)
	AddMember(ctx context.Context, in *Member, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	EditMember(ctx context.Context, in *Member, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	EditMemberStatus(ctx context.Context, in *basepb.EditStatusReq, opts ...grpc.CallOption) (*basepb.AnyRes, error)
	GetMemberList(ctx context.Context, in *GetMemberReq, opts ...grpc.CallOption) (*ListMemberRes, error)
	GetMemberDetail(ctx context.Context, in *basepb.GetOneReq, opts ...grpc.CallOption) (*MemberDetail, error)
}

type memberServiceClient struct {
	cc *grpc.ClientConn
}

func NewMemberServiceClient(cc *grpc.ClientConn) MemberServiceClient {
	return &memberServiceClient{cc}
}

func (c *memberServiceClient) RegisterByMobile(ctx context.Context, in *MobilePasswdReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, "/memberpb.MemberService/RegisterByMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) LoginByMobile(ctx context.Context, in *MobilePasswdReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, "/memberpb.MemberService/LoginByMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) GetMemberForLogin(ctx context.Context, in *MemberIdReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, "/memberpb.MemberService/GetMemberForLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) AddMember(ctx context.Context, in *Member, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/memberpb.MemberService/AddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) EditMember(ctx context.Context, in *Member, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/memberpb.MemberService/EditMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) EditMemberStatus(ctx context.Context, in *basepb.EditStatusReq, opts ...grpc.CallOption) (*basepb.AnyRes, error) {
	out := new(basepb.AnyRes)
	err := c.cc.Invoke(ctx, "/memberpb.MemberService/EditMemberStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) GetMemberList(ctx context.Context, in *GetMemberReq, opts ...grpc.CallOption) (*ListMemberRes, error) {
	out := new(ListMemberRes)
	err := c.cc.Invoke(ctx, "/memberpb.MemberService/GetMemberList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) GetMemberDetail(ctx context.Context, in *basepb.GetOneReq, opts ...grpc.CallOption) (*MemberDetail, error) {
	out := new(MemberDetail)
	err := c.cc.Invoke(ctx, "/memberpb.MemberService/GetMemberDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServiceServer is the server API for MemberService service.
type MemberServiceServer interface {
	RegisterByMobile(context.Context, *MobilePasswdReq) (*LoginRes, error)
	LoginByMobile(context.Context, *MobilePasswdReq) (*LoginRes, error)
	GetMemberForLogin(context.Context, *MemberIdReq) (*LoginRes, error)
	AddMember(context.Context, *Member) (*basepb.AnyRes, error)
	EditMember(context.Context, *Member) (*basepb.AnyRes, error)
	EditMemberStatus(context.Context, *basepb.EditStatusReq) (*basepb.AnyRes, error)
	GetMemberList(context.Context, *GetMemberReq) (*ListMemberRes, error)
	GetMemberDetail(context.Context, *basepb.GetOneReq) (*MemberDetail, error)
}

// UnimplementedMemberServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMemberServiceServer struct {
}

func (*UnimplementedMemberServiceServer) RegisterByMobile(ctx context.Context, req *MobilePasswdReq) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterByMobile not implemented")
}
func (*UnimplementedMemberServiceServer) LoginByMobile(ctx context.Context, req *MobilePasswdReq) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByMobile not implemented")
}
func (*UnimplementedMemberServiceServer) GetMemberForLogin(ctx context.Context, req *MemberIdReq) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberForLogin not implemented")
}
func (*UnimplementedMemberServiceServer) AddMember(ctx context.Context, req *Member) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (*UnimplementedMemberServiceServer) EditMember(ctx context.Context, req *Member) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMember not implemented")
}
func (*UnimplementedMemberServiceServer) EditMemberStatus(ctx context.Context, req *basepb.EditStatusReq) (*basepb.AnyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMemberStatus not implemented")
}
func (*UnimplementedMemberServiceServer) GetMemberList(ctx context.Context, req *GetMemberReq) (*ListMemberRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberList not implemented")
}
func (*UnimplementedMemberServiceServer) GetMemberDetail(ctx context.Context, req *basepb.GetOneReq) (*MemberDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberDetail not implemented")
}

func RegisterMemberServiceServer(s *grpc.Server, srv MemberServiceServer) {
	s.RegisterService(&_MemberService_serviceDesc, srv)
}

func _MemberService_RegisterByMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MobilePasswdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).RegisterByMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.MemberService/RegisterByMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).RegisterByMobile(ctx, req.(*MobilePasswdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_LoginByMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MobilePasswdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).LoginByMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.MemberService/LoginByMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).LoginByMobile(ctx, req.(*MobilePasswdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_GetMemberForLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).GetMemberForLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.MemberService/GetMemberForLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).GetMemberForLogin(ctx, req.(*MemberIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Member)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.MemberService/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).AddMember(ctx, req.(*Member))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_EditMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Member)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).EditMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.MemberService/EditMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).EditMember(ctx, req.(*Member))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_EditMemberStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(basepb.EditStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).EditMemberStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.MemberService/EditMemberStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).EditMemberStatus(ctx, req.(*basepb.EditStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_GetMemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).GetMemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.MemberService/GetMemberList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).GetMemberList(ctx, req.(*GetMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_GetMemberDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(basepb.GetOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).GetMemberDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.MemberService/GetMemberDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).GetMemberDetail(ctx, req.(*basepb.GetOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "memberpb.MemberService",
	HandlerType: (*MemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterByMobile",
			Handler:    _MemberService_RegisterByMobile_Handler,
		},
		{
			MethodName: "LoginByMobile",
			Handler:    _MemberService_LoginByMobile_Handler,
		},
		{
			MethodName: "GetMemberForLogin",
			Handler:    _MemberService_GetMemberForLogin_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _MemberService_AddMember_Handler,
		},
		{
			MethodName: "EditMember",
			Handler:    _MemberService_EditMember_Handler,
		},
		{
			MethodName: "EditMemberStatus",
			Handler:    _MemberService_EditMemberStatus_Handler,
		},
		{
			MethodName: "GetMemberList",
			Handler:    _MemberService_GetMemberList_Handler,
		},
		{
			MethodName: "GetMemberDetail",
			Handler:    _MemberService_GetMemberDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memberpb/member.proto",
}
