// Code generated by protoc-gen-go. DO NOT EDIT.
// source: memberpb/payment.proto

package memberpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentCode int32

const (
	PaymentCode_CodeNone PaymentCode = 0
	PaymentCode_Wechat   PaymentCode = 1
	PaymentCode_Alipay   PaymentCode = 2
)

var PaymentCode_name = map[int32]string{
	0: "CodeNone",
	1: "Wechat",
	2: "Alipay",
}

var PaymentCode_value = map[string]int32{
	"CodeNone": 0,
	"Wechat":   1,
	"Alipay":   2,
}

func (x PaymentCode) String() string {
	return proto.EnumName(PaymentCode_name, int32(x))
}

func (PaymentCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b614f87eb7e5cee8, []int{0}
}

type PaymentType int32

const (
	PaymentType_TypeNone PaymentType = 0
	PaymentType_Order    PaymentType = 1
	PaymentType_Recharge PaymentType = 2
)

var PaymentType_name = map[int32]string{
	0: "TypeNone",
	1: "Order",
	2: "Recharge",
}

var PaymentType_value = map[string]int32{
	"TypeNone": 0,
	"Order":    1,
	"Recharge": 2,
}

func (x PaymentType) String() string {
	return proto.EnumName(PaymentType_name, int32(x))
}

func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b614f87eb7e5cee8, []int{1}
}

type PaymentStatus int32

const (
	PaymentStatus_StatusNone  PaymentStatus = 0
	PaymentStatus_Unpaid      PaymentStatus = 1
	PaymentStatus_PaySuccess  PaymentStatus = 2
	PaymentStatus_StatusOther PaymentStatus = 3
)

var PaymentStatus_name = map[int32]string{
	0: "StatusNone",
	1: "Unpaid",
	2: "PaySuccess",
	3: "StatusOther",
}

var PaymentStatus_value = map[string]int32{
	"StatusNone":  0,
	"Unpaid":      1,
	"PaySuccess":  2,
	"StatusOther": 3,
}

func (x PaymentStatus) String() string {
	return proto.EnumName(PaymentStatus_name, int32(x))
}

func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b614f87eb7e5cee8, []int{2}
}

type PaymentParams struct {
	SourceId             string   `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id"`
	Money                float64  `protobuf:"fixed64,2,opt,name=money,proto3" json:"money"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentParams) Reset()         { *m = PaymentParams{} }
func (m *PaymentParams) String() string { return proto.CompactTextString(m) }
func (*PaymentParams) ProtoMessage()    {}
func (*PaymentParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_b614f87eb7e5cee8, []int{0}
}

func (m *PaymentParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentParams.Unmarshal(m, b)
}
func (m *PaymentParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentParams.Marshal(b, m, deterministic)
}
func (m *PaymentParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentParams.Merge(m, src)
}
func (m *PaymentParams) XXX_Size() int {
	return xxx_messageInfo_PaymentParams.Size(m)
}
func (m *PaymentParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentParams.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentParams proto.InternalMessageInfo

func (m *PaymentParams) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *PaymentParams) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

type ToAdd struct {
	MemberId             uint64           `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	Type                 PaymentType      `protobuf:"varint,2,opt,name=type,proto3,enum=memberpb.PaymentType" json:"type"`
	PaymentCode          PaymentCode      `protobuf:"varint,3,opt,name=payment_code,json=paymentCode,proto3,enum=memberpb.PaymentCode" json:"payment_code"`
	Ip                   string           `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip"`
	Params               []*PaymentParams `protobuf:"bytes,5,rep,name=params,proto3" json:"params"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ToAdd) Reset()         { *m = ToAdd{} }
func (m *ToAdd) String() string { return proto.CompactTextString(m) }
func (*ToAdd) ProtoMessage()    {}
func (*ToAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_b614f87eb7e5cee8, []int{1}
}

func (m *ToAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToAdd.Unmarshal(m, b)
}
func (m *ToAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToAdd.Marshal(b, m, deterministic)
}
func (m *ToAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToAdd.Merge(m, src)
}
func (m *ToAdd) XXX_Size() int {
	return xxx_messageInfo_ToAdd.Size(m)
}
func (m *ToAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ToAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ToAdd proto.InternalMessageInfo

func (m *ToAdd) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *ToAdd) GetType() PaymentType {
	if m != nil {
		return m.Type
	}
	return PaymentType_TypeNone
}

func (m *ToAdd) GetPaymentCode() PaymentCode {
	if m != nil {
		return m.PaymentCode
	}
	return PaymentCode_CodeNone
}

func (m *ToAdd) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ToAdd) GetParams() []*PaymentParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type ToEdit struct {
	PaymentId            string        `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id"`
	Status               PaymentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=memberpb.PaymentStatus" json:"status"`
	PaymentCode          PaymentCode   `protobuf:"varint,3,opt,name=payment_code,json=paymentCode,proto3,enum=memberpb.PaymentCode" json:"payment_code"`
	Money                float64       `protobuf:"fixed64,4,opt,name=money,proto3" json:"money"`
	PayedMsg             string        `protobuf:"bytes,5,opt,name=payed_msg,json=payedMsg,proto3" json:"payed_msg"`
	TradeNo              string        `protobuf:"bytes,6,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ToEdit) Reset()         { *m = ToEdit{} }
func (m *ToEdit) String() string { return proto.CompactTextString(m) }
func (*ToEdit) ProtoMessage()    {}
func (*ToEdit) Descriptor() ([]byte, []int) {
	return fileDescriptor_b614f87eb7e5cee8, []int{2}
}

func (m *ToEdit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToEdit.Unmarshal(m, b)
}
func (m *ToEdit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToEdit.Marshal(b, m, deterministic)
}
func (m *ToEdit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToEdit.Merge(m, src)
}
func (m *ToEdit) XXX_Size() int {
	return xxx_messageInfo_ToEdit.Size(m)
}
func (m *ToEdit) XXX_DiscardUnknown() {
	xxx_messageInfo_ToEdit.DiscardUnknown(m)
}

var xxx_messageInfo_ToEdit proto.InternalMessageInfo

func (m *ToEdit) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *ToEdit) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return PaymentStatus_StatusNone
}

func (m *ToEdit) GetPaymentCode() PaymentCode {
	if m != nil {
		return m.PaymentCode
	}
	return PaymentCode_CodeNone
}

func (m *ToEdit) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *ToEdit) GetPayedMsg() string {
	if m != nil {
		return m.PayedMsg
	}
	return ""
}

func (m *ToEdit) GetTradeNo() string {
	if m != nil {
		return m.TradeNo
	}
	return ""
}

type PaymentRes struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id"`
	Money                float64  `protobuf:"fixed64,3,opt,name=money,proto3" json:"money"`
	State                uint32   `protobuf:"varint,2,opt,name=state,proto3" json:"state"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRes) Reset()         { *m = PaymentRes{} }
func (m *PaymentRes) String() string { return proto.CompactTextString(m) }
func (*PaymentRes) ProtoMessage()    {}
func (*PaymentRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_b614f87eb7e5cee8, []int{3}
}

func (m *PaymentRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRes.Unmarshal(m, b)
}
func (m *PaymentRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRes.Marshal(b, m, deterministic)
}
func (m *PaymentRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRes.Merge(m, src)
}
func (m *PaymentRes) XXX_Size() int {
	return xxx_messageInfo_PaymentRes.Size(m)
}
func (m *PaymentRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRes.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRes proto.InternalMessageInfo

func (m *PaymentRes) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *PaymentRes) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *PaymentRes) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func init() {
	proto.RegisterEnum("memberpb.PaymentCode", PaymentCode_name, PaymentCode_value)
	proto.RegisterEnum("memberpb.PaymentType", PaymentType_name, PaymentType_value)
	proto.RegisterEnum("memberpb.PaymentStatus", PaymentStatus_name, PaymentStatus_value)
	proto.RegisterType((*PaymentParams)(nil), "memberpb.PaymentParams")
	proto.RegisterType((*ToAdd)(nil), "memberpb.ToAdd")
	proto.RegisterType((*ToEdit)(nil), "memberpb.ToEdit")
	proto.RegisterType((*PaymentRes)(nil), "memberpb.PaymentRes")
}

func init() { proto.RegisterFile("memberpb/payment.proto", fileDescriptor_b614f87eb7e5cee8) }

var fileDescriptor_b614f87eb7e5cee8 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcf, 0x8e, 0x12, 0x4f,
	0x10, 0xfe, 0xcd, 0xc0, 0xb0, 0x50, 0xec, 0xb2, 0x93, 0x0e, 0x3f, 0x1d, 0x35, 0x46, 0xe4, 0x84,
	0x1c, 0x20, 0xb2, 0x1e, 0xbc, 0xb2, 0xc6, 0x03, 0x89, 0xee, 0x92, 0x59, 0xcc, 0x26, 0x5e, 0x48,
	0x33, 0x5d, 0x81, 0x4e, 0x9c, 0xe9, 0x4e, 0x77, 0x63, 0x32, 0xaf, 0xe8, 0x53, 0xf8, 0x28, 0xa6,
	0xbb, 0x67, 0x80, 0x04, 0x8d, 0x07, 0x4f, 0xd3, 0xf5, 0xe7, 0xab, 0xaa, 0xef, 0xab, 0x1a, 0x78,
	0x92, 0x63, 0xbe, 0x41, 0x25, 0x37, 0x53, 0x49, 0xcb, 0x1c, 0x0b, 0x33, 0x91, 0x4a, 0x18, 0x41,
	0xda, 0xb5, 0x7f, 0x78, 0x0b, 0x57, 0x4b, 0x1f, 0x5a, 0x52, 0x45, 0x73, 0x4d, 0x5e, 0x40, 0x47,
	0x8b, 0xbd, 0xca, 0x70, 0xcd, 0x59, 0x12, 0x0c, 0x82, 0x51, 0x27, 0x6d, 0x7b, 0xc7, 0x82, 0x91,
	0x3e, 0x44, 0xb9, 0x28, 0xb0, 0x4c, 0xc2, 0x41, 0x30, 0x0a, 0x52, 0x6f, 0x0c, 0x7f, 0x04, 0x10,
	0xad, 0xc4, 0x9c, 0x31, 0x0b, 0xf6, 0x95, 0x6b, 0x70, 0x33, 0xad, 0x5a, 0x2d, 0x18, 0x79, 0x03,
	0x4d, 0x53, 0x4a, 0x74, 0xd8, 0xde, 0xec, 0xff, 0x49, 0x3d, 0xc3, 0xa4, 0x1a, 0x60, 0x55, 0x4a,
	0x4c, 0x5d, 0x0a, 0x79, 0x0f, 0x97, 0xd5, 0xc0, 0xeb, 0x4c, 0x30, 0x4c, 0x1a, 0x7f, 0x80, 0x7c,
	0x10, 0x0c, 0xd3, 0xae, 0x3c, 0x1a, 0xa4, 0x07, 0x21, 0x97, 0x49, 0xd3, 0xcd, 0x1d, 0x72, 0x49,
	0xa6, 0xd0, 0x92, 0x8e, 0x58, 0x12, 0x0d, 0x1a, 0xa3, 0xee, 0xec, 0xe9, 0x59, 0x0d, 0xcf, 0x3b,
	0xad, 0xd2, 0x86, 0x3f, 0x03, 0x68, 0xad, 0xc4, 0x47, 0xc6, 0x0d, 0x79, 0x09, 0x50, 0x4f, 0x71,
	0xd0, 0xa2, 0x53, 0x79, 0x16, 0xcc, 0x96, 0xd6, 0x86, 0x9a, 0xbd, 0xae, 0x18, 0x9d, 0x97, 0x7e,
	0x70, 0xe1, 0xb4, 0x4a, 0xfb, 0x07, 0x56, 0x07, 0xdd, 0x9b, 0x27, 0xba, 0x5b, 0xb5, 0x25, 0x2d,
	0x91, 0xad, 0x73, 0xbd, 0x4d, 0x22, 0xbf, 0x2a, 0xe7, 0xf8, 0xac, 0xb7, 0xe4, 0x19, 0xb4, 0x8d,
	0xa2, 0x0c, 0xd7, 0x85, 0x48, 0x5a, 0x2e, 0x76, 0xe1, 0xec, 0x3b, 0x31, 0x7c, 0x04, 0xa8, 0x3a,
	0xa5, 0xa8, 0xff, 0xc6, 0xf2, 0xd0, 0xba, 0x71, 0xda, 0xba, 0x0f, 0x91, 0x25, 0xe5, 0x97, 0x79,
	0x95, 0x7a, 0x63, 0x7c, 0x03, 0xdd, 0x13, 0x0a, 0xe4, 0x12, 0xda, 0xf6, 0x7b, 0x27, 0x0a, 0x8c,
	0xff, 0x23, 0x00, 0xad, 0x47, 0xcc, 0x76, 0xd4, 0xc4, 0x81, 0x7d, 0xcf, 0xbf, 0x71, 0x49, 0xcb,
	0x38, 0x1c, 0xbf, 0x3b, 0x80, 0xec, 0x01, 0x58, 0x90, 0xfd, 0x56, 0xa0, 0x0e, 0x44, 0xf7, 0x8a,
	0xa1, 0x8a, 0x03, 0x1b, 0x48, 0x2d, 0x5e, 0x6d, 0x31, 0x0e, 0xc7, 0x9f, 0x0e, 0x77, 0xeb, 0x45,
	0x26, 0x3d, 0x00, 0xff, 0x3a, 0xb6, 0xfb, 0x52, 0x48, 0xca, 0x59, 0x1c, 0xd8, 0xd8, 0x92, 0x96,
	0x0f, 0xfb, 0x2c, 0x43, 0xad, 0xe3, 0x90, 0x5c, 0x43, 0xd7, 0xe7, 0xde, 0x9b, 0x1d, 0xaa, 0xb8,
	0x31, 0x33, 0xd0, 0xab, 0xab, 0xa1, 0xfa, 0xce, 0x33, 0xb4, 0xcb, 0x9d, 0x33, 0xb6, 0xa4, 0x25,
	0xb9, 0x3e, 0xee, 0xc7, 0x1d, 0xf9, 0xf3, 0xfe, 0xd9, 0xc2, 0xac, 0x8c, 0x6f, 0xe1, 0xc2, 0x1e,
	0x8d, 0x45, 0xc4, 0xa7, 0x08, 0xeb, 0xfc, 0x3d, 0xe4, 0xf6, 0xf5, 0xd7, 0x57, 0x5b, 0x6e, 0x76,
	0xfb, 0xcd, 0x24, 0x13, 0xf9, 0x54, 0xef, 0x78, 0x91, 0xf3, 0xad, 0x98, 0xca, 0xcd, 0xb4, 0xce,
	0xde, 0xb4, 0xdc, 0xff, 0x7a, 0xf3, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x02, 0xf6, 0x0c, 0xad, 0xc9,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	AddPay(ctx context.Context, in *ToAdd, opts ...grpc.CallOption) (*PaymentRes, error)
	EditPay(ctx context.Context, in *ToEdit, opts ...grpc.CallOption) (*PaymentRes, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) AddPay(ctx context.Context, in *ToAdd, opts ...grpc.CallOption) (*PaymentRes, error) {
	out := new(PaymentRes)
	err := c.cc.Invoke(ctx, "/memberpb.PaymentService/AddPay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) EditPay(ctx context.Context, in *ToEdit, opts ...grpc.CallOption) (*PaymentRes, error) {
	out := new(PaymentRes)
	err := c.cc.Invoke(ctx, "/memberpb.PaymentService/EditPay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	AddPay(context.Context, *ToAdd) (*PaymentRes, error)
	EditPay(context.Context, *ToEdit) (*PaymentRes, error)
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_AddPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToAdd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AddPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.PaymentService/AddPay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AddPay(ctx, req.(*ToAdd))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_EditPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToEdit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).EditPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberpb.PaymentService/EditPay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).EditPay(ctx, req.(*ToEdit))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "memberpb.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPay",
			Handler:    _PaymentService_AddPay_Handler,
		},
		{
			MethodName: "EditPay",
			Handler:    _PaymentService_EditPay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memberpb/payment.proto",
}
